dequelabs/axe-core

- bower.json
> Use forked node-uuid without explicitly publish to global object

- doc/handlebars_reason.md
The HTML angle brackets were being double escaped. Mad changes to prevent this
> prevent the double escaping

- lib/checks/color/color-contrast.js
- lib/commons/color/get-background-color.js
- lib/commons/color/get-foreground-color.js
- lib/rules/color-contrast.json
- test/commons/color/get-background-color.js
- test/commons/color/get-foreground-color.js
- Running the audit before would scroll the viewport to the bottom of the page.
[Closes #147]
> Fix viewport scroll bug

- doc/API.md
This corrects a small point of confusion in the documentation in which an example uses specific rule ids, but the text describing the example uses generic variable names.
> corrects minor typo in docs

- doc/API.md
The API documentation originally had:
a11yCheck
- purpose
- description
- synopsis
- parameters
- results
- a11yCheck parameters
- context
- options
- callback
The documentation for the a11yCheck parameters was split up. There was a brief 'overview' of the parameters after the synopsis, then the more detailed section about each individual parameter was *after* the return/results object documentation.
This change simply unifies the parameter documentation to a single location, following the same pattern as for the other documented public methods.
Additionally, with the simplified outline for the a11yCheck method, more deep-links were added to the TOC at the top. (deep linking to the parameters section itself, as well as to the details for each of the three parameters)
No changes to the …
> Reorder Results/Parameters section in API doc

- Gruntfile.js
To reduce the file size of axe-core/index.js, I updated Grunt to send this file through its own minify/uglify path. Previously, it was "nodefied" before being stripped of comments, so those all ended up in the exported module.
This change reduces the exported module's filesize from 235kb to 112kb.
> Uglify nodefied index.js script

- doc/API.md
Adding examples to the API documentation to better describe "array of arrays" when using iframes in the Context Parameter's 'include-exclude object'
> API Documentation Update

- lib/core/base/context.js
- test/core/base/context.js
I came across this issue while using `axe-core` in the `ember-a11y-testing` project, and I [made some notes](https://github.com/ember-a11y/ember-a11y-testing/issues/29) there that may make for a useful reference, but to elaborate...
When axe.a11yCheck is passed an HTMLFormElement node as its context, and when that element contains nested controls (for example: `HTMLInputElement` nodes), an error will be thrown within the `parseSelectorArray` function because it's [currently checking](https://github.com/dequelabs/axe-core/blob/4ef74435ac92a88c602690ac1e243c404f750d00/lib/core/base/context.js#L131) whether or not the `item` is an array with `if (item && item.length)`, and `length` also happens to be a [property of `HTMLFormElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormEl …
> Exclude DOM Nodes when testing for arrays in parseSelectorArray

- package.json
- test/integration/full/jquery/a11ycheck-object-exclude.html
- test/integration/full/jquery/a11ycheck-object-exclude.js
- test/integration/full/jquery/a11ycheck-object-include.html
- test/integration/full/jquery/a11ycheck-object-include.js
- test/integration/full/jquery/a11ycheck-object.html
- test/integration/full/jquery/a11ycheck-object.js
Closes https://github.com/dequelabs/axe-core/issues/194
> Add tests for jQuery objects, include/exclude

- Gruntfile.js
https://github.com/gruntjs/grunt-contrib-uglify/issues/366
This change very specifically defines which comments will be kept - which only includes those starting with /*!
This has been tested in the building of axe.min.js
> Fix preserveComments in uglify which was not removing any comments

- lib/commons/color/get-background-color.js
- lib/commons/dom/elements-from-point.js
- test/checks/color/color-contrast.js
I was seeing false negatives (not seeing contrast errors that should be detected) on pages where there was a sticky header attached to the viewport, while using the axe chrome extension. After diving into the issue, I discovered that it was due to axe scrolling to the element while testing a page. Scrolling to the element would place the element at the top of the page, which would also place the element behind a sticky header. Because axe tries to be smart and determine the background via visual order, it was finding the sticky header instead of the element with bad contrast.
For example, view https://mfairchild365.github.io/axe-contrast-bug/
That example has two contrast errors, but axe only finds one (on the sticky header).
Note: I'm not confident that the automated tests will detect if …
> Improve contrast detection for elements that are behind another element

- typings/axe-core/axe-core-tests.ts
- typings/axe-core/axe-core.d.ts
Need to publish this to npm so we can utilize the typings for both axe-core and avoid a second definition for axe-webdriverjs (for now).
> test(typescript-def): add source and AxeResults

- .gitignore
- .npmignore
- axe.d.ts
- package.json
- typings/axe-core/axe-core-tests.ts
This PR fixes axe-core import in Angular 2 app tests when distributed through npm instead of DefinitelyTyped. There were problems importing the definitions into Angular 2 from npm, so after troubleshooting I moved the definition to the root and added some .npmignore/.gitignore rules for extraneous files. I kept axe's TypeScript export as-is to support a wider variety of compiler versions (`export = axe` instead of `export default axe`). 
TypeScript usage: `import * as axe from 'axe-core'`
> Fix npm TypeScript definition for Angular 2 apps

- .travis.yml
- package.json
so that global grunt-cli installation is not required
---
`npm run build` expected to `grunt` in the `PATH` and failed as there was none. Installing grunt as a devDependencies solves the problem 
>In addition to the shell's pre-existing `PATH`, `npm run` adds `node_modules/.bin` to the `PATH` provided to scripts. Any binaries provided by `locally-installed` dependencies can be used without the `node_modules/.bin` prefix - [npm/run-script](https://docs.npmjs.com/cli/run-script#description)
> chore(deps): added grunt-cli as devDependencies

- CONTRIBUTING.md
The fix for #248 is already on master but we need to publish it in a new release. This PR updates documentation for consuming the aXe TypeScript definition, which is now available at the root of the directory instead of inside the `typings` folder. The tests are still in that directory but they are excluded in `.npmignore`. 
I tested the aXe definition with both our TypeScript tests and this demo project: https://github.com/marcysutton/ng2-test-seed.
More info about publishing `d.ts` files: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
> docs(typescript): fix path and update usage

- lib/core/base/rule.js
- test/core/base/rule.js
This diff will modify Rule#run so that the `DqElement` wrapping of a node when gathering rule check results is deferred until it's been established that the result will actually be used.
This seems to have some performance impact since (at least in my own tests) the vast majority of runs ends up with a non empty aggregate result set, but with only empty results. This situation leads to a lot of work being spent finding the selector of a node unnecessarily.
> Avoid calling `DqElement` unnecessarily when gathering results

- lib/core/base/context.js
- test/core/base/context.js
Right now, if context is given as `{include: [], exclude[]}`, the `include` piece does not get properly defaulted to `[document]`.
The following are already accepted and work as expected:
- `{include: null}`
- `{include: undefined}`
- `{include: ""}`
- `{exclude: []}`
I don't think there is an appreciable difference for the `include` key between `null`, `undefined`, `""` and `[]`, so I think the following should be supported as well:
`{include: []}`
(To be fair, right now any falsey value for `include` would default to `[document]`, but I'm not suggesting that `0` or `false` should be supported, even though they current work.)
(code hand-edited directly on github, so it probably doesn't conform to style-guidelines)
> Allow `include` to be specified, but empty

- lib/commons/dom/is-offscreen.js
- test/commons/dom/is-offscreen.js
From my tests, an element should be considered 'off the screen' if it is a non-zero-width element and its right edge is <= 0, not just < 0.
> Improve isOffScreen() detection

- lib/commons/aria/attributes.js
- lib/commons/aria/roles.js
- test/commons/aria/roles.js
This fixes #290.
This is my first PR to this repository; I would much appreciate a code review. See also code comments pertaining to helper functions.
In case of multiple implicit roles existing for a node, we need to infer the expected implicit context based on a combination of applied aria-attributes for the node, and which of these are applicable to the existing implicit roles.
Each implicit role is given a score based on the combination of aria-attributes for the role, and the list of aria-attributes for the node.
The highest scoring role is returned. When multiple equally highest scored roles exist, the first is returned.
> Return optimally suited implicit role for a node

- Gruntfile.js
Uglify:beautify wasn't picking up the custom preserveComments function for axe.js. This fix adds the banner back in to that file.
> fix: add copyright banner back in to axe.js

- lib/checks/color/link-in-text-block.js
- lib/commons/color/get-background-color.js
- lib/commons/color/get-foreground-color.js
- lib/commons/color/incomplete-data.js
The incompleteData API for color-contrast was causing a circular dependency by including nodes. They weren't being used, so they're gone with this commit.
> fix: remove circular dep from incompleteData

- lib/checks/color/color-contrast.js
- lib/checks/color/link-in-text-block.js
- lib/commons/color/get-background-color.js
- lib/commons/color/get-foreground-color.js
- lib/commons/color/incomplete-data.js
- lib/core/utils/publish-metadata.js
- test/checks/color/color-contrast.js
- test/checks/color/link-in-text-block.js
- test/commons/color/get-background-color.js
- test/commons/color/get-foreground-color.js
- test/commons/color/incomplete-data.js
If check result doesn't supply a reason, it is difficult to handle fallbacks as written. This change simplifies things now that missingData doesn't include nodes (due to a circular dependency). The one caveat is it now can't handle floating up multiple reasons.
This issue makes our Attest extension not error out if there is no missingData, and it solves an internal issue where color contrast is listed in the extension but comes back with a count of 0. (https://dequesrc.atlassian.net/browse/WWD-726)
> Handle missing data

- lib/checks/color/color-contrast.js
- lib/checks/color/link-in-text-block.js
- lib/core/utils/publish-metadata.js
- test/checks/color/color-contrast.js
- test/checks/color/link-in-text-block.js
- test/core/utils/publish-metadata.js
To make axe-core more backwards-compatible, I reverted part of yesterday's change to incomplete check results so they use the same key (`missingData` instead of `missingReason`). I also added some logic and test coverage in case a rule depends on the 2.2.0 version.
> API compatibility for incompleteData

- build/configure.js
- build/tasks/add-locale.js
- lib/core/base/audit.js
- lib/core/reporters/helpers/incomplete-fallback-msg.js
- lib/core/utils/publish-metadata.js
- lib/misc/incomplete-fallback.json
- locales/nl.json
- test/core/reporters/helpers/incomplete-fallback-msg.js
- test/core/utils/publish-metadata.js
I added the ability to localize the fallback message. This makes it so that if a check doesn't supply a default incomplete message or reasons, aXe will still return _something_ in the appropriate language.
> feat: localize incomplete fallback message

- doc/API.md
- lib/core/base/check.js
- lib/core/base/rule.js
- lib/core/utils/check-helper.js
- lib/core/utils/collect-results-from-frames.js
- lib/core/utils/dq-element.js
- lib/core/utils/get-check-option.js
- lib/core/utils/get-friendly-uri-end.js
- lib/core/utils/get-selector.js
- lib/core/utils/merge-results.js
- lib/core/utils/pollyfills.js
- test/core/base/check.js
- test/core/base/rule.js
- test/core/public/run.js
- test/core/utils/check-helper.js
- test/core/utils/dq-element.js
- test/core/utils/get-check-option.js
- test/core/utils/get-friendly-uri-end.js
- test/core/utils/get-selector.js
- test/integration/rules/duplicate-id/duplicate-id.json
Rebuild the getSelector method, to return selectors that are more readable, shorter and more durable. In addition, the absolutePaths option was added which will return full paths to elements, rather then the shortest possible selectors we could find.
> Rebuild getSelector

- CHANGELOG
- axe.d.ts
- doc/projects.md
- doc/rule-descriptions.md
- lib/checks/color/color-contrast.json
- lib/commons/color/get-background-color.js
- lib/commons/dom/visually-contains.js
- lib/rules/link-in-text-block.json
- package.json
- test/checks/color/color-contrast.js
- test/commons/color/get-background-color.js
- test/commons/dom/visually-contains.js
- test/integration/rules/color-contrast/color-contrast.html
- test/integration/rules/color-contrast/color-contrast.json
To address default implicit labels and inputs returning as Can't Tell (due to what it thinks is bgOverlap), this change adds some logic to the `calculateObscuringAlpha` function in `lib/commons/color/get-background-color.js` to check if an element's top left corner is actually overlapping in addition to returning the alpha value. I based it on the top left corner and not the center point because of the problem I was trying to solve–inputs being nested in implicit labels with the default styling causing an incomplete result.
I ran into issues with the integration tests because axe-core sometimes returns the label as the node, and sometimes the label and the input, depending on whether the tests are running in `grunt dev` or `grunt test-fast`. The runner used for our integration tests …
> Fix bugs with implicit labels and TRs for color contrast

- lib/checks/navigation/href-no-hash.json
- lib/rules/href-no-hash.json
I noticed the copy in this rule when I was testing extensions with best practice rules turned on. Because help text is used in the sidebar of our new extensions, it read poorly compared to the help text in other rules.
Here's the commit where the text originated: https://github.com/dequelabs/axe-core/commit/e0ebdea70fcc1e1c6b7abb82c1467d3031630474
> fix: update copy in href-no-hash best practice rule

- doc/API.md
We've gotten questions about the new category mappings added in https://github.com/dequelabs/axe-core/commit/fe829e2b47c067d67dd8f0e33875ab05885d2b63, so I listed them out in API.md.
I considered listing which rules these apply to, but we'd have to maintain it...and since these are only used by Deque internally it didn't seem worth it. Let me know if this needs more detail.
Closes https://dequesrc.atlassian.net/browse/WWD-698
> doc: explain category mappings

- lib/core/index.js
axe-webdriverjs wasn’t running properly because axe.source wasn’t getting the window object passed in correctly.
> fix: Update axe.source to work with Firefox webdriver

- package.json
I almost forgot to run `grunt build` before `npm publish` again today, so this script makes sure that doesn't happen. `prepublishOnly` will run before the module is published, but not on npm install. We could potentially run it as `prepublish` to get both of those. That might actually simplify other projects, like attest-standards.
More on npm scripts including `prepublishOnly`: https://docs.npmjs.com/misc/scripts
> chore: ensure package is built before publishing

- build/tasks/testconfig.js
A message will be printed out explaining the task purpose when running
`grunt --help`
Related #364 
____
Using the `[description]` parameter from https://gruntjs.com/creating-tasks#basic-tasks
Before:
```console
test-webdriver  Custom multi task. *
testconfig  Custom multi task. *
update-help  Custom multi task. *
```
After:
```console
test-webdriver  Custom multi task. *
testconfig  This task creates a file with all the source test config and
HTML fixutres in a single JS object "test" *
update-help  Custom multi task. *
```
> chore: add help text for testconfig Grunt task

- build/tasks/test-webdriver.js
- test/commons/color/get-background-color.js
- test/commons/color/get-foreground-color.js
- test/integration/full/options/options.js
- Errors got swallowed by the browser testrunner. That’s fixed now
- Chrome was failing one of the tests due to not cleaning up scroll position
> fix offScreen test failing in Chrome

- lib/core/base/audit.js
- test/core/base/audit.js
Small fix to ensure the stack is always exposed when a check throws an exception. This should make it much easier for us to track down problems people find in axe using the extensions.
> fix: Properly output error stack

- lib/commons/color/get-background-color.js
- test/commons/color/get-background-color.js
This should fix a false positive color contrast issue on https://www.alaskaair.com/. At the bottom of the page, there is a server number, and an image. The element containing the background was scrolled up by `scrollIntoView()`, causing the server number to be on the wrong background. By passing `false` to `scrollIntoView()`, we prevent it scrolling too much. We only need the top of the element to align with the top of the viewport, when the element is very very tall. Otherwise `elementsFromPoint` would be passed a negative number, which it doesn't understand.
> fix: Minimise scrolling in getBackgroundColor

- doc/API.md
- lib/core/public/run-rules.js
- lib/core/utils/scroll-state.js
- test/core/public/run.js
- test/core/utils/scroll-state.js
- test/playground.html
With this setting, axe will remember the scroll position of all elements that can scroll, and restore them once analyse is done.
> feat: Add option restoreScroll

- build/templates.js
- lib/checks/.jshintrc
- lib/checks/label/help-same-as-label.js
- lib/commons/text/accessible-text.js
- test/checks/label/help-same-as-label.js
fixes #387 
Also exposes the virtualNode to the check code
> fix: help-same-as-label for shadow DOM

- lib/checks/label/title-only.js
- test/checks/label/title-only.js
Closes https://github.com/dequelabs/axe-core/issues/388
> fix: use virtualNode in title-only check

- lib/core/utils/flattened-tree.js
- test/core/utils/contains.js
- test/core/utils/flattened-tree.js
The current implementation does not include the shadow host as it clearly should according to step 2 in the algorithm here https://drafts.csswg.org/css-scoping/#flat-tree
> include the shadow host in the flattened tree

- lib/checks/color/link-in-text-block.json
- lib/checks/keyboard/accesskeys.json
- lib/checks/lists/listitem.json
- lib/checks/media/description.json
- lib/checks/navigation/header-present.json
- lib/checks/navigation/heading-order.json
- lib/checks/navigation/internal-link-present.json
- lib/checks/navigation/p-as-heading.json
- lib/checks/navigation/skip-link.json
- lib/checks/shared/aria-label.json
- lib/checks/shared/aria-labelledby.json
- lib/checks/shared/doc-has-title.json
- lib/checks/shared/has-visible-text.json
- lib/checks/shared/is-on-screen.json
- lib/checks/shared/non-empty-title.json
- lib/checks/shared/role-none.json
- lib/checks/shared/role-presentation.json
- lib/checks/tables/caption-faked.json
- lib/checks/tables/html5-scope.json
- lib/checks/tables/same-caption-summary.json
- lib/checks/tables/th-has-data-cells.json
Thanks to the work of Matt Isner, I had a nice list to work from. I’ve double checked that for each impact I changed, it only changes the impact level of the rules I wanted to change. The changes are as follow:
| Rule			| Impact from		| Impact to
|-----------------------|-----------------------|---------------
| accesskeys		| critical		| serious
| blink			| minor			| serious
| marquee		| minor			| serious
| document-title	| moderate		| serious
| duplicate-id		| critical		| moderate
| heading-order		| minor			| moderate
| link-in-text-b	| critical		| serious
| listitem		| critical		| serious
| p-as-heading		| critical		| serious
| scope-attr-val	| critical, serious	| critical, moderate
| server-side-ima	| minor			| critical
| skip-link		| critical		| moderate
| table-duplicate-name	| …
> Align impact levels with Deque Way

- lib/commons/text/visible.js
- lib/rules/.jshintrc
- lib/rules/color-contrast-matches.js
- test/rule-matches/color-contrast-matches.js
This PR builds on #404 to pull in some of the commons already in use.
Closes https://github.com/dequelabs/axe-core/issues/393.
> Shadow DOM support for color contrast matches 

- lib/checks/media/caption.js
- lib/checks/media/description.js
- test/.jshintrc
- test/checks/media/caption.js
- test/checks/media/description.js
- test/testutils.js
> shadowDOM for media checks

- lib/checks/lists/dlitem.js
- lib/checks/lists/has-listitem.js
- lib/checks/lists/listitem.js
- lib/checks/lists/only-dlitems.js
- lib/checks/lists/only-listitems.js
- lib/checks/lists/structured-dlitems.js
- lib/commons/dom/get-composed-parent.js
- test/.jshintrc
- test/checks/lists/dlitem.js
- test/checks/lists/has-listitem.js
- test/checks/lists/listitem.js
- test/checks/lists/only-dlitems.js
- test/checks/lists/only-listitems.js
- test/checks/lists/structured-dlitems.js
- test/commons/dom/get-composed-parent.js
- test/testutils.js
This should solve #427 and #428.
> Add shadow DOM support to list checks

- lib/commons/dom/find-elms-in-context.js
- lib/commons/text/accessible-text.js
- test/checks/forms/fieldset.js
- test/checks/forms/labelledby.js
- test/checks/keyboard/focusable-no-name.js
- test/checks/label/explicit.js
- test/checks/label/implicit.js
- test/checks/lists/only-listitems.js
- test/checks/lists/structured-dlitems.js
- test/checks/shared/aria-labelledby.js
- test/checks/shared/has-visible-text.js
- test/checks/tables/same-caption-summary.js
- test/checks/visibility/hidden-content.js
- test/commons/.jshintrc
- test/commons/dom/find-elms-in-context.js
- test/commons/text/accessible-text.js
- test/testutils.js
> shadowDOM accessible text calculation

- lib/checks/label/explicit.js
- test/checks/label/explicit.js
> Make explicit check consider shadow DOM

- lib/checks/label/duplicate-img-label.js
- test/checks/label/duplicate-img-label.js
- test/testutils.js
> feat: Add shadow DOM to duplicate-img-label check

- lib/checks/label/explicit.js
- lib/commons/dom/find-up.js
- test/checks/lists/dlitem.js
- test/checks/lists/has-listitem.js
- test/checks/lists/listitem.js
- test/checks/lists/only-dlitems.js
- test/checks/lists/only-listitems.js
- test/checks/lists/structured-dlitems.js
- test/checks/navigation/landmark.js
- test/checks/shared/button-has-visible-text.js
- test/commons/dom/find-up.js
> fix: Let findUp work on shadow root children

- lib/checks/aria/required-children.js
- test/checks/aria/required-children.js
- test/checks/keyboard/focusable-no-name.js
- test/testutils.js
I didn't add any shadow DOM tests for `aria-owns` because ID attributes get reset inside of shadow boundaries, so that technique won't work. Are there any other Shadow DOM scenarios I should consider?
Closes https://github.com/dequelabs/axe-core/issues/421
> feat: add shadow support to aria-required-children

- lib/checks/shared/duplicate-id.js
- test/checks/shared/duplicate-id.js
> feat(duplicate-id): Add shadow DOM support

- lib/core/utils/aggregateChecks.js
- test/core/utils/aggregateChecks.js
> fix: Exclude `any` checks from output if one passed

- lib/core/utils/aggregateChecks.js
- lib/core/utils/aggregateRule.js
- test/core/utils/aggregateChecks.js
- test/core/utils/aggregateRule.js
- test/playground.html
This solves a problem we had with the axe-devtools extension, where, if there wasn’t also a violation for that same rule, the impact wouldn’t be available.
> fix: incomplete results should have impact

- lib/checks/aria/required-children.js
- test/checks/aria/required-children.js
Remove textbox from the list of missing roles when checking a combobox node that is a native input element
https://github.com/dequelabs/axe-core/issues/160
> fix(checks/aria/required-children): add exception for native input combobox missing textbox

- build/sri-update.js
- package.json
- sri-history.json
Since axe-core is injected into many many web pages, it is very important that we’re able to check the integrity of the file we’re injecting. Keeping the SRI of all previously published versions around makes this much easier.
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
> feat: Add sri-history file and update process

- CONTRIBUTING.md
correct misspelling in CONTRIBUTING doc
I don't think I've ever spelled license correctly the first time 😊
> fix(docs): add minor spelling fix

- doc/developer-guide.md
- doc/rules.md
Now that people are submitting rules, I thought we could use more documentation about how help text is used and how to create incomplete messages.
> docs: document help text and incomplete messages

- bin/postinstall.sh
- package.json
This hook works on the command line only–for some reason GitX throws an error (a known issue according to the [angular-precommit source code](https://github.com/ajoslin/angular-precommit/blob/master/index.js#L25)). 
I've asked the axe-core team to respond with preferred methods of writing commits so I can test different applications. But this will install the hook automatically, preventing commits which don't adhere to our [commit policy](https://github.com/dequelabs/axe-core/blob/develop/doc/code-submission-guidelines.md#git-commits) (which follows the Angular style).
We can use this in our other projects, too, since it doesn't depend on any specific linter.
> Precommit hook to prevent bad commit messages

- lib/commons/text/accessible-text-virtual.js
- test/commons/text/accessible-text.js
This one seemed easy enough to fix, so I made a PR for it. Essentially we had a client report back in January that a table with role="presentation" and a single table cell was failing the link text rule. That would work fine from an AT perspective, so we decided it was a false positive. But I drew the line on using a single table cell since concatenation of multiple cells would produce horrible link text.
If you have suggestions on how to reduce the complexity, I'm open to changes!
Closes https://dequesrc.atlassian.net/browse/WWD-547 (internal only)
> feat: allow link text from single-cell layout table

- doc/projects.md
Removing accesslint since it no longer uses axe-core.
> chore: remove accesslint from projects

- lib/commons/color/get-background-color.js
- test/commons/color/get-background-color.js
We had a bug report where the background color of some TR elements wasn't getting picked up. Turns out the code for manually adding in TR since it gets missed with document.elementsFromPoint was only checking for TR and TD together, so if the foreground color was on a TH or a child element TR wouldn't get added to the elmStack. This change allows both of those cases to work by making sure TD or TH are present TR to be added, but it doesn't require the element under test to be either of those elements.
> Color contrast support for TH and children of TR elements

- Gruntfile.js
If you've `npm install`ed any of the example projects in examples/, the grunt "jshint" task gets bogged down trying to lint the node_modules/ directory within the example.
> chore: ignore node_modules when linting

- lib/commons/color/get-background-color.js
- test/checks/color/color-contrast.js
`document.elementsFromPoint` does not include the `TBODY` and `THEAD` elements, so contrast was not being calculated correctly under some circumstances involving those elements. See added tests for examples.
> Add missing elements that have a factor on contrast

- README.md
- doc/act-rules-format.md
- doc/developer-guide.md
- doc/rule-development.md
- doc/rule-proposal.md
This PR is designed to do a few things:
1. Streamline how rules get added. We shouldn't have people just creating PRs without discussing ahead of time the rules they are trying to add.
2. Create a standard that we can use to document the rules in. This will help with the transparency of axe-core.
3. Make it easier for us to take axe-core rules and propose them as WCAG ACT Rules.
Here are a few example rules the ACT Taskforce has developed for comparison: wilcofiers.github.io/act-rules/
> docs: Document how to propose axe-core rules

- build/utils/postinstall.js
- package.json
> fix node4 build issue

- doc/API.md
- lib/core/reporters/helpers/process-aggregate.js
- lib/core/reporters/no-passes.js
- test/core/reporters/helpers/process-aggregate.js
This allows us to specify a short list of result types that we want `helper.processAggregate` to bother processing. For some reporting scenarios, we don't want to bother processing 'passes', for instance. This causes a massive performance improvement for those scenarios.
We can leverage this option in the axe extension to speed up performance there as well.
Closes https://github.com/dequelabs/axe-core/issues/512
> perf(reporter): add option to limit result types to be processed

- lib/checks/aria/required-children.js
- test/checks/aria/required-children.js
No longer requires a collapsed combobox to own a child listbox.
The relevant ARIA 1.1 spec: https://www.w3.org/TR/wai-aria-1.1/#combobox
https://github.com/dequelabs/axe-core/issues/548
> fix(required-children): add combobox > listbox exception

- lib/rules/th-has-data-cells.json
Fixes the message to match the prose used in the documentation, as noted in issue #585
> update th-has-data-cells help message

- doc/API.md
I find the existing docs slightly misleading. They seem to suggest that types specified in the option will be limited to one result instead of vice versa, which is actually the case - types _not_ specified get throttled.
> docs: improve docs for resultTypes option

- lib/core/public/load.js
- lib/core/utils/rule-should-run.js
- test/core/public/run-rules.js
> fix: Ensure overloaded Array.prototype won't crash axe

- lib/commons/aria/index.js
- test/checks/aria/allowed-attr.js
- test/integration/rules/aria-allowed-attr/passes.html
- test/integration/rules/aria-allowed-attr/passes.json
This pull-request closes https://github.com/dequelabs/axe-core/issues/540.
> fix(commons/aria): allow aria-required on radio and checkbox roles

- lib/checks/color/color-contrast.json
- lib/commons/color/get-background-color.js
- lib/rules/color-contrast-matches.js
- test/checks/color/color-contrast.js
- test/commons/color/get-background-color.js
- test/integration/rules/color-contrast/color-contrast.html
- test/integration/rules/color-contrast/color-contrast.json
- test/rule-matches/color-contrast-matches.js
We can squash these commits onto 2x. I wanted the chance to review them in a PR, since I had to modify a few things from develop.
> Color fixes 2x

- lib/commons/dom/is-focusable.js
- test/commons/dom/is-natively-focusable.js
Refactor dom.isFocusable to expose dom.isNativelyFocusable. This allows us to distinguish between elements that are in the focus order because of tabindex and elements that are focusable by default.
This allows us to identify elements that are manually inserted into the tab order (i.e. isFocusable && !isNativelyFocusable), or to identify elements with redundant tabindex (e.g. input[tabindex=0])
There is no change in the logic of isFocusable, but it's also true that isNativelyFocusable is not **yet** being used by checks in axe-core, but it's convenient for tools wrapping/extending axe and for the authoring of future rules.
> Refactor dom.isFocusable to expose dom.isNativelyFocusable for convenience

- lib/checks/lists/dlitem.js
- test/integration/full/definition-list/dlitem-xhtml.js
- test/integration/full/definition-list/dlitem-xhtml.xhtml
In XHTML, `element.tagName` preserves the case.
In the `dlitem` check, the tag name is now upper-cased before
being tested as '`DL`', to make the rules works on XHTML documents.
Fixes #581
> Fix the `dlitem` rule for XHTML documents

- lib/core/utils/get-selector.js
- lib/core/utils/is-xhtml.js
- test/core/utils/get-selector.js
- test/core/utils/is-xhtml.js
- test/integration/full/get-selector/get-selector.js
- test/integration/full/get-selector/get-selector.xhtml
- test/integration/full/is-xhtml/is-xhtml.js
- test/integration/full/is-xhtml/is-xhtml.xhtml
> Fix `getSelector` for namespaced elements + introduce XHTML fixtures

- doc/rule-proposal.md
- lib/checks/keyboard/focusable-no-name.js
The existing variable name isFocusable is confusing because it's really asking whether the element is in the focus order. To clarify the difference: elements with tabindex -1 are focusable, elements with tabindex > -1 are in the focus order (and focusable).
Ideally, we can change the incorrect name of the "focusable-no-name" rule to the correct "focus-order-no-name" -- but @marcysutton has [mentioned there may be backwards compatibility issues](https://github.com/dequelabs/axe-core/pull/638#issuecomment-351219583)
> refactor(checks/keyboard): change var names to distinguish being in focus order from being focusable

- lib/commons/dom/is-focusable.js
- test/commons/dom/is-focusable.js
- test/commons/dom/is-natively-focusable.js
Adds tests for disabled/AT-hidden elements with tabindex
fixes #647
> fix(commons/dom): fix isFocusable functions by checking screenreader visibility and enabledness

- README.md
Also removed some badges that do not add a lot of value - probably most controversial is the CircleCI build status badge. Reason I don't think this adds value is that we never merge a change that does not pass CircleCI, so the most important build statuses are the build status of the individual pull requests.
> docs: Add activity and usage badges

- lib/core/base/rule.js
When running things with perfTimer, I noticed sometimes there was significant cost within the runChecks methods, however that wasn't always obvious from the existing performanceTimer measures.
This adds instrumentation around the `runChecks` methods.  
One note is that the intrumentation is synchronous, however checks finish asynchronously. But in my experience, it appears the majority of the cost happens in the first bit of synchronous runChecks work.  So this seems OK.
Screenshot including the nontrivial cost of `runchecks-duplicate-id`:
~[This patch doesn't pass JSHint.](https://user-images.githubusercontent.com/39191/35527867-f7fd761a-04e0-11e8-82ce-54a5b4935d24.png) I'm interested in your suggestions on handling that.~
> perf(perf-timer): add instrumentation for Rule.runChecks

- lib/rules/image-alt.json
- test/integration/rules/image-alt/image-alt.html
We have been advised that best practice is to use the following for inline SVGs:
```
<svg role="img">
<title>SVG Title</title>
</svg>
```
which is echoed in [this article](https://css-tricks.com/accessible-svgs/#article-header-id-6).
I see that there is conversation in this issue https://github.com/dequelabs/axe-core/issues/20 about how to best go about it, but for now the test for `svg[role="img"]` needs to be removed since it isn't really valid.
> fix(rule): Remove coverage of `svg[role="img"]` for image-alt rule

- axe.d.ts
> chore(type-checking): Cannot use only callback in run() without ts error

- lib/core/base/audit.js
- lib/core/base/context.js
- lib/core/utils/qsa.js
- lib/core/utils/select.js
- lib/rules/heading-order.json
- lib/rules/landmark-main-is-top-level.json
- lib/rules/link-in-text-block.json
- test/core/base/audit.js
- test/core/base/context.js
- test/core/base/rule.js
- test/core/utils/qsa.js
- test/core/utils/select.js
Improve the performance of `axe.utils.select`
This gets rid of the need for a sort in all instances except when there is an overlapping include context
Memoizes select so that subsequent calls to `axe.utils.select` from within `Audit.run` will return the cached results
> fix(perf): improve select performance fixes #702

- circle.yml
It's time to upgrade Circle, as "end of 1.0 is on the horizon." Documentation is no longer being updated for 1.0 which makes debugging more difficult. The new system is more containerized with Docker and gives you finer granularity over all the steps. 
Geckodriver didn't work for some reason, but Chromedriver did with the `6.12.3-browsers` node image. It fixed the `chrome:mobile` test failures I saw in #711. https://hub.docker.com/r/circleci/node/tags/ 
Closes https://github.com/dequelabs/axe-core/issues/717
> test: upgrade to CircleCI 2.0

- circle.yml
- lib/commons/color/get-background-color.js
- lib/commons/dom/shadow-elements-from-point.js
- lib/core/utils/flattened-tree.js
- lib/core/utils/is-shadow-root.js
- test/checks/color/color-contrast.js
- test/commons/color/get-background-color.js
- test/commons/color/get-foreground-color.js
- test/commons/dom/shadow-elements-from-point.js
- test/commons/dom/visually-contains.js
- test/core/utils/flattened-tree.js
- test/core/utils/is-shadow-root.js
- test/integration/full/contrast/shadow-dom.html
- test/integration/full/contrast/shadow-dom.js
- test/testutils.js
This PR adds color contrast support for pages with nested Shadow DOM. 
One TODO I still have is to support multiline elements inside of shadow boundaries (inline elements with line breaks, originally added in https://github.com/dequelabs/axe-core/pull/610). The actual background color for those is wrong in this PR because the tree walking across multiple roots doesn't really factor in client rects that partially overlap. I've struggled with it for the past week and decided to punt on it.
Part of the complication is that a shadow host is always returned from `document.elementsFromPoint` regardless of whether its content overlaps (i.e. absolute positioning, etc.). For block elements that don't visually overlap their host element, we have to filter out the host element from the stack or it …
> Shadow support for color contrast

- doc/rule-descriptions.md
- lib/rules/audio-caption.json
> Fix audio-caption SC tag

- lib/rules/label-matches.js
- test/integration/rules/label-title-only/label-title-only.html
- test/integration/rules/label/label.html
- test/rule-matches/label-matches.js
> Prevent label rule from crashing on input without type

- doc/API.md
- lib/core/public/cleanup-plugins.js
- test/core/public/cleanup-plugins.js
axe.cleanup() requires two functional arguments, 'resolve' and 'reject' that are not mentioned in the documentation (I will create a separate pull-request for that).  
This change will define default arguments with reasonable behavior:  default resolve() does nothing and default reject() logs an error message to the console.
This is related to Issue #705 .
> Provide default arguments to axe.cleanup()

- doc/.github/ISSUE_TEMPLATE.md
- doc/.github/PULL_REQUEST_TEMPLATE.md
We have to repeat ourselves a lot in issues and PRs, so it makes sense to add Github templates that point out common things (commit policy, accessibility supported, axe-core/integration versions, etc.). I started with the Angular templates so we may want to make additional changes. I'm open to suggestions!
> Add github templates for issues and PRs

- lib/core/base/audit.js
- lib/core/public/run.js
- lib/core/utils/collect-results-from-frames.js
- lib/core/utils/get-selector.js
- test/core/base/audit.js
- test/core/public/run-rules.js
- test/core/public/run.js
- test/core/utils/collect-results-from-frames.js
- test/core/utils/dq-element.js
- test/core/utils/get-selector.js
- test/core/utils/send-command-to-frame.js
@WilcoFiers Take a look at this commit, it decreases the `querySelectorAll` time on https://www.mlb.com/yankees/schedule/2018-03/list from ~17s to ~7s
> fix(perf): Improve getSelector performance

- doc/rule-descriptions.md
- lib/checks/aria/implicit-role-fallback.js
- lib/checks/aria/implicit-role-fallback.json
- lib/commons/aria/index.js
- lib/rules/aria-dpub-role-fallback-matches.js
- lib/rules/aria-dpub-role-fallback.json
- test/checks/aria/implicit-role-fallback.js
- test/integration/rules/aria-dpub-role-fallback/aria-dpub-role-fallback.html
- test/integration/rules/aria-dpub-role-fallback/aria-dpub-role-fallback.json
- test/integration/rules/aria-roles/aria-roles.html
- test/integration/rules/aria-roles/aria-roles.json
- test/rule-matches/aria-dpub-role-fallback-matches.js
Ensures that DPUB ARIA roles that are unsupported and may have a negative
impact are only used on elements which have a compatible implicit ARIA
role fallback.
**Tags**: cat.aria, wcag2a, wcag131
CSS selector `[role]`
+ JS matcher that matches the elements with the following roles: 'doc-backlink', 'doc-biblioentry', 'doc-biblioref', 'doc-cover', 'doc-endnote', 'doc-glossref', 'doc-noteref'
1. gets the element’s role
2. if there’s no role, or the role is invalid, ignore (return `true`)
3. return `true` if and only if the role’s type is equal to the element’s implicit role (i.e. if the implicit role is a compatible fallback for the explicit role).
This PR implements the rule to complement #584
>  feat(rules): add new rule aria-dpub-role-fallback 

- lib/commons/dom/get-element-by-reference.js
- test/checks/navigation/skip-link.js
If href contains url encoded fragment like "<a href="#%3Ctarget%3E">Click Here</a>" it leads to false positive violation due to no target
> fix(rule): skip-link rule doesn't decode URI encoded href's

- sri-history.json
I validated each of the sri-history entries manually and discovered that the following 3 versions have inaccurate entries:
- 2.4.2
- 2.6.1
- 3.0.0-beta.1
I am personally responsible for adding the 2.4.2 and 2.6.1 entries. I'm fairly certain that I used the build/sri-update tool to generate those entries back when I added them, and today I generated the entries by `npm i`ing axe-core and generating the hash using the sri-toolbox module. I don't see why those two methods would produce different results, so I'm baffled. I'm guessing human error.
> fix: Overwrite incorrect sri-history entries

- doc/developer-guide.md
- doc/rule-development.md
the `pass`, `fail` and `incomplete` messages in the check's `metadata` object have to be in a `messages` object.
> fix documentation of check properties

- lib/rules/button-name.json
- test/integration/rules/button-name/button-name.html
- test/integration/rules/button-name/button-name.json
This change makes it more clear that `title` is allowed for accessible naming of button elements and button inputs.
Closes https://github.com/dequelabs/axe-core/issues/747
Closes https://github.com/dequelabs/axe-core/issues/765
> fix: allow title on button-name

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
> Typings: Fix ElementContext type

- lib/core/utils/respondable.js
- test/core/utils/respondable.js
The most important change here is respondable.js [line 15](https://github.com/dequelabs/axe-core/pull/825/files#diff-addc6dbd1628709793c7399662a26bfeR15), in response to https://github.com/dequelabs/axe-core/issues/818. We want the source comparison string to use the application name when it exists.
Since the Audit's `application` property is being hard-coded [here](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/audit.js#L42) as "axeAPI", this also changes the fallback to match so we're using the same application name everywhere. In practice, even though we had set `application` to "axeAPI", almost all message responses were identified as coming from "axe" because the fallback was being applied.
> Use application name in respondable

- doc/rule-descriptions.md
- lib/rules/video-caption.json
Small fix for an issue that got reported through Slack.
> fix: Tag video-caption only as SC 1.2.2

- lib/core/utils/respondable.js
I noticed that the documentation for the `publish` method was inaccurate, referring to a non-existent `event` parameter. I reused the language found in the docs for the `createResponder` method a few lines above.
> docs: Correct function documentation

- lib/commons/aria/attributes.js
- lib/commons/aria/index.js
- test/checks/aria/valid-attr-value.js
This change allows empty aria-labelledby attributes in the valid-attr-value rule. 
Closes https://github.com/dequelabs/axe-core/issues/372
> fix(rule): allow empty aria-labelledby values

- lib/commons/dom/shadow-elements-from-point.js
> fix: Prevent color rules from crashing Chrome 66 #856

- package.json
This should hopefully get axe-core into the proper state before creating a new entry for sri-history. My best guess as to why sri-history was changing was because it had been updated without running `grunt build` first, so the source was actually different. This makes it an automatic build step instead of relying on the publisher to remember it.
> chore: add grunt build step to npm run release

- axe.d.ts
add missing resultTypes to RunOptions. Fixes TS compilation on some projects.
fixes #896
- Github issue: #896
Add missing resultTypes to RunOptions introduced in #568. Fixes TS compilation on some projects.
> chore(types): add resultTypes to typings

- lib/core/utils/escape-selector.js
- test/core/utils/escape-selector.js
> fix: Prevent axe-core crashing on “-“ as a class name

- .gitignore
- Gruntfile.js
- build/tasks/test-webdriver.js
- test/integration/full/frame-wait-time/frame-wait-time.html
- test/integration/full/frame-wait-time/frame-wait-time.js
- Tackled the issue of CircleCI kicking the bucket intermittently due to timeout error on script execution for mobile web-driver (chrome-mobile).
- Github issue: https://github.com/dequelabs/axe-core/issues/805
- Although this looked like grunt concurrency, or non-availability of gecko-driver, or docker base image issue, this was purely a configuration for web-driver.
- Also over-rid node ENV to not default to Http2, to avoid experimental warning on the terminal.
- Refer Circle CI for relevant commit to see logs (https://circleci.com/gh/dequelabs/axe-core/1164)
> fix: attempt to fix ci build failures.

- lib/checks/tables/td-has-header.js
- lib/commons/table/is-data-cell.js
- test/commons/table/is-data-cell.js
- test/integration/rules/td-has-header/td-has-header.html
- test/integration/rules/td-has-header/td-has-header.json
> fix: td-has-heading to ignore td with its role changed

- lib/checks/aria/required-children.js
- lib/checks/aria/required-children.json
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
> fix: Make empty role=lisbox elements as incomplete

- doc/rule-descriptions.md
- lib/rules/frame-title.json
> fix: Update tags for frame-title rule

- lib/core/public/run.js
This patch enables `axe.run()` to return a Promise when `window.Promise` is not defined, but there is a Promise implementation in the global scope.
This, while very edge-casey, enables me to run axe in a node process by only importing [`jsdom-global/register`](https://github.com/rstacruz/jsdom-global).
- Github issue:
> fix(axe.run): allow returning a Promise in jsdom

- lib/core/utils/element-matches.js
Closes https://github.com/dequelabs/axe-core/issues/953
- Github issue: https://github.com/dequelabs/axe-core/issues/953
I ran `grunt test` under Linux which fired up two instances of Chromium and one of Firefox. I’m guessing it also used PhantomJS. There was one failure reported, but it was present before these changes were applied:
```
>> URL: http://localhost:9876/test/commons/
>> Describe: color.getBackgroundColor
>> it should ignore inline ancestors of non-overlapping elements
>> AssertionError@http://localhost:9876/node_modules/chai/chai.js:9320:13                                                             
>> [3]</module.exports/Assertion.prototype.assert@http://localhost:9876/node_modules/chai/chai.js:239:13 …
```
> fix(utils/element-matches.js): Use `node.matches*` in place of `prototype.matches*`

- Gruntfile.js
When we updated grunt-contrib-uglify through Greenkeeper, it didn't throw an error on the deprecated `preserveComments` option. It needed to be updated to `output.comments` instead.
Closes https://github.com/dequelabs/axe-core/issues/950
> chore: restore comments in axe.js file

- lib/commons/text/accessible-text-virtual.js
- test/commons/text/accessible-text.js
I was poking around in the accessibleName method when I found/ noticed this little bug. It turns out that if you have an input element with an ID, Axe doesn't bother looking for an implicit label. That should obviously have been based on if there was actually an explicit label, not if the input has an ID.
> fix(accessible-name): Allow fallback labels when input has id

- axe.d.ts
- Github issue: https://github.com/dequelabs/axe-core/issues/972
> fix: typescript interface updates

- lib/core/utils/flattened-tree.js
- test/core/utils/flattened-tree.js
> fix: Don't crash with slot elements without shadowDOM

- doc/rule-descriptions.md
Regeneration of documentation of rule descriptions based tag changes in PR  https://github.com/dequelabs/axe-core/pull/988
Closes issue:
- None
> chore: Regenerate docs based on pr #988

- lib/checks/keyboard/page-has-main.json
- lib/checks/keyboard/page-no-duplicate-contentinfo.json
- lib/checks/keyboard/page-no-duplicate-main.json
- lib/checks/navigation/region.json
- lib/rules/landmark-banner-is-top-level.json
- lib/rules/landmark-contentinfo-is-top-level.json
- lib/rules/landmark-main-is-top-level.json
- lib/rules/landmark-no-duplicate-banner.json
- lib/rules/landmark-no-duplicate-contentinfo.json
- lib/rules/landmark-one-main.json
- lib/rules/region.json
Some of the help and description text entries for landmark rules didn't read very well, and weren't consistent with each other. Thanks very much to @iamrafan for the suggestions!
Closes https://github.com/dequelabs/axe-core/issues/983
> fix: consistent landmark rule/check descriptions

- lib/checks/navigation/region.js
- test/checks/navigation/region.js
Form elements with a title attribute are now counted as landmarks, whereas forms without a label or title are not. ARIA forms are counted as landmarks regardless of label or title.
Closes  #962 
> Region: allow forms with non-empty title, plain div[role=form]

- doc/examples/puppeteer/.eslintrc
- doc/examples/puppeteer/.npmrc
- doc/examples/puppeteer/README.md
- doc/examples/puppeteer/axe-puppeteer.js
- doc/examples/puppeteer/package.json
As requested, this patch adds an example of using `axe-core` with [Puppeteer](https://github.com/GoogleChrome/puppeteer). The example is very minimal and does not include all of `axe-webdriverjs`'s features.
Related to #1008.
> doc(examples): add simple Puppeteer example

- .eslintignore
- .gitignore
- .jsdoc.json
- doc/API.md
- doc/developer-guide.md
- lib/core/utils/get-selector.js
- package.json
- Exposing all the available methods with in `axe` seemed like a good idea to avoid other contributors re-writing/inventing the wheel all over again. For example, see comment - https://github.com/dequelabs/axe-core/pull/1022#discussion_r205972165
- Here in the `jsdoc` comments are embraced to generate the documentation under `./doc/api`.
- The generated files are ignored from source control.
- A npm task `api-docs` is facilitated to enable generating the documentation.
- Respective docs on contributing and developer notes has been updated with details on how to generate a full list of API reference.
- The generated documentation also allows exploring source code.
- Screenshots:
Closes issue:
- No issue reported.
> fix: generate jsdoc(umentation)

- circle.yml
This patch reduces the CircleCI build time by about ~2 minutes since do not have to `npm install` in most builds/scenarios.
> ci: Speed up builds by caching node_modules

- .eslintrc
- doc/examples/chrome-debugging-protocol/.eslintrc
- doc/examples/puppeteer/.eslintrc
- lib/core/base/audit.js
The patch updates our ESLint configs and instructs ESLint to enable ECMA v9 features (including the spread `...` operator).
Additionally, a random usage of `Object.assign()` has been replaced by the spread operator to ensure this is working as expected.
> build(eslint): enable usage of the "spread" operator

- doc/rule-descriptions.md
This patch updates the `rule-descriptions.md` document via `npx grunt build`. It appears the source files in which this document have changed but the generated content has not been comitted.
I've been "ignoring" this change in the many PRs I've opened recently and have finally grown tired of doing so.
> doc: update rule-descriptions

- test/testutils.js
Currently running the `axe-core` test suite in a browser that has either the axe or attest extension enabled will yield unpredictable and confusing results. This patch causes the test suite to throw an error instructing people to disable their extension(s) before running their tests.
I ran into this while working on a feature and wasted ~1 day trying to debug. :'(
Side note - I'm opening a seperate PR into the extensions repository which exposes the `__AXE_EXTENSION__` global.`
> test: throw a helpful error when running alongside the extension

- doc/examples/puppeteer/README.md
In linking to this demo from deque.com, I saw a typo that needed fixing.
> doc: fix typo in puppeteer README

- .github/CODEOWNERS
Adding Marcy and Dylan as code owners. Unlike most other axe / Attest repos, we wanted for this one to always have approval from a code owner on a PR to develop.
> chore: Update codeowners file

- lib/checks/aria/errormessage.js
- test/checks/aria/errormessage.js
The messages templates of the errormessage check expects data to be an array rather than a string. This fixes that issue. Instead of getting this:
> aria-errormessage values `m,y,-,i,d` must use a technique to announce the message (e.g., aria-live, aria-describedby, role=alert, etc.)
This fix returns:
> aria-errormessage value `my-id` must use a technique to announce the message (e.g., aria-live, aria-describedby, role=alert, etc.)
> fix(errormessage): check data is an array of IDs

- doc/projects.md
Added a project for Python projects maintained by Mozilla: https://github.com/mozilla-services/axe-selenium-python
> doc: add axe-selenium-python to projects

- test/integration/full/frame-wait-time/frame-wait-time.js
- The bug is not relevant anymore, and believe has been fixed as a consequence of changes done to allow webdriver to have a larger timeout.
-  Ran multiple test runs on circle, both locally and https://circleci.com/gh/dequelabs/axe-core/tree/bug-frame-wait-time. Test assertions for `frame-wait-time` are as expected.
Closes issue: https://github.com/dequelabs/axe-core/issues/929
> fix: frame wait time test case

- build/tasks/aria-supported.js
- lib/checks/aria/unsupportedrole.js
- lib/checks/aria/unsupportedrole.json
- lib/commons/aria/index.js
- lib/commons/aria/roles.js
- lib/rules/aria-roles.json
- test/checks/shared/unsupportedrole.js
- test/integration/rules/aria-roles/aria-roles.html
- test/integration/rules/aria-roles/aria-roles.json
Adds `unsupported` property to the `lookupTable.role` dictionary. New option for `aria.isValidRole` to `flagUnsupported` roles. Defaults to `false` since this commons function is reused for multiple checks.
Part one of https://github.com/dequelabs/axe-core/issues/918.
TODO: 
- Add `unsupported` to lookupTable.attributes
- Figure out what to do with globalAttributes, which are currently a flat array
- Add `axe.commons.support` API and enable control of it through `axe.configure`
> feat: flag unsupported roles

- lib/checks/mobile/meta-viewport-scale.js
- lib/checks/mobile/meta-viewport.json
- test/checks/mobile/meta-viewport-scale.js
A user reported the meta-viewport check had a confusing failure message, so I changed it to pass along the failing attribute:
"Fix the following: user-scalable="no" on <meta> tag disables zooming"
Closes https://github.com/dequelabs/axe-core/issues/1045
> fix(meta-viewport): show attribute in message

- circle.yml
- package.json
The `npx` package doesn't ship with the version of `npm` we're using (which is 3.x in node v6.12.3). Instead of relying on it, we execute the `standard-version` binary via `npm script` instead.
> ci: do not use `npx` binary

- doc/examples/jest_react/package.json
For some reason Greenkeeper had us bump a dependency to a non-existing version.
Closes #1090
> chore: Fix example dependency mistake

- circle.yml
The CI release script failed to run the build command.
Closes #1104 
> fix: Fix broken 3.1.0 release script

- Gruntfile.js
- This PR ensures, generation of banner comments on `axe.js` and `axe.min.js` files as a part of `grunt build` step.
- `grunt-contrib-uglify` > 2.x has some API changes which replaced `preserveComments` with `options.comments` which is now adapted here.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/1108
> fix: banner comment in generated axe files

- .circleci/config.yml
- .gitignore
- Gruntfile.js
- build/tasks/file-exists.js
- package.json
This PR introduces a new task which ensures, existence of a given set of files. In this case it checks, for `axe.***.js` files for all langs specified. If the build generated files do not exist, a fatal error is thrown. Also, the same files are checked for existence as a part of `prepublishOnly` step.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/1117
> chore: Ensure generated files exist

- lib/rules/html-lang-valid.json
- test/integration/full/html-lang-valid/frames/level1.html
- test/integration/full/html-lang-valid/frames/level2-b.html
- test/integration/full/html-lang-valid/frames/level2-c.html
- test/integration/full/html-lang-valid/html-lang-valid.html
- test/integration/full/html-lang-valid/html-lang-valid.js
This PR enhances `html-lang-valid` rule to allow `xml:lang` attribute.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/1140
> fix: html-lang-valid should consider xml:lang

- lib/rules/object-alt.json
- test/integration/rules/object-alt/object-alt.html
- test/integration/rules/object-alt/object-alt.json
This PR, allows role `presentation`/ `none` on `object`.
Closes issue: 
- https://github.com/dequelabs/axe-core/issues/1221
> fix: Allow role presentation and none on object-alt rule

- lib/checks/aria/required-children.js
- lib/checks/aria/valid-scrollable-semantics.js
- lib/checks/keyboard/landmark-is-top-level.js
- lib/checks/label/multiple-label.js
- lib/checks/navigation/heading-order.js
- lib/checks/navigation/region.js
- lib/checks/visibility/hidden-content.js
- lib/commons/dom/is-visual-content.js
This is a maintenance PR, to update `node.tagName` usages to `node.nodeName`.
Did not update the usages in:
- `lib/core/utils/css-parser.js` - as this is a copy/pasted (imported) module.
- `lib/core/utils/qsa.js` - as this seems to break a lot of tests.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/942
> fix: Avoid IE problems by using nodeName instead of tagName

- test/commons/dom/idrefs.js
- test/commons/dom/is-visible.js
- test/commons/text/visible-virtual.js
- test/core/utils/contains.js
- test/core/utils/get-root-node.js
- test/core/utils/is-hidden.js
This is a maintenance PR.
Adding logic to skip tests if no shadowDOM support, as against skipping assertion with in the test blocks.
> test: update to skip test if no shadowDOM support

- lib/commons/dom/is-visible.js
- test/commons/dom/is-visible.js
Whilst solving for a non-reproducible `region` rule bug (https://github.com/dequelabs/axe-core/issues/864), decided to enhance current `dom.isVisible` implementation to cater for `noscript` and `template` tags.
> fix: handle noscript and template in dom.isVisible

- .circleci/config.yml
Moving npm cache version management for CI builds as a Circle Environment Variable, to allow for easier cache busting.
Reasoning being, had a recent npm dependencies cache issue as a part of the eslint PRs - #1247 and #1250.
> chore: easy cache bust of npm modules in CI

- axe.d.ts
We don't always set both. For example, see [axe-webdriverjs](https://github.com/dequelabs/axe-webdriverjs/blob/v2.0.1/lib/axe-injector.js#L28).
> fix(typedefs): do not require brand and application

- doc/API.md
- lib/core/utils/preload.js
- test/core/base/audit.js
- test/core/utils/preload-cssom.js
- test/core/utils/preload.js
- test/integration/full/css-orientation-lock/incomplete.js
- test/integration/full/css-orientation-lock/passes.js
- test/integration/full/css-orientation-lock/violations.js
This PR does the below:
- Set's `preload: true` by default.
- Updates `preload` related tests.
- Updates `preload` API documentation.
- This allows for `experimental` rules like `css-orientation-lock`, to be run with out passing an extra flag from products like extensions.
Closes issue:
> fix: set preload:true as default

- lib/core/base/audit.js
- test/core/base/audit.js
See title for description.
Closes issue: WWD-1913
> fix: Log instead of error on unknown tag

- locales/ja.json
Attribute name is changed to back to English (it was supposed to remain in English).
> fix(i18n): Fix Japanese translation

- build/shared/format.js
- build/tasks/aria-supported.js
- build/tasks/configure.js
This patch runs Prettier over the generated `aria-supported.md` and `rule-descriptions.md` files. This ensures `npm run build` does not create any unstaged changes.
Closes #1310.
> chore: format generated documentation before writing to disk

- lib/commons/color/get-background-color.js
This patch adds a safeguard to `color.filteredRectStack` which prevents a `TypeError: Cannot read property '0' of undefined` from being thrown.
This is not a perfect solution, but a stop-gap instead. It's still unclear why we're getting `undefined` here. More investigation is needed, but this can happen at a later date.
Closes #1306 and #1259.
> fix: prevent TypeErrors in color-contrast checks

- lib/checks/forms/autocomplete-appropriate.js
- lib/commons/utils/valid-input-type.js
- test/checks/forms/autocomplete-appropriate.js
- test/integration/rules/autocomplete-valid/autocomplete-valid.html
- test/integration/rules/autocomplete-valid/autocomplete-valid.json
`Firefox` returns `node.type` as `text` for certain scenarios like - `<input autocomplete="bday-month" type="month">`, hence using `getAttribute` to resolve the value of `type` solves for this edge case.
Due to this, the number of violations returned across different browsers were different as described in the bug below.
Closes issue:
- https://dequesrc.atlassian.net/browse/WWD-1957
> fix: autocomplete-appropriate node type resolution

- Gruntfile.js
Small bug fix. no-lint needs to run `run:npm_run_imports`.
> chore: Fix grunt dev:no-lint

- .github/CODEOWNERS
Allow different code owners for various paths of the code with a global fallback.
> chore: update code owners with fallback to global owners

- Gruntfile.js
- lib/checks/forms/group-labelledby-after.js
- lib/checks/forms/group-labelledby.js
- lib/checks/forms/group-labelledby.json
- test/checks/forms/group-labelledby.js
- test/integration/rules/checkboxgroup/checkboxgroup.html
- test/integration/rules/checkboxgroup/checkboxgroup.json
- test/integration/rules/radiogroup/radiogroup.html
- test/integration/rules/radiogroup/radiogroup.json
Update the group-labelledby check to enforce that in addition to having a shared label, radiobuttons and checkboxes with the same name also have a unique label. This impacts the checkboxgroup and radiogroup rules.
I merged in a fix from #1314, which changes the gruntfile. We should probably more that PR first.
Closes #1111
> feat(rule): Require unique aria labels in checkboxgroup & radiogroup

- Gruntfile.js
- package.json
This patch removes all of the ESLint stuff from the Grunt configuration. There have been numerous efforts to "fix" the existing Grunt/ESLint setup which all seem unnecessary. Now, if you want to lint your code, just do `npm run eslint`. If you don't want to lint your code, then don't do `npm run eslint`.
Ref: #1342, #1314, #1267, #1255, #1247, and probably others...
> chore: remove "linting" from Grunt

- package.json
Two difference prs were merged that both tried to clean up the duplicate grunt dependency that was in the package.json. Resulted in it being removed completely. 
Closes issue:
> fix: add grunt back to dependencies

- lib/core/imports/index.js
- package.json
- test/integration/full/umd/umd-window.js
- Requiring `es6-promise` to `window`.
- Verified in Windows 10 Machine, IE11 browser, for existence of `window.Promise`
- Added tests to verify `Promise` usage.
> chore: add es6 promise

- build/templates.js
- lib/core/base/rule.js
- test/core/base/rule.js
Passing the `context` object to the `matches` function for rules, to  allow for pre-filtering of nodes based on context.
Closes issue: https://github.com/dequelabs/axe-core/issues/1359
> feat: pass context to rule matches

- lib/commons/aria/arialabelledby-text.js
- test/commons/text/accessible-text.js
Following up on a few comments in #1163
> chore: Resolve a few a11y-name comments

- package.json
Removing a dependency, that @WilcoFiers added 2+ years ago, in an attempt to use Promise.
> chore: remove redundant promise dependency

- package.json
**Note: looking for opinion**
Following this PR - https://github.com/dequelabs/axe-core/pull/1343, `npm run eslint` does not run locally at all, which leads to some basic lint errors getting into CI & then the developer having an Aha moment. 
It should not be developer overhead to remember to run `eslint` before pushing. Hence adding this step to `lint-staged` which should catch lint errors (albeit not only on staged files). 
Verified that it works, locally.
> chore: add eslint to lint staged

- .github/CODEOWNERS
I added Stephen to the codeowners instead. Adding two code owners doesn't really work as I was hoping it might. Stephen will have to just be mindful not to approve PRs that involve rule changes.
> chore: Simplify codeowner stuff

- .eslintignore
ESLint has no business running on axe(.min).js.
> chore(eslint): Ignore built files

- build/imports-generator.js
- package.json
- test/integration/full/umd/umd-module-exports.js
Use derequire the rename all uses of `require` to `_dereq_` to avoid the problem of Cypress overloading the `require` method.
Closes #1405
> fix: Avoid require conflict with Cypress [#1405]

- .circleci/config.yml
This patch prevents our `test` CircleCI job from running until both `lint` and `dependencies` have passed. This ensures we "fail fast", which should (in theory) free up _some_ time with our limited container count.
> ci: do not run the tests unless "lint" passes

- lib/core/reporters/helpers/get-environment-data.js
- test/core/reporters/helpers/get-environment-data.js
`helpers.getEnvironmentData` made the assumption that `window` is the name of the global object. This is not the case when running axe-core in a NodeJS environment such as when testing axe-core using JSDOM. Usually all props on window get copied over to the global to avoid this, but especially for something as uncommon as `screen` it is not surprising that this broke somewhere.
Closes #1404
> fix: Avoid "screen is not defined" error [#1404]

- test/checks/mobile/css-orientation-lock.js
fix breaking test in IE.
Reference - https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument
> test: createHTMLDocument needs mandatory title when invoked in IE

- .circleci/config.yml
This patch adds CircleCI configuration for automatically creating a GitHub Release (tag) after we successfully deploy a production version to npm.
Closes issue:
> ci: create GitHub release after publishing to npm [WWD-1845]

- Gruntfile.js
- appveyor.yml
- build/tasks/test-webdriver.js
- lib/core/utils/preload-cssom.js
- test/checks/lists/only-dlitems.js
- test/checks/lists/only-listitems.js
- test/checks/mobile/css-orientation-lock.js
- test/commons/text/form-control-value.js
- test/core/utils/is-html-element.js
- test/integration/full/css-orientation-lock/violations.js
- test/integration/full/landmark-banner-is-top-level/landmark-banner-is-top-level-pass.js
- test/integration/full/landmark-contentinfo-is-top-level/landmark-contentinfo-is-top-level-pass.js
- test/integration/full/preload-cssom/preload-cssom.js
- test/integration/full/preload/preload.js
- test/rule-matches/autocomplete-matches.js
- test/testutils.js
Tests should be running end-to-end on appveyor, with a few exceptions:
* PhantomJS is timing out on some integration tests. It's likely we are doing something to break PhantomJS on Windows, but unfortunately Phantom is not providing any useful logs beyond timing out.
* A number of integration tests with webdriver are failing in IE11. ([see branch with failing tests](https://ci.appveyor.com/project/scurker/axe-core/builds/23236242))
* Tests that are failing only in IE are skipped
Related #1384 
Closes #519 
> ci: Run axe-core tests on appveyor

- lib/core/imports/index.js
`es6-promises` doesn't check if `window.Promise` exists before overriding it, but instead [checks if the browser natively supports Promises](https://github.com/taylorhakes/promise-polyfill/blob/master/src/polyfill.js) by seeing if `Promise.resolve()` returns `'[object Promise]'` when passed to `toString`:
```js
let P = local.Promise;
if (P) {
var promiseToString = null;
try {
promiseToString = Object.prototype.toString.call(P.resolve());
} catch(e) {
// silently ignored
}
if (promiseToString === '[object Promise]' && !P.cast){
return;
}
}
local.Promise = Promise;
```
Adding a check before we run the polyfill to see if `window.Promise` exists. 
I looked at changing to anther promise library that would do the check better, but I'm not sure if @jkodu chose `es6-promsie` for a specific reason …
> fix: only load Promise polyfill if window.Promise is missing

- build/test/config.js
- test/core/public/run-rules.js
- test/core/public/run.js
Some tests are occasionally failing on AppVeyor, so skipping a specific CSSOM test in Chrome, and allowing for retries on some of the IE tests.
> ci: allow retries in IE; skip flaky test for windows ci

- axe.d.ts
Update `axe.d.ts` to match `API.md` in terms of which result `impact` properties may sometimes be `null`
Closes issue: #1476
> fix: make nullable impact properties have nullable types per API docs

- .circleci/config.yml
This patch removes the CircleCI "hold" for canary releases. As result, all (green) `develop` commits will be published to npm as `axe-core@next`.
> ci: remove hold for "next" releases

- appveyor.yml
Some tests were flaking out, so just run `build` and `test:examples` on appveyor.
> ci: only run build and test:examples on appveyor

- doc/API.md
- lib/core/base/rule.js
- lib/core/utils/performance-timer.js
Add metrics for `rule.gather`, `rule.matches` and `axe.utils.isHidden`. This allows us to see where a rule is taking the most time better. Also rename rules to be sortable based on id. Lastly, have axe only output metrics that were done after axe run, otherwise you get metrics that the website ran before axe did, which makes it really confusing when reading the metric logs.
Example output:
```
Measure rule_aria-valid-attr-value#gather_axe.utils.isHidden took 931ms
Measure rule_aria-valid-attr-value#gather took 931ms
Measure rule_aria-valid-attr-value took 937ms
Measure rule_aria-valid-attr-value#matches took 4ms
Measure rule_aria-valid-attr-value#runchecks took 2ms
Measure rule_aria-valid-attr#gather_axe.utils.isHidden took 960ms
Measure rule_aria-valid-attr#gather took 960ms
Measure …
```
> feat(rule): add more perf timing metrics to rules

- axe.d.ts
This patch removes the version number from `axe.d.ts`. I think the original idea behind keeping it here was to update it every time we release, but this hasn't been happening lately.
Removing the version does not have any effect on TypeScript users; instead, it just removes an easy to break/forget part of our internal processes 😃
> chore: remove version number from axe.d.ts

- lib/checks/aria/valid-attr-value.js
- test/checks/aria/valid-attr-value.js
> fix(aria-valid-attr-value): allow aria-controls to pass when element is not in the DOM

- lib/core/utils/scroll-state.js
- test/core/utils/scroll-state.js
The arguments for `window.scroll()` are [x-axis, y-axis](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll); meaning that "top" value (vertical scrolling) was supposed to be passed as 2nd argument.
> fix: Scroll state had top and left properties flipped

- lib/core/reporters/raw.js
- test/core/reporters/raw.js
- test/playground.html
This patch updates our "raw" reporter, ensuring it does not pass `DqElement`s to its callback. Instead, it serializes the `DqElement` by using the `DqElement#toJSON()` method.
Unfortunately many of our tests pass non-results to the reporters, so several "guards" were added to the reporter ensuring we don't error while attempting to transform the provided results. In an ideal world, these tests would be rewritten to pass "proper" result objects to our reporters, but this felt out-of-scope for the task at hand.
Closes https://github.com/dequelabs/axe-core/issues/1195
> fix(raw-reporter): do not output `DqElement`s

- .prettierignore
`doc/api` is ignored by git but not by prettier. Prettier breaks on quite a few of them if you've run `npm run api-docs` before running prettier.
> chore(prettier): ignore generated api doc files

- package.json
Greenkeeper keeps flagging issues that aren't actual issues due to appveyor breaking the build.
Closes issue: #1523 
> chore: update Babel dependencies

- lib/commons/dom/is-skip-link.js
On https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#PrescriptionRefill takes the time to run the skip-link rule from 33s to 38ms.
> fix(dom.isSkipLink): cache first page link

- lib/checks/aria/valid-attr-value.js
- test/checks/aria/valid-attr-value.js
Allow `aria-owns` to pass `aria-valid-attr-value` when element has `aria-expanded=false` and the owned element is not in the DOM.
Linked issue: #1524 
> fix(aria-valid-attr-value): allow aria-owns to pass when element is not in the DOM

- doc/examples/jsdom/package.json
- doc/examples/jsdom/test/a11y.js
There were a lot more things needed for the global object than I thought there would be.
Axe needed:
* `document`
* `window`
* `Node`
* `NodeList`
* `Element`
* `Document`
and Axios needed:
* `navigator`
Linked issue: #1473
> docs: add jsdom example and tests

- package.json
Our `npm run retire` script is failing CricleCI because Handlebars 4.0.0 has a high severity issue.
```
handlebars 4.1.0 has known vulnerabilities: severity: high; summary: A prototype pollution 
vulnerability in handlebars may lead to remote code execution if an attacker can control 
the template; 
https://snyk.io/vuln/SNYK-JS-HANDLEBARS-174183 
https://github.com/wycats/handlebars.js/issues/1495 
https://github.com/wycats/handlebars.js/commit/cd38583216dce3252831916323202749431c773e
```
`standard-version` brings in Handlebars and the latest version fixes the issue.
> chore: update standard-version dep

- lib/core/utils/flattened-tree.js
During a pairing session, noticed a bug with checking if a property already exists in the `_vNodeCache` of `flattenedTree`.
Previously because of this line https://github.com/dequelabs/axe-core/pull/1536/files#diff-a4aba2b3f5c65ff940eb4c8060dc57dfL37, if `isFocusable` is false, the utility function will be called. We should check if a cached value exists, rather than check against `true` or `false`, given that the values of some of these cached functions are boolean.
Closes issue: NA.
> fix: check if property exists in cache of flattenedTree

- lib/commons/aria/index.js
- test/checks/aria/required-attr.js
- test/integration/full/configure-options/configure-options.js
> fix(aria-required-attr): don't require aria-valuemin/max

- locales/ja.json
I've translated the new rule for avoid-inline-spacing.
> chore(i18n): Update Japanese locale

- lib/core/reporters/raw-env.js
- test/core/reporters/raw-env.js
`rawEnv` reporter calls the callback with `{raw, env}` where `raw` is the output of the `raw` reporter and `env` is the output of `helpers.getEnvironmentData()`.
Closes issue: #1534
> feat(reporter): adds the rawEnv reporter which wraps raw and env data

- appveyor.yml
* Run test scaffolding commands isolated
* Split up test commands between phantom/webdriver to allow for quicker runs if something flakes out
* Only run `webdriver:ie` tests
I did a bit of testing around this. Ran 40+ iterations on CI after the change and there was only a single failure due to flaky tests being unable to run after 3 attempts (the other failures were due to random appveyor issues). This change could potentially make tests run longer (up to ~30 minutes), but will provide greater confidence levels that there aren't breaking windows changes.
It _does not_ resolve any of the underlying issues that may be contributing to potential flakiness on Windows.
> ci: run test tasks with appveyor-retry to allow flaky tests to re-run

- lib/checks/aria/required-children.js
- lib/checks/aria/required-children.json
- lib/commons/aria/index.js
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
* Added additional elements per https://github.com/dequelabs/axe-core/issues/1444#issuecomment-488253893
* Added check for element to fall under _Needs Review_ only when an element is empty or has no owned nodes.
* Added missing roles to aria lookup table where owner relationship was missing per [D.Pub Aria 1.0](https://www.w3.org/TR/dpub-aria-1.0/) and [Aria 1.1](https://www.w3.org/TR/wai-aria-1.1/).
Closes issue: #1444 
Closes issue: #383
> feat(rule): add additional elements to check for incomplete with required children

- test/.eslintrc
- test/checks/lists/dlitem.js
- test/checks/mobile/css-orientation-lock.js
- test/commons/aria/arialabel-text.js
- test/commons/aria/is-aria-role-allowed-on-element.js
- test/commons/matches/from-definition.js
- test/commons/matches/node-name.js
- test/core/base/audit.js
- test/core/reporters/raw-env.js
- test/core/utils/get-stylesheet-factory.js
- test/core/utils/parse-crossorigin-stylesheet.js
- test/core/utils/parse-sameorigin-stylesheet.js
- test/core/utils/preload-cssom.js
- test/integration/full/preload-cssom/preload-cssom.js
- test/integration/full/preload/preload.js
- test/integration/full/umd/umd-window.js
- test/integration/rules/runner.tmpl
- test/runner.tmpl
Noticed a lot of IE11/ Appveyor tests were failing as a consequence of looked over es6 syntax which is used in `tests/*.js`.
This PR, changes `eslintrc` for `tests` directory to disable `es6` syntax & fixes all such usages.
> test: disable es6 syntax usage within tests directory

- appveyor.yml
Our appveyor account only has a queue of 1, so we can only do one job at a time. With the full suite taking 10ish minutes to complete and allowing 3 times for failures, we're getting backed up having to run appveyor for each commit against both the branch and develop. 
Since we're already running the mocha tests in CircleCI, we can just focus on running the IE tests in appveyor to cover our missing test browser while speeding up the appveyor tests.
> test: only run IE11 tests in appveyor

- test/core/reporters/raw-env.js
The raw env reporter compares two datetime strings together in an equality test. If the datetimes were off by 1 ms the test would fail. Just copied the test for environment data from the v1 reporter.
> test: fix flakey test

- lib/checks/label/multiple-label.js
- test/checks/label/multiple-label.js
When authors use `aria-labelledby` on a labeled input, multiple labels will be consumed by AT. In cases where less than all labels are included, the excluded label must have `aria-hidden="true"`.
issue: #689 (don't autoclose, docs needed)
> fix(multiple-label): no longer raises issue when aria-labelledby overrides how AT views multiple labels

- lib/core/utils/flattened-tree.js
The `<content>` tag is deprecated and the `getDistributedNodes()` method on it's element is also deprecated. We used to unconditionally call it, but the method was removed in Firefox, and could potentially be removed from an upcoming version of Chrome.
A `<content>` tag was replaced by `<slot>` in shadow DOM v1 and behaves like a `<div>` now. So it is safe to treat it like any other node.
Closes issue: https://github.com/dequelabs/axe-core/issues/1576
> fix(flatten-tree): do not call deprecated getDistributedNodes

- lib/checks/label/multiple-label.js
- test/checks/label/multiple-label.js
If the node is not contained in the ownerDocument it must be in shadow (open). Therefore, we climb the parentNode path to the first document fragment. Closed shadow is not supported. This fixes an issue where a single shadow tree held an input and valid label(s). Crossing shadow tree/document boundaries can not produce an accessible name.
Closes issue: #1559
> fix(multiple-label): considers explicit labels in the same shadow tree

- build/tasks/test-webdriver.js
- lib/commons/color/get-background-color.js
- test/commons/color/get-background-color.js
- test/commons/dom/visually-overlaps.js
- test/runner.tmpl
[`sortPageBackground`](https://github.com/dequelabs/axe-core/blob/c7803bfa3fca037ec9cb168853a8c009b3fab602/lib/commons/color/get-background-color.js#L207) did not account for instances where an element did not visually intersect with `document.body` but should inherit the background color from the canvas background (`<html>`).
According to the [CSS3 Background Spec](https://www.w3.org/TR/css-backgrounds-3/#special-backgrounds), the document canvas should propagate the background color of the `<body>` element when all of the following are true:
* The `<html>` element has `background-image: none`
* The `<html>` element has `background-color: transparent`
The following [CodePen](https://codepen.io/iamrafan/pen/WmLJmw) provides a case where axe shows a false positive due to the above missing …
> fix: Include body as part of background color checks when element does not intersect

- README.md
This patch adds a CircleCI status badge to our README. This enables users to see how stable the `develop` branch is and allows us to quickly navigate to the `axe-core` landing page in CircleCI (which is something I do frequently).
> docs: Add CircleCI status badge

- Gruntfile.js
Making changes to integration html and json files did not retrigger the `npm start` build, so you would have to manually quit and restart the process to see changes. The `test/integration/index.html` file is a generated file so we exclude that file from the watch.
> test: watch integration html and json files

- lib/core/utils/get-scroll.js
- test/core/utils/get-scroll.js
- test/core/utils/scroll-state.js
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.html
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.json
- test/rule-matches/scrollable-region-focusable-matches.js
An element with `overflow: hidden` is not scrollable except through JavaScript `elm.scrollTop`. This prevents common CSS techniques to hide elements from visual users from failing the rule.
e.g.
```css
.sr-only {
border: 0; 
clip: rect(0 0 0 0); 
height: 1px; 
margin: -1px;
overflow: hidden;
padding: 0;
position: absolute;
width: 1px;
}
```
Linked issue: #1582
> fix(scrollable-region-focusable): exclude overflow:hidden as not scrollable

- lib/core/base/virtual-node.js
- test/core/base/virtual-node.js
SVG elements return a `SVGAnimatedString` object and not a string when accessing `node.className`.
Linked issue: #1423
> fix(virtual-node): fix hasClass to work with svg elements

- build/templates.js
Noticed that the `gather` function in `Rule`, takes 2 arguments (See - https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/rule.js#L386), but the build template for any override provided in the rule spec, passes the wrong number of arguments.
> fix: arguments for gather function in build template

- lib/checks/forms/autocomplete-appropriate.js
- lib/core/base/virtual-node.js
- lib/core/utils/qsa.js
- lib/rules/autocomplete-matches.js
- test/core/base/virtual-node.js
- test/rule-matches/autocomplete-matches.js
Autocomplete-matches uses the JavaScript DOM property `.type` to look at the type of input. This is trivial when you have a DOM node, but becomes a bit more complicated when you don't (e.g. AST implementations). Created a method on the `VirtualNode` that just returns the DOM property lookup but is expected to be overridden for other implementations.
It also tries to determine if the node is visible in the DOM, but that doesn't work for virtual node only runs, so I made it conditional on there being an `actualNode` to look at.
Please double check the tests that I added all the same properties when converting to `queryFixture`.
> feat(autocomplete-matches): use virtualNode only lookups

- lib/commons/dom/find-up.js
- lib/core/utils/element-matches.js
- test/core/utils/element-matches.js
When passing no context to `axe.run`, the `<html>` element would try to find-up and get the `document` node as the parent, which doesn't have any matches function and so would error in `element-matches.js` when calling `node[method](selector)`.
Linked issue: #1585
> fix(matches-selector): don't call matches function if none exist on the element

- doc/API.md
> docs: add list of required globals

- doc/API.md
> docs: add all reporters to axe.configure parameters

- lib/core/reporters/na.js
- test/core/log.js
By request of Wilco. The na reporter is the exact same code as the v2 reporter.
> fix: deprecate na reporter

- lib/checks/tables/th-has-data-cells.js
Removes most `reduces` for either `.forEach` iteration or `.some` for better readability of the code. Also updates to ES6 syntax. 
Thanks to @AdnoC for the help.
> refactor: make th-has-data-cells check more readable

- axe.d.ts
When enabling the xpath option of `axe.run`, the `NodeResult` has an `xpath` string array. Added the property to the `NodeType` interface.
```js
axe.run({ xpath: true });
// sample violation result
{
"any": [
{
"id": "aria-allowed-role",
"data": [
"tablist"
],
"relatedNodes": [],
"impact": "minor",
"message": "ARIA role tablist  is not allowed for given element"
}
],
"all": [],
"none": [],
"impact": "minor",
"html": "<nav class=\"tabnav-tabs \" role=\"tablist\">",
"target": [
".comment-form-head.tabnav.flex-justify-between > .tabnav-tabs[role=\"tablist\"]"
],
"xpath": [
"/div[@id='discussion_bucket']/div[2]/div[2]/div[3]/form/div/div/div/nav"
],
"failureSummary": "Fix any of the following:\n  ARIA role tablist  is not allowed for given element"
}
```
Closes issue: #1636
**Required fields, …
> fix(axe.d.ts): add optional xpath property to NodeResult

- lib/checks/color/color-contrast.js
Add the size in px to the color contrast error message to avoid confusion with the pt unit.
```
"Fix any of the following:
Element has insufficient color contrast of 3.87 (foreground color: #3d7e9a, background color: #eeeeee, font size: 12.0pt / 16px, font weight: normal). Expected contrast ratio of 4.5:1"
```
Linked issue: #1628
> feat(color-contrast): add px unit to error messages

- test/rule-matches/duplicate-id-active-matches.js
- test/rule-matches/duplicate-id-aria-matches.js
- test/rule-matches/duplicate-id-misc-matches.js
When debugging, noticed that some test suite names were not correct & also filename seemed to be a copy pasted (eg: filename.2.js). 
This PR fixes these nitpicks.
Closes issue:
- NA
> refactor: fix test suite titles

- lib/commons/color/get-background-color.js
- test/commons/color/get-background-color.js
…overlapping elm
Prevents calculating color contrast ratio that have an overlapping element
Closes issue: #1459 
> fix(get-background-color): No longer calculate color from non-opaque overlapping element

- doc/API.md
The `resultType` description in the docs has caused a bit of confusion for users (see #1126, #1183, and #1540). Based on the current read of the docs, it sounds like users expect the option to filter out result types not listed. So if the option was `resultTypes: ['violations']`, the user expected only violation results to be listed. 
Instead what the option really does is limit the number of related nodes to a maximum of one for each result type not listed. Updated the docs to clarify this point. 
Closes #1126
Closes #1183
> docs: clarify resultType option

- lib/commons/color/get-background-color.js
- test/commons/color/get-background-color.js
All browsers consistently allowed styling `<thead>`, `<tbody>`, and `<tfoot>` elements. Added them to the `getBackroundColor` function that includes missing elements from `document.elementsFromPoint` API.
https://codepen.io/straker/pen/ewRzKr
Linked issue: #823
> fix(get-background-color): process tbody, thead, and tfoot when getting background color

- build/rule-generator.js
- doc/examples/test-examples.js
- package.json
[Execa v2.0.0 removed the `.shell` command](https://github.com/sindresorhus/execa/releases/tag/v2.0.0) and instead uses the [`shell` option](https://github.com/sindresorhus/execa#shell) to execute the command in a shell.
> chore: Update execa to latest version

- lib/checks/aria/valid-attr-value.js
- lib/checks/aria/valid-attr-value.json
- test/checks/aria/valid-attr-value.js
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
> fix(valid-attr-value): Return incomplete when aria-describedby reference a missing element

- doc/examples/phantomjs/axe-phantom.js
This patch updates the `phantomjs` example test, making it not fail if an axe-core violation is found on deque.com.
While it's extremely embarrassing that deque.com has violations, it's not something we control, so we shouldn't block merges based on it.
> test(examples): do not fail tests if deque.com has violations

- .circleci/config.yml
- package.json
- test/test-locales.js
> test: ensure locale files are valid

- axe.d.ts
Added new properties to RunOptions interface that are specified in documentation: https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#options-parameter
Closes #1696 
> fix(types): add new properties to RunOptions

- .circleci/config.yml
- package.json
- test/test-rule-help-version.js
This should block a release pr (a pr into `master` branch only) if the newest axe version rule help docs are not active.
> test: require new release rule help docs to be active before creating release

- lib/checks/label/duplicate-img-label.js
- test/checks/label/duplicate-img-label.js
> fix(image-redundant-alt): check for parent before calculating text

- .eslintignore
- lib/core/utils/escape-selector.js
- package.json
eslint 6.0.0 seems to have removed the `W041` rule. Also our `.eslintignore` was not properly ignoring all `node_modules` files and would try to load the eslint config from the `doc/examples/jasmine/node_modules/extend/.eslintrc` which tried to extend a dev dependency of that module, which would fail.
> chore: update eslint version to 6.1.0

- doc/examples/test-examples.js
This will better let us see which example dir is failing the test as the tests now run in sync. To try to speed up the test though the `npm install` command is run async for each dir.
> test: run example tests in sync

- doc/examples/chrome-debugging-protocol/package.json
- doc/examples/jasmine/package.json
- doc/examples/jest_react/.babelrc
- doc/examples/jest_react/package.json
- doc/examples/jsdom/package.json
- doc/examples/mocha/package.json
- doc/examples/phantomjs/package.json
- doc/examples/puppeteer/package.json
- doc/examples/qunit/package.json
Just running `npm update` and `npm audit fix` in all our example dirs. Had to update our react example to use babel 7 and the [new presets](https://github.com/babel/babel/issues/8707) as well.
> chore: update example dependencies

- doc/API.md
Replacement for #1710 / #1718
All the credit goes to @arturoromeroslc for spotting this issue and submitting #1703. His fix didn't work, but he couldn't have known that. This should do it though.
> docs(api): Include call methods in code snippets

- test/integration/rules/runner.js
When [trying to deprecate](https://github.com/dequelabs/axe-core/issues/1733) the `fieldset` and `group-labelledby` checks by disabling them using `enabled: false`, the deprecated rules using these checks would fail their integration tests since the check was no longer running for the rule. This change allows us to disable checks completely only if either all rules that use the check have been deprecated or if the check is removed from all the rules metadata.
> test: don't run integration tests for deprecated rules

- lib/checks/aria/valid-attr-value.json
Missed an opening `{` which caused the message to [not be doTified correctly](https://github.com/dequelabs/axe-core/issues/1151#issuecomment-516725923).
Linked issue: #1151 
> fix(aria-valid-attr-value): fix incomplete translation message

- test/integration/full/strict-csp/strict-csp.html
- test/integration/full/strict-csp/strict-csp.js
Integration test showing that axe can parse and run under a strict csp. If you want to see that this works, you can open the `strict-csp.html` file and change the source of axe to [3.3.0](https://unpkg.com/axe-core@3.3.0/axe.js), then `npm run start` and navigate to the test to see it fail.
> test: add test showing axe runs under strict csp

- lib/rules/aria-form-field-name-matches.js
- test/rule-matches/aria-form-field-name-matches.js
The combobox pattern following ARIA 1.1 uses a native textbox child element for the accessible name. Don't need to check the parent `role=combobox` for the accessible name.
Closes issue: #1711
> fix(aria-form-field-name-matches): don't test combobox elements when they have a child input

- doc/projects.md
`docs/projects.md` currently links to https://github.com/javnov/axe-selenium-csharp, which publishes the [Globant.Selenium.Axe NuGet package](https://www.nuget.org/packages/Globant.Selenium.Axe/). Unfortunately, this package hasn't been updated in 2 years; it is currently broken in Chrome 76, and we weren't able to contact the maintainer about contributing updates to it.
https://github.com/TroyWalshProf/SeleniumAxeDotnet is a more recent fork of that codebase that is actively maintained and published under the [Selenium.Axe NuGet package](https://www.nuget.org/packages/Selenium.Axe/). This fork is the one we're planning to start recommending in [microsoft/axe-pipelines-samples](https://github.com/microsoft/axe-pipelines-samples).
This PR updates the link to point to the maintained fork …
> chore: update projects.md link to .NET integration library

- lib/checks/forms/fieldset.json
- lib/checks/forms/group-labelledby.json
Deprecating checks used only in the newly deprecated `radiogroup` and `checkboxgroup` rules. The `deprecated` property doesn't really do anything in the code, but I figured it would be nice to have so we can search for the term and get hits on rules and checks.
Closes issue: #1733
> feat(fieldset, group-labelledby): deprecate fieldset and group-labelledby checks

- lib/rules/color-contrast-matches.js
- test/rule-matches/color-contrast-matches.js
We check if the node or its parent is `aria-disabled`, but not the element an explicit label pointed to. Went ahead and updated the code to use es6.
Closes issue: #1731
> fix(color-contrast-matches): don't check aria-disabled explicit label element

- doc/backwards-compatibility-doc.md
Document that APIs will stay deprecated for at least 6 months before they are removed. Deprecated APIs are only removed during a major release.
> docs: APIs stay deprecated at least 6 months before removal

- lib/checks/aria/required-children.js
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
Allow `reviewEmpty` roles to have empty children so long as the child does not have a role.
Closes issue: #1762
> fix(aria-required-children): allow reviewEmpty nodes to have empty children

- package.json
Not sure why this says it's failing. Seems to work locally. Testing here.
*Edit*: Seems appveyor timed out the first time for an unknown reason and never finished running the tests.
Closes: #1797
Closes: #1771
> chore(package): update eslint-config-prettier to version 6.2.0

- lib/core/base/audit.js
- test/core/base/audit.js
- test/core/public/configure.js
> feat(audit): add lang query paramenter to help urls

- README.md
Also to note that we now test in IE11 with every pr.
> docs: update readme to deprecate support for v0 Shadow DOM

- lib/core/utils/get-selector.js
- test/core/utils/get-selector.js
There was a bug where after running color-contrast, the page would be scrolled to the bottom and a fragment element would then be removed from the DOM (due to an `onscroll` event). If the fragment element was the target of a rule, axe would throw an error say since `doc.host` would return `undefined`.
Closes issue: #1589
> fix(get-selector): don't throw error for disconnected fragment

- doc/backwards-compatibility-doc.md
Merging from `develop` into a branch where I was authoring rules, crept in a formatting change, see - https://github.com/dequelabs/axe-core/pull/1649/files#diff-a0a8316da4851cf2b614c43ecd9834c2.
> chore: run prettier formatting

- lib/core/utils/scroll-state.js
- test/core/utils/scroll-state.js
For any page in IE that has an SVG element, accessing `.children` on an SVGElement when getting the scroll state would return `undefined` and ends up throwing an exception. Other browsers treat SVGs as HTMLCollections but IE treats them as SVGElement.
Closes issue: #525
> fix(utils): Fix error in IE when getting scroll state on page with SVG elements

- doc/API.md
Fixed inconsistency of `preload` default value in docs API.
Closes issue: #1817
> docs: update preload default value

- lib/core/base/audit.js
- locales/nl.json
- test/core/public/configure.js
Use the failure summaries from the passed in locale.
Discovered a bug in the translation file generator (#1810) and had to make `nl.json` match the incorrect structure so we don't try to do too much in this PR. Will fix the structure and bug in another PR.
Closes issue: #1750
> fix(configure): use translations for failure summaries

- lib/core/utils/scroll-state.js
As suggested by @stephenmathieson on #1820,  adding a code comment in scroll-state for why childNodes is needed for SVGs in IE.
Closes issue: #525 
> docs(utils): add code comment in scroll-state for why childNodes is needed for SVGs in IE

- lib/commons/aria/index.js
- test/integration/rules/aria-allowed-attr/passes.html
[`aria-readonly` is an allowed attribute](https://www.w3.org/TR/wai-aria-1.1/#listbox) on `listbox`
Closes issue: #1821 
> fix(aria-allowed-attr): allow 'aria-readonly' on listbox

- lib/commons/text/unicode.js
- test/checks/label/label-content-name-mismatch.js
- test/commons/text/unicode.js
Part 1 for #1635 to fix using private use unicode characters. 
> fix(label-content-name-mismatch): ignore private space unicode

- build/test/config.js
- test/integration/api/external/index.html
- test/integration/api/external/index.js
This adds tests that will help prevent breaking changes in axe-core that axe Pro depends on.
Closes issue: N/A (Q3 rock)
> chore: ensures axe Pro api

- lib/commons/aria/is-accessible-ref.js
- lib/commons/dom/is-focusable.js
- lib/core/base/context.js
- lib/core/utils/are-styles-set.js
- lib/core/utils/get-scroll.js
- lib/core/utils/is-html-element.js
- lib/core/utils/is-shadow-root.js
- lib/core/utils/qsa.js
- lib/rules/duplicate-id-active-matches.js
- lib/rules/duplicate-id-misc-matches.js
Optimize various functions. Most of the optimizations fall in one of the following categories:
- Switch the order of conditions in `if` statements to order to execute the cheapest operation first
- Short-circuit searches in arrays
- Avoid allocating intermediary arrays
`axe https://www.theguardian.com/international` shows an improvement of ~200ms.
> perf: Improve performance of various functions

- lib/rules/color-contrast-matches.js
- test/rule-matches/color-contrast-matches.js
Ignore nodes of only emoji, nonBMP unicode, and punctuation. Turns out this was a lot easier than I thought since I discovered we had the unicode functions. 
Closes issue: #315
> fix(color-contrast): ignore nodes that don't contain text

- lib/commons/color/get-background-color.js
- test/commons/color/get-background-color.js
In IE11 `scrollIntoView` does not accept an options parameter, so will treat any truthy value as passing the boolean `true`. This changes the behavior of the code that's currently there. 
So instead we'll just see if the center point of the element is within the viewport and if not, look for a scrollable parent element and scroll it. Should fix the issue without causing any problems in IE11.
Closes issue: #1730
> fix(get-background-color): scroll element into view horizontally

- locales/fr.json
élement -> élément (an accent is missing)
doivent êtres -> doivent être (The past participle of "être" is always invariable)
un alternative textuelle -> une alternative textuelle ("un" and "alternative" must be the same gender) 
déterminée car -> déterminiée, car (ponctuation - a coma is needed before "car") 
audiopdescription -> audiodescription (misspelled)
Closes issue:
> chore(i18n): Update french locale

- README.md
Greenkeeper badge is broken, looks bad on NPM and Github.
> docs: Remove broken Greenkeeper badge

- lib/commons/text/is-icon-ligature.js
Tech debt to rename a variable to not collide with the context used in rules.
Closes issue: #1847
> chore(is-ligature-icon): rename canvas to canvasContext

- package.json
Fixes errors in older Safari from `__magic__` global code.
Closes issue: #1764
> fix(doT.js): prevent errors in older versions of Safari

- axe.d.ts
- doc/API.md
- typings/axe-core/axe-core-tests.ts
As per [Wilco's comment](https://github.com/dequelabs/axe-core/issues/894#issuecomment-425159052), `RunOnly` interface should not accept a `RunOnlyObject` for the `values` property. It only can accept a [non-empty array](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/audit.js#L646-L648).
Closes issue: #894 
> fix(axe.d.ts): RunOnly.values should not accept a RunOnlyOption

- axe.d.ts
- doc/API.md
- lib/core/base/audit.js
- test/core/base/audit.js
- typings/axe-core/axe-core-tests.ts
`runOnly` array option will now detect it's type (`tag` or `rule`) based on the supplied values.
Closes issue: #1775 
> feat(audit): allow runOnly option to accept an array of rules

- lib/checks/shared/exists.js
- lib/checks/shared/exists.json
- test/checks/shared/exists.js
- test/integration/rules/server-side-image-map/server-side-image-map.html
- test/integration/rules/server-side-image-map/server-side-image-map.json
What should the remediation message be for this?
Closes issue: #408
> fix(server-side-image-map): return as needs review rather than failure

- lib/checks/lists/listitem.js
- lib/checks/lists/listitem.json
- lib/rules/listitem.json
- test/checks/lists/listitem.js
There was some confusion about lists having overriding roles and `li` children.
Closes issue: #1171
> fix(listitem): clarify that li elements must be contained in a list or role=list

- lib/commons/text/is-icon-ligature.js
- test/commons/text/is-icon-ligature.js
Seems I forgot to trim the string.
Closes issue: #1906
> fix(is-icon-ligature): ignore whitespace characters

- lib/core/public/run.js
- test/core/public/run.js
Concurrent runs of axe is not supported and something we've decided not to support. This should prevent `Expect axe._selectorData to be set up` errors from showing up (which happen due to a concurrent run) and give a way more helpful error as to what the problem is and how to solve it.
Closes issue: #1041 
Closes issue: #1867
> fix(run): throw error if axe.run is called after a run has started but not completed

- lib/commons/dom/is-focusable.js
- test/commons/dom/is-focusable.js
> fix(is-focusable): use tabindex attribute instead of property

- lib/checks/keyboard/tabindex.js
- test/checks/keyboard/tabindex.js
> fix(tabindex): don't error when tabindex property is overridden

- lib/checks/shared/non-empty-alt.js
- test/checks/shared/non-empty-alt.js
Stop using DOM node in non-empty-alt check.
> chore(non-empty-alt): use virtualNode instead of node

- lib/rules/link-name.json
- lib/rules/role-not-button-matches.js
The link-name rule shouldn't be limited to things with an href attribute.
> fix(link-name): test role=link when there is no href

- lib/checks/label/alt-space-value.js
Stop using DOM node in alt-space-value check.
Closes issue:
> chore(alt-space-value): use virtualNode instead of node

- lib/checks/shared/has-alt.js
- test/checks/shared/has-alt.js
Stop using DOM node in has-alt check.
> chore(has-alt): use virtualNode instead of node

- lib/checks/shared/aria-label.js
- lib/commons/aria/arialabel-text.js
- lib/core/base/virtual-node/serial-virtual-node.js
- lib/core/base/virtual-node/virtual-node.js
- lib/rules/label-content-name-mismatch-matches.js
- test/checks/shared/aria-label.js
- test/commons/aria/arialabel-text.js
One of many upcoming PRs that will start to transition axe-core away from directly working on the DOM.
> feat(aria-label): deprecate Element arg; use virtualNode

- Gruntfile.js
- lib/core/utils/parse-crossorigin-stylesheet.js
- test/core/utils/parse-crossorigin-stylesheet.js
This test was always timing out in Phantom in the terminal which was preventing running `npm test` and getting past it. Turns out axios was taking longer than the PhantomJS timeout, so I increased it and used the preload timeout for axios.
> test: prevent timeout in parseCrossOriginStylesheet test

- lib/checks/aria/required-children.js
- lib/commons/aria/index.js
- test/checks/aria/required-children.js
Adds the other allowed expanded child types to the `combobox` owned requirements. If the box is open it checks what the expected role of the expanded element should be and only makes that required. If the box is closed it doesn't make any of them required.
Also modernized the rest of the file (`var` -> `let` or `const`)
Closes issue: https://github.com/dequelabs/axe-core/issues/1009
> fix(aria-required-children): allow comboboxes with more popup roles

- lib/checks/lists/only-listitems.js
- lib/checks/lists/only-listitems.json
- test/checks/lists/only-listitems.js
Add a new message when an `<li>` element has a role that is not `listitem`. I also heavily refactored and simplified the code because it was super confusing to read through and try to figure out what was going on (lots of negation statements, a `reduce` that wasn't needed, confusing logic, didn't make use of `aria.getRole`, etc.).
Closes issue: #1919
> fix(only-listitem): add message about invalid role on li elements

- Gruntfile.js
- doc/developer-guide.md
- lib/core/utils/contains.js
- test/checks/color/color-contrast.js
- test/commons/color/get-background-color.js
- test/commons/color/get-own-background-color.js
- test/commons/dom/is-offscreen.js
- test/commons/dom/is-visible.js
- test/commons/table/is-data-table.js
- test/commons/text/accessible-text.js
- test/core/base/audit.js
- test/core/utils/is-html-element.js
- test/core/utils/preload.js
- test/integration/adapter.js
- test/integration/full/css-orientation-lock/incomplete.js
- test/integration/full/css-orientation-lock/passes.js
- test/integration/full/css-orientation-lock/violations.js
- test/integration/full/preload-cssom/preload-cssom.js
- test/integration/full/preload/preload.js
- test/integration/full/strict-csp/strict-csp.html
- test/integration/full/strict-csp/strict-csp.js
- test/runner.tmpl
- test/testutils.js
Remove checks like `window.PHANTOMJS` from variety of tests.
Closes issue:
- NA
> test: remove `window.PHANTOMJS` checks from tests

- lib/checks/color/color-contrast.js
- lib/checks/color/color-contrast.json
- lib/rules/color-contrast-matches.js
- lib/rules/color-contrast.json
- test/checks/color/color-contrast.js
- test/rule-matches/color-contrast-matches.js
Adding two new config flags to color-contrast so it can check unicode character. Sometimes ligature based icons utilize unicode characters as stand-in's, so these flags become useful to be able to do color-contrast checks on these icons.
ignoreUnicode, defaults to true and retains the behavior of ignoring all unicode characters when doing color contrast. This can be turned off to start checking unicode characters for color contrast.
ignoreLength, defaults to false and retains the behavior that single character nodes do not contain enough information to say whether or not they have color contrast issues. This can be turned on to ignore this length check and always check if a node has color contrast issues.
Closes issue: #1906 
> feat(rule): add color-contrast check for unicode characters, behind flags.

- lib/core/reporters/v1.js
- test/core/reporters/v1.js
This change populates the `failureSummary` field in the v1 reporter for results categorized as `incomplete`.  At the time of writing, this field is currently only populated for `violations`.
Closes issue: #1971 
> feat(v1-reporters): Add failureSummary to incomplete results

- .eslintrc
- lib/.eslintrc
- lib/checks/.eslintrc
- lib/commons/.eslintrc
- lib/rules/.eslintrc
- test/.eslintrc
- test/checks/.eslintrc
`debugger` statements should error on eslint. Unsure why they were set to off previously.
Closes issue:
- NA
> chore: error eslint on debugger statement

- lib/commons/dom/get-element-stack.js
- test/commons/dom/get-element-stack.js
> fix(getElementStack): do not add hidden elements to the stack

- lib/commons/aria/index.js
- test/checks/aria/aria-allowed-role.js
- test/checks/shared/non-empty-title.js
- test/commons/aria/get-element-unallowed-roles.js
- test/commons/aria/is-aria-role-allowed-on-element.js
Prepare test code for #1988. It's mostly just adding `flatTreeSetup` to all the affected tests.
> tests: prepare tests for commons.matches change

- Gruntfile.js
The uglify/beautify script was parsing our escaped unicode regex strings. This turned
```js
function getUnicodeNonBmpRegExp() {
/**
* Regex for matching astral plane unicode
* - http://kourge.net/projects/regexp-unicode-block
*/
return new RegExp(
'[' +
'\u1D00-\u1D7F' + // Phonetic Extensions
'\u1D80-\u1DBF' + // Phonetic Extensions Supplement
'\u1DC0-\u1DFF' + // Combining Diacritical Marks Supplement
// '\u2000-\u206F' + // General punctuation - handled in -> getPunctuationRegExp
'\u20A0-\u20CF' + // Currency symbols
'\u20D0-\u20FF' + // Combining Diacritical Marks for Symbols
'\u2100-\u214F' + // Letter like symbols
'\u2150-\u218F' + // Number forms (eg: Roman numbers)
'\u2190-\u21FF' + // Arrows
'\u2200-\u22FF' + // Mathematical operators
'\u2300-\u23FF' + // Misc Technical …
```
> fix(unicode): stop parsing escaped unicode strings

- lib/checks/aria/valid-attr-value.js
- lib/checks/aria/valid-attr-value.json
- lib/checks/keyboard/page-has-main.json
- test/checks/aria/valid-attr-value.js
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
Aria-current with an invalid value is [just treated as "aria-current=true."](https://www.w3.org/TR/wai-aria-1.1/#aria-current) 
With another value needing to be marked as incomplete we needed to have different remediation messages for each one (aria-describedby for missing id and aria-current for invalid value). Because of this we couldn't return an array of values since we needed to set the `messageKey` property of the data. 
What this all means is that only one needs review item can be marked on an element at a time due to the need of different need review messages.
Closes issue: #1773
> fix(aria-valid-attr-value): mark as needs review for aria-current with invalid value

- lib/checks/navigation/region.js
- test/checks/navigation/region.js
The region rule should always allow content in an ARIA live region. The current code fails the rule based on role before it gets to the `aria-live` check. This fix moves that check up so a region with `role="alert"` and `aria-live` is allowed.
Closes issue: #1992 
> fix(region-rule): allow live regions with explicit roles

- lib/checks/navigation/region.js
- test/checks/navigation/region.js
`alert`, `log`, and `status` have implicit aria-live values of `polite` or `assertive` and should also pass aria-live checks for regions.
> fix(region): allow content in roles with implicit aria-live

- lib/checks/keyboard/page-has-elm.js
- test/checks/keyboard/page-has-elm.js
In the same vain as #1973, if a page has a main or h1 element but it is not visible, it shouldn't pass the check.
> fix(page-has-main): ignore hidden elements

- lib/checks/keyboard/page-no-duplicate.js
- test/checks/keyboard/page-no-duplicate.js
> fix(page-no-duplicate-main): do not fail for duplicate hidden elements

- lib/commons/color/get-background-color.js
- lib/commons/color/get-foreground-color.js
- lib/commons/dom/get-element-stack.js
- test/commons/color/get-foreground-color.js
- test/commons/dom/get-element-stack.js
- test/integration/full/contrast/code-highlighting.html
- test/integration/full/contrast/code-highlighting.js
Code blocks with syntax highlighting could have large amounts of client rects, which would then cause it to take a few seconds each to process. Code blocks could also cause us lots of incomplete results with "partially obscured by another element." 
The code changes fix the speed by focusing only on the client rects of the text nodes of the element rather than all client rects. Since each of the child nodes that have text nodes will be checked individually, there is no need for the main parent to also check those nodes as well. This reduced the large code block from 2000+ client rects to just <20, taking color contrast from running in 10+ seconds to <1 seconds. 
It also adjusts the collision check to account for elements which lie exactly on the middle of the element being checked. This …
> fix(color-contrast): improve speed and accuracy of code blocks with syntax highlighting

- lib/checks/color/color-contrast.js
- lib/checks/color/color-contrast.json
- lib/commons/text/unicode.js
- test/checks/color/color-contrast.js
- test/commons/text/unicode.js
The test for non-BMP characters was actually broken as it was returning `undefined` because of short text content and not because of the non-BMP characters. Also fixed the non-BMP regex to globally ignore characters.
Closes issue: #1993
> fix(color-contrast): mark as needs review for text that contains only non-BMP characters

- lib/core/utils/preload.js
- test/integration/full/preload/preload.js
Preload assets did not reject with `axios.get` failed.
This meant that before this fix, axe.run waited till preload timeout kicked in.
Closes issue:
- NA
> fix(preload): reject promise `axe.utils.preload` when XHR fails

- lib/commons/dom/shadow-elements-from-point.js
- test/commons/dom/shadow-elements-from-point.js
`msElementsFromPoint` in IE extensions can return null instead of an empty array where the point is outside the viewport. This ensures such a scenario doesn't cause color-contrast to bail.
> fix(color-contrast): support IE extension context

- lib/checks/media/no-autoplay-audio.js
Identified that `Number.isNaN` fails in IE11. Also it is a redundant check as we already check if `!node.duration`.
Closes issue:
- NA
> fix(no-autoplay-audio): remove `Number.isNaN` check for node duration

- lib/commons/text/unicode.js
> Street creds for @AdnoC for pairing on this :)
See related issue - https://github.com/dequelabs/axe-core/issues/2023 for description.
In this fix, we create a `RegExp` literal instead of creating a RegExp from a string, which changes uglify behaviour.
This issue is not currently tested by any of the test coverage we have, because all of them use `axe.js` over a the minified `axe.min.js`. This issue was identified under windows ecosystem when executing axe from attest-java using the minified source.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2023
> fix(commons): avoid unicode regex encoding in axe.min.js

- lib/checks/color/color-contrast.js
- lib/checks/color/color-contrast.json
- lib/rules/color-contrast.json
- test/integration/rules/color-contrast/color-contrast.html
- test/integration/rules/color-contrast/color-contrast.json
The check options were not being passed to the check as it was in the wrong place in the JSON file. Moving it to the correct place caused a bug in our [integration test](https://github.com/dequelabs/axe-core/blob/develop/test/integration/rules/color-contrast/color-contrast.html#L27-L32) in that a text field would return as undefined as it's visible text was empty, so we returned `undefined` instead of passing it as the [code assumed any empty text was due to unicodes](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/color/color-contrast.js#L7-L20).
So I had to fix that by ensuring the visible text actually contained unicode characters before checking if it was empty due to removed unicode characters.
Closes issue: #1993
> fix(color-contrast): properly pass options to check

- package.json
Adds https://www.deque.com/axe as the homepage reducing the redundancy on the npm site of having both links point to Github.
Closes issue: #2026 
> chore: Add specific homepage

- locales/fr.json
Fixes a typo I noticed in fr.json
> chore(fr.json): fix typo in incomplete fallback

- lib/checks/color/color-contrast.js
- test/checks/color/color-contrast.js
The computed values of `font-weight` are numeric string so that we don't need to check keywords such as `bold`.
The `font-weight` values are continuous. They can be `123` or `123.4` so that we should parse them as number.
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
Closes issue: #2031 
> fix(color-contrast): parse font-weight value as number (#2031)

- sri-history.json
Explanation for why this went wrong is in #2042.
> fix(sri-history): correct SRI for various axe files

- .circleci/config.yml
- .gitignore
- .npmrc
- package-lock.json
- package.json
An SRI is essentially a hash of axe.js. As of version 3.1 (I think) , we are bundling a few external dependencies into axe-core. This hash is created when we create the release branch, and put into sri-history.json. If any of the dependencies is different when we build locally for the release branch, from when we build in CI right before executing `npm publish`, axe-core will not be identical, and the SRI in sri-history.json will be incorrect.
To fix this, this PR does:
1. add a package-lock file, and use `npm ci` to ensure the server build has the dependencies in the lock file
2. make `npm ci` part of the `npm run release` script, to ensure dependencies are in sync with package-lock
3. Add `npm run sri-validate` before releasing to test the sri matches what is in sri-history.json …
> chore(ci): prevent publishing invalid SRIs

- lib/checks/navigation/region.js
- test/integration/full/region/region-fail.html
We should ignore text nodes that are direct children of body since we cannot target the text node itself and saying "body must be contained within a landmark" doesn't make sense.
Closes issue: #2049
> fix(region): ignore direct child text nodes of body

- lib/rules/color-contrast-matches.js
- test/rule-matches/color-contrast-matches.js
> fix(color-contrast): ignore form elements that move text outside of node using text-indent

- package-lock.json
When we created the package-lock.json, @deqeue/doT.js was resolved to use agora rather than npm.
Thanks to @scurker for finding this.
> fix(package-lock): change @deque/doT from agora to npm

- lib/commons/aria/index.js
- test/checks/aria/aria-allowed-role.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
Added input with a type of tel as an element that should allow the aria role of spinbutton.
Closes issue: #1928 
> fix(aria-allowed-role): allow role=spinbutton on input[type=tel]

- lib/core/utils/get-check-message.js
- test/core/utils/get-check-message.js
Technically this is a `feat`, but we had a breaking change for 3.5.1 that broke eslint-plugin-jsx-a11y, so we need to release this as a patch release so we don't go to 3.6.0. 
With this, they can use a public API rather than accessing a private interface:
```js
export function axeFailMessage(checkId, data) {
return axe.utils.getCheckMessage(checkId, 'fail', data);
}
```
Closes issue: #2060 
> fix(getCheckMessage): add API to return check message

- lib/commons/dom/url-props-from-attribute.js
- test/commons/dom/url-props-from-attribute.js
- test/integration/rules/identical-links-same-purpose/identical-links-same-purpose.html
- test/integration/rules/identical-links-same-purpose/identical-links-same-purpose.json
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2017
> fix(commons):  handle node(s) contained by SVG document when deciphering url properties

- lib/checks/keyboard/page-has-elm.js
- test/checks/keyboard/page-has-elm.js
- test/integration/full/landmark-one-main/landmark-one-main-pass3.html
- test/integration/full/landmark-one-main/landmark-one-main-pass3.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass3.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass3.js
Take into account screen-reader only elements
Closes issue: #2056
> fix(page-has-heading-one): find screen-reader only headings

- doc/API.md
The output contains 2 separate `<ol />` elements instead of just 1 (which I assume was the intent). This only visually worked because we previously hard-coded the numbers in the `<li />`s 
Closes issue: n/a
> docs: nest sublist in context parameter <ol />

- README.md
I noticed in a recent article someone was using the callback API instead of the promise API. The promise API is the preferred way to run axe, so it doesn't make sense that we use the callback API in the readme.
> docs(readme): use axe.run() promise API

- lib/checks/aria/invalidrole.js
- test/checks/shared/invalidrole.js
`invalidrole` should fail only when all roles on a given element are invalid.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2073
> fix: check `invaildrole` fails only when all roles are invalid

- lib/rules/aria-roles.json
- lib/rules/no-empty-role-matches.js
- test/integration/rules/aria-roles/aria-roles.html
- test/rule-matches/no-empty-role-matches.js
Ignore empty, whitespace or undefined `role` for rule `aria-roles`
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2074
> fix: ignore empty, whitespace or undefined `role` for rule `aria-roles`

- lib/checks/language/has-lang.js
- lib/checks/language/has-lang.json
- test/checks/language/has-lang.js
When `xml:lang` attribute is present but no `lang` attribute, it's a bit confusing to say "The <html> element does not have a lang attribute"
Closes issue: #2080
> fix(has-lang): update message to indicate that xml:lang is not valid on HTML pages

- lib/checks/tables/th-has-data-cells.js
- test/checks/tables/th-has-data-cells.js
> fix(th-has-data-cells): fail when data cell points to a different header

- lib/checks/keyboard/page-no-duplicate.js
- test/checks/keyboard/page-no-duplicate.js
The changes in [this pr](https://github.com/dequelabs/axe-core/pull/1949) modified the code in such a way that the first element passed to the check is not filtered based on the `nativeScopeFilter` option. This caused the bug in #2081
Closes issue: #2081
> fix(page-no-duplicate-contentinfo): do not fail when first element is inside landmark

- lib/rules/definition-list.json
Add mention that `<div>` is allowed to group content in `<dl>`, reference:  https://github.com/dequelabs/axe-core/pull/1076.
> fix(definition-list): Mention <div> is allowed to group content in <dl>

- lib/commons/table/get-headers.js
- test/checks/tables/td-has-header.js
- test/commons/table/get-headers.js
Part 1 of 2 (part 2: https://github.com/dequelabs/axe-core/pull/2096)
Partially closes issue: #2039
> fix(td-has-headers): don't fail for empty headers attribute

- lib/commons/text/unicode.js
- test/commons/text/unicode.js
This PR adds unicode characters in Supplementary Private Use Area-A to the `getUnicodeNonBmpRegExp` regex.
Closes issue: https://github.com/dequelabs/axe-core/issues/2101
> fix(unicode) detect supplementary private use area A

- lib/commons/text/unicode.js
- test/commons/text/unicode.js
I added an additional range to the regex in #2102. The purpose of it was to match unicode characters in Supplementary Private Use Area A, and I got the regex itself from https://apps.timwhitlock.info/js/regex.
However, it randomly occurred to me that the part of the regex I added is actually a superset of what was already there. And the real fix to #2101 was not the addition to the regex, but was solely due to [adding `getSupplementaryPrivateUseRegExp` to `hasUnicode`](https://github.com/dequelabs/axe-core/pull/2102/files#diff-e46b3ba4cd0e3b35ba002d5305ee074b) 🤦‍♂.
The existing part was:
```regex
[\uDB80-\uDBBF][\uDC00-\uDFFD]
```
The part I previously added (with an "or") was:
``` regex
[\uDB80-\uDBBE][\uDC00-\uDFFF]|\uDBBF[\uDC00-\uDFFD]
```
Note the overlap in the ranges. In fact, as …
> chore: simplify the regex getting supplementary private use characters

- .eslintrc
- Gruntfile.js
- lib/commons/utils/index.js
- package-lock.json
- package.json
Webpacked the `commons/utils` directory as it has nothing in it really. So made it an easy test case to see this all working. The export is pretty useless in this case but we can fix it later once we convert the entire library in ES Modules (the file itself should go away).
We'll need to be extra sure this is all working. So reviewer should pull down the changes and run `npm run build` and make sure the compiled output (both `axe.js` and `axe.min.js`) still runs in the browser and that `axe.commons.utils` is still there.
Closes issue: #2109 
> chore: add grunt-webpack

- .eslintrc
- Gruntfile.js
- lib/commons/index.js
- lib/commons/matches/attributes.js
- lib/commons/matches/condition.js
- lib/commons/matches/from-definition.js
- lib/commons/matches/from-function.js
- lib/commons/matches/from-primative.js
- lib/commons/matches/index.js
- lib/commons/matches/matches.js
- lib/commons/matches/node-name.js
- lib/commons/matches/properties.js
`commons/matches` is an odd group as everything is added off of the main `matches` function instead of an object. Also, there is a lot of code that accesses just `matches` instead of `commons.matches` so I had to make a global variable and add things to that. Will have to clean up when everything is converted.
Closes issue: #2114 
> chore: convert commons.matches to ES Modules

- lib/core/utils/respondable.js
- lib/core/utils/uuid.js
- test/core/utils/respondable.js
- test/mock/frames/responder.html
- test/mock/frames/results-timeout.html
- test/mock/frames/throwing.html
The code wasn't ignoring errant iframes from responding to our post messages with data we weren't expecting or to reflected messages. So to ensure we ignored these messages I assigned a unique id to each axe instance. When we receive a message we look to make sure the messages came from a different axe instance than the one listening to the event. That way we are guaranteed to only respond to messages sent from an axe instance inside an iframe.
Closes issue: #2127
> fix(respondable): ignore reflected messages from iframes

- lib/commons/dom/find-up.js
- lib/core/utils/closest.js
- test/core/utils/closest.js
Noticed a bug in our `findUpVirtual` code. 
`findUpVirtual` uses `Element.closest` if it's available and uses the passed in node. If it's not available it walks up the parent tree looking for a matching node. However, `closest` will return the current node while our tree walk code always starts at the parent node. This means that in IE11 you get a different result than the other browsers:
```html
<div id="1">
<div id="2">Hi</div>
</div>
<script>
const node = document.getElementById('2');
const upNode = axe.commons.dom.findUp(node, '[id]');
// in IE11 this returns "#1" but in everything else it's #2
console.log(upNode);
</script>
```
Talking to Wilco, he suggested we create a virtual node implementation of `closest` as we have done for `matches`. `findUpVirtual` is also odd in that it …
> feat(closest): VirtualNode implementation of Element.closest. Deprecate commons.dom.findUp and commons.dom.findUpVirtual

- lib/checks/.eslintrc
- lib/checks/aria/required-children.js
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2076
> fix(required-children): consider overriding descendant role(s) when validating required child role(s)

- .eslintrc
- Gruntfile.js
- lib/commons/table/get-all-cells.js
- lib/commons/table/get-cell-position.js
- lib/commons/table/get-headers.js
- lib/commons/table/get-scope.js
- lib/commons/table/index.js
- lib/commons/table/is-column-header.js
- lib/commons/table/is-data-cell.js
- lib/commons/table/is-data-table.js
- lib/commons/table/is-header.js
- lib/commons/table/is-row-header.js
- lib/commons/table/to-grid.js
- lib/commons/table/traverse.js
- test/commons/table/is-column-header.js
- test/commons/table/is-header.js
- test/commons/table/is-row-header.js
Again had to rewrite some tests that mocked. `tables/traverse.js` change is mostly removing the wrapping IIFE (no idea why it did that).
Closes issue: #2115 
> chore: convert commons.table to ES Modules

- lib/core/base/audit.js
This patch refactors the `Audit` into a proper ES5 class. This improves readability while keeping the same functional behavior.
> refactor(Audit): Convert to ES5 class

- .eslintrc
- Gruntfile.js
- build/configure.js
- lib/commons/aria/index.js
- lib/commons/color/index.js
- lib/commons/dom/index.js
- lib/commons/forms/index.js
- lib/commons/index.js
- lib/commons/matches/index.js
- lib/commons/table/index.js
- lib/commons/text/index.js
- lib/commons/utils/index.js
- test/checks/aria/allowed-attr.js
- test/checks/aria/required-attr.js
- test/checks/aria/valid-attr-value.js
- test/checks/aria/valid-attr.js
- test/checks/color/link-in-text-block.js
- test/checks/forms/autocomplete-valid.js
- test/checks/tables/html5-scope.js
- test/commons/color/element-has-image.js
- test/commons/color/get-foreground-color.js
- test/commons/table/get-headers.js
`commons` needs to be a global var to support our current build process (wrapping the entire file in a function and returning it). We can remove that later when we convert the entire build process to just use webpack.
Needed to remove or rewrite some tests that mocked.
> chore: convert commons to ES Modules

- lib/core/base/check.js
- lib/core/base/metadata-function-map.js
Creating the stub for the map that will allow checks to use a string id to access shared evaluate and after functions. Once checks have been converted to es modules we can add them all to the map and have the feature working.
Closes issue:
> feat: support check evaluate functions as an id string

- test/core/reporters/na.js
- test/core/reporters/no-passes.js
- test/core/reporters/raw-env.js
- test/core/reporters/raw.js
- test/core/reporters/v1.js
- test/core/reporters/v2.js
Going through tests and noticed the reporters test all went through `axe.run` and had to mock `axe._runRules`, which just returned the mocked results. So killed the middle man functions and just called the reporters directly with the results.
Closes issue:
> test(reporters): make tests true unit rather than integration tests

- lib/checks/generic/README.md
- lib/checks/generic/attr-non-space-content-evaluate.js
- lib/checks/shared/non-empty-alt-evaluate.js
- lib/checks/shared/non-empty-alt.json
- lib/checks/shared/non-empty-title-evaluate.js
- lib/checks/shared/non-empty-title.json
- lib/checks/shared/non-empty-value-evaluate.js
- lib/checks/shared/non-empty-value.json
- lib/core/base/metadata-function-map.js
- test/checks/shared/non-empty-alt.js
- test/checks/shared/non-empty-title.js
- test/checks/shared/non-empty-value.js
`non-empty-alt`, `non-empty-title`, and `non-empty-value` were all the same function so combined them into a single generic check. Generic checks are new checks that don't have metadata files associated with them so are just evaluate functions called from other checks (can't be used directly in a rule). They typically will need options passed into them to work.
I talked to wilco about `non-empty-title` using `titleText` function and he said it didn't need to do that so was fine to just look at the title attribute directly.
Lastly, all the tests for the old checks are the exact same, especially since now they use the same evaluate underneath. I think we should remove them and just have a single test for the generic one and let the integration tests for the rules that use these checks catch …
> feat(non-space-content): switch all non-empty checks to new generic check

- lib/checks/aria/aria-required-attr-evaluate.js
- test/checks/aria/required-attr.js
We already have an exception for `aria-valuenow` so we needed the same exception for `aria-checked`. See https://w3c.github.io/html-aam/#el-input-checkbox.
Closes issue: #2225
> fix(aria-required-attr): pass aria-checked for elements with checked property

- lib/commons/dom/get-rect-stack.js
- test/commons/dom/get-element-stack.js
Digging into this issue, I realized that children of floated elements should share the same position as their floated parent. Floats do not create stacking contexts, but their children are part of the "floating stack." So comparing a non-floated stack element to floating stack element should not result in the same position (which was causing the bug as the nested `div#2` was being compared against `div#3` and `div#4` and returning the same position, so it defaulted to the inverse DOM order putting `div#2` after the other two).
Closes issue: #2222
> fix(get-element-stack): properly calculate position of children of floated elements

- lib/core/utils/process-message.js
Found a global variable that didn't get imported properly. Would throw an error when we got to that line (very rarely happens).
> chore(process-message): import helper function

- lib/core/base/rule.js
- test/core/base/rule.js
> feat(rule): add reviewOnFail option to have rule return as needs review instead of violation

- lib/checks/generic/matches-definition-evaluate.js
- lib/checks/shared/role-none-evaluate.js
- lib/checks/shared/role-none.json
- lib/checks/shared/role-presentation-evaluate.js
- lib/checks/shared/role-presentation.json
- lib/core/base/metadata-function-map.js
- test/checks/shared/role-none.js
- test/checks/shared/role-presentation.js
There are a few checks we could replace with this if matches could handle things like "attribute is not empty" or "attribute is empty" type checks as well. Once we extend matches with role matching, there are a few more checks we can replace as well.
Closes issue: #2185
> feat(matches-definition): add generic check matches-definition

- lib/checks/mobile/meta-viewport-scale-evaluate.js
- test/checks/mobile/meta-viewport-scale.js
Currently checking this meta viewport tag throws an error:
<meta name="viewport" content="user-scalable=1, minimal-ui">
> TypeError: Cannot read property 'toLowerCase' of undefined
I think the issue was [introduced by this change](https://github.com/dequelabs/axe-core/pull/2137).
This PR fixes the issue by tolerating meta viewport properties without a value.
> fix(meta-viewport): don't throw error if viewport property doesn't have a value

- lib/checks/language/valid-lang-evaluate.js
- lib/checks/language/valid-lang.json
- test/checks/language/valid-lang.js
Part of #2195. Refactored the `reduce`.
> feat(valid-lang): add option for which attributes to look at

- lib/checks/navigation/region-evaluate.js
- test/checks/navigation/region.js
> feat(region): add option to match nodes as region

- lib/checks/shared/avoid-inline-spacing-evaluate.js
- lib/checks/shared/avoid-inline-spacing.json
- test/checks/shared/avoid-inline-spacing.js
> feat(avoid-inline-spacing): add option for which css properties to look at

- lib/rules/aria-input-field-name.json
Adds the missing word "must" to help metadata for ARIA input field name. This puts it in line with the other ARIA rules that include the word "must."
This is helpful for @webhintio, which uses the help field in `axe-core` to provide developer guidance. With the word "must" missing, it is not clear what developer action is needed.
Closes issue:
> fix(aria-input-field-name): add the missing word "must" to help metadata

- lib/core/utils/get-flattened-tree.js
- test/core/utils/flattened-tree.js
In investigating various things, we discovered that passing in a subtree of the DOM to `getFlattenTree` would give bad results when running various APIs. For example, trying to get the accessible name of this structure would return `''` and running the label rule would fail:
```html
<div id="foo">lablled</div>
<input  id="context" aria-labelledby="foo">
<script>
var input = document.getElementById('context');
axe.utils.getFlattenTree(document.getElementById('context'));
var a11yName = axe.utils.accessibleText(input);
assert('a11yName === 'foo');  // returns false
</script>
```
This doesn't happen in a normal `axe.run` as we always set up the virtual tree to be the `documentElement` regardless of what node is passed in. This is only an issue with `getFlattenTree`.
`getFlattenTree` expects …
> feat(utils.getFlattenTree): default to documentElement

- doc/API.md
Noticed the docs for `matches` said it was a CSS selector so corrected it to be a function.
> docs(api): fix matches description

- lib/checks/color/color-contrast-evaluate.js
Found this issue while trying to get [safari running in CI](https://github.com/dequelabs/axe-core/pull/2264). Safari does not translate `font-weight: bold` into a number but instead leaves it as `bold`.
> fix(color-contrast): fix font-weight calculation for safari

- doc/API.md
Another outdated API use. You are only able to configure the `enabled` property of a rule in `axe.run` and not do `axe.configure` like configuration.
> fix(api): correct use of rules property in axe.run

- lib/commons/matches/attributes.js
- lib/commons/matches/explicit-role.js
- lib/commons/matches/from-definition.js
- lib/commons/matches/implicit-role.js
- lib/commons/matches/index.js
- lib/commons/matches/node-name.js
- lib/commons/matches/properties.js
- lib/commons/matches/semantic-role.js
- test/commons/matches/explicit-role.js
- test/commons/matches/from-definition.js
- test/commons/matches/implicit-role.js
- test/commons/matches/semantic-role.js
Specific matches functions are needed to know when to look at [just the explicit role](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/aria-input-field-name.json), just [the implicit role](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/label.json), or [the semantic role](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/button-name.json). This follows the ACT standard of naming.
**Note:** getting the role matches to work with `SerialVirtualNode` will require a rewrite of `getRole` to use the virtual node to access the role attribute, which will require ensuring every test that uses `getRole` at any point to set up the virtual tree, which is a lot of tests. That will be its own pr after #2281 is merged.
Also cleaned up the imports while I was in the …
> feat(matches): add explicitRole, implicitRole, and semanticRole matches functions

- lib/core/public/configure.js
- test/core/public/configure.js
Prevents passing `axe.configure({ rules: ['hello'] });`. Also checked the `checks` property as it had the same problem.
Closes issue: #2282
> fix(configure): validate rules and checks properties

- lib/checks/lists/dlitem-evaluate.js
- lib/checks/lists/only-dlitems-evaluate.js
- lib/checks/navigation/region-evaluate.js
- lib/commons/aria/get-explicit-role.js
- lib/commons/aria/get-role.js
- lib/commons/aria/implicit-role.js
- lib/commons/aria/index.js
- lib/commons/forms/is-aria-combobox.js
- lib/commons/forms/is-aria-listbox.js
- lib/commons/forms/is-aria-range.js
- lib/commons/forms/is-aria-textbox.js
- lib/commons/matches/explicit-role.js
- lib/commons/matches/implicit-role.js
- lib/commons/text/native-text-alternative.js
- lib/rules/aria-allowed-role-matches.js
- lib/rules/aria-form-field-name-matches.js
- test/commons/aria/get-explicit-role.js
- test/commons/forms/is-aria-combobox.js
- test/commons/forms/is-aria-listbox.js
- test/commons/forms/is-aria-range.js
- test/commons/forms/is-aria-textbox.js
- test/commons/matches/explicit-role.js
- test/commons/matches/implicit-role.js
- test/commons/matches/semantic-role.js
- test/rule-matches/aria-allowed-role-matches.js
While working on #2281, one of the tests was failing because it wanted the explicit role but role conflict resolution was getting in the way and returning `null`. So created a function to get just the explicit role with no conflict resolution and made `getRole` the semantic role function. Deprecated the `noImplicit` option of `getRole` as that functionality is now covered by `getExplicitRole`.
Also made sure `getRole` could work with virtual nodes. 
Once this is merged, will pull it into #2281 to finish it off.
> feat(commons/aria): deprecate getRole({ noImplicit }) for getExplicitRole()

- build/tasks/aria-supported.js
When passing the grunt lang option, the generated `axe` file has a suffix of the language supplied. This needs to be catered for when dynamically requiring `axe` in the build step `aria-supported`
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2290
> fix: ensure correctly generated axe is required by `aria-supported` build step

- .github/axe-linter.yml
A bug in axe-linter seems to be crashing on invalid HTML files that we use for our integration tests, as seen in #2304 and #2300. Ignoring our test directory as we purposefully write inaccessible examples. Also ignoring the CHANGELOG which will cause axe-linter to fail from an automated file.
> chore: ignore files for axe-linter

- .github/axe-linter.yml
Regex was bad and was only ignoring the top level test files.
> chore(axe-linter): actually ignore all test files

- .circleci/config.yml
- doc/examples/test-examples.js
I noticed that all our examples use an axe-core version from npm and not the local axe.js file. This meant that us testing the examples for every pr and release does not verify the current code works in the examples, only that the last released version of axe-core works.
Since the examples are there as examples, they should act as standalone examples and install axe-core from npm as a normal user would. However, we can still test the local copy of axe for our tests by overriding the npm version with the local version just in the test run.
> tests: test the examples using local version of axe

- lib/commons/dom/get-text-element-stack.js
- test/checks/color/color-contrast.js
- test/commons/dom/get-element-stack.js
Truncated text whose untruncated text went outside the bounds of the screen caused our color-contrast code to error out. This is caused by the text rect returning the full width of the text and not the truncated width. Fix is to look at the parent nodes rect instead of the text rect if we detect truncated text.
Closes issue: #2178, #2285
> fix(color-contrast): properly handle truncated text

- axe.d.ts
Tags (especially in custom rules) can be any string. Hard-coding this list prevents the ability to use custom tags.
This patch has the unfortunate side-effect of preventing intellisense in TypeScript-enabled editors, but provides more "technically correct" types.
Related #2312
> fix(types): Make any tag allowed

- lib/commons/aria/lookup-table.js
We can read [here](https://w3c.github.io/aria/#aria-orientation) that:
> remain undefined on roles where an expected default orientation is ambiguous (e.g., radiogroup).
which, according to my understanding, implies that `aria-orientation` is allowed on `radiogroup` role, which would also make sense as visually we can present it either horizontally or vertically.
> fix(aria-allowed-attr): Add aria-orientation to radiogroup role

- lib/commons/aria/lookup-table.js
Those resources mention that `radiogroup` supports being named based on `legend`:
https://w3c.github.io/aria/#radiogroup
https://w3c.github.io/aria/#namefromlegend
This mentions what naming by legend is (which is somewhat self-explanatory, but pasting it here for completeness):
https://w3c.github.io/aria/#namecalculation
And we know that `legend` must be a descendant of a `fieldset`.
In addition to that MDN mentions explicitly that `radiogroup` is allowed for a `fieldset`:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#Technical_summary
> fix(aria-allowed-element): Add fieldset to allowed elements for radiogroup

- lib/commons/matches/from-primative.js
- test/commons/matches/from-primative.js
Doing this allows us to replace our `isNotNull` function matchers in the lookup table with serializable strings. `isNull` function matcher can just be replaced by `null` since we already match `null` to `null`.
```diff
{
nodeName: 'a',
attributes: {
-    href: isNotNull
+    href: "/.*/"
}
}
```
> feat(matcher): allow regex string to be parsed as regex

- build/rule-generator/get-files-metadata.js
We have a CLI (`npm run rule-gen`), which helps generate all the relevant files with code snippets when writing a new rule, by prompting the user to simply follow a Q&A wizard. 
This change updates the generator to output ES Modules friendly code in the matches, rules & checks file accordingly.
> Note: I recently was looking to write a new rule and used the generator & thence the PR to update this.
Closes issue:
- NA
> chore: adapt `rule-generator` script to output ES Modules snippets

- .github/axe-linter.yml
Doesn't work with the leading `./`
> ci: remove leading ./ from ignored axe-linter files

- lib/commons/forms/is-aria-combobox.js
- lib/commons/forms/is-aria-listbox.js
- lib/commons/forms/is-aria-range.js
- lib/commons/forms/is-aria-textbox.js
- lib/commons/forms/is-native-select.js
- lib/commons/forms/is-native-textbox.js
- test/commons/forms/is-native-select.js
- test/commons/forms/is-native-textbox.js
- test/commons/text/form-control-value.js
Part of issue: #2183 of checks that use accessible-text-virtual code path (for example,`focusable-no-name`)
> fix(forms/*): allow all form control value checks to work with virtual nodes

- lib/checks/generic/has-text-content-evaluate.js
- lib/checks/shared/has-visible-text.json
- lib/commons/aria/lookup-table.js
- lib/commons/aria/named-from-contents.js
- lib/standards/aria-roles.js
- test/checks/shared/has-visible-text.js
- test/commons/aria/named-from-contents.js
I noticed that `named-from-contents` had an exception for `table` elements to always be considered named from contents. The comment said it was because the implicit role was too over-assertive but I couldn't find any tests in the `named-from-contents` test suite that showed an example nor could I find a reason in [the original pr it was created](https://github.com/dequelabs/axe-core/pull/1163). 
So I removed the exception and just allowed `table` role to be named from contents. This seemed like a better place for it and still allowed all the tests to pass (without the exception two of our accessible name acceptance tests failed as they required the `table` element to be named from contents).
Part of issue: #2183
> fix(checks/has-visible-text): work with virtual and serial nodes

- lib/standards/html-aria.js
- lib/standards/html-elms.js
Continued from #2325 to get a clean tree instead of a botched file merge of 34 file changes. 
This table replaces some hardcoded values in our code and allows us to work on #1597 and #601 by allowing us to identify interactive content.
Replaces these values: 
* `phrasingElements` in [subtree-text](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/text/subtree-text.js#L31-L72)
* `htmlTags` in [is-html-element](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/is-html-element.js#L1-L120) (which is why there are empty objects)
* `possibleShadowRoots` in [is-shadow-root.js](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/is-shadow-root.js#L1-L20)
* part of the `sectioningElementSelector` in …
> feat(standards): add html-elms spec

- lib/checks/aria/no-implicit-explicit-label-evaluate.js
- lib/commons/dom/find-elms-in-context.js
- lib/commons/text/label-text.js
- lib/rules/aria-form-field-name-matches.js
- test/checks/aria/no-implicit-explicit-label.js
- test/rule-matches/aria-form-field-name-matches.js
> fix(aria-toggle-field-name): work with virtual nodes

- lib/core/base/virtual-node/serial-virtual-node.js
- lib/core/base/virtual-node/virtual-node.js
- test/core/base/virtual-node/serial-virtual-node.js
- test/core/base/virtual-node/virtual-node.js
Allows us to do input property matches with case insensitivity for serial and virtual nodes.
```js
const input = document.createElement('input');
input.setAttribute('type', 'BUTTON');
const vNode = axe.utils.getFlattenedTree(fixture)[0];
commons.matches(vNode, {
properties: {
type: 'button'
}
}); // true
const serialNode = new axe.SerialVritualNode({
nodeName: 'input',
attributes: {
type: 'BUTTON'
}
});
commons.matches(serialNode, {
properties: {
type: 'button'
}
}); // true
```
> fix(virtual-node): default and lowercase type property

- lib/commons/aria/get-roles-with-name-from-contents.js
- lib/commons/standards/get-aria-roles-supporting-name-from-content.js
- lib/commons/standards/index.js
- lib/rules/label-content-name-mismatch-matches.js
- test/commons/aria/get-roles-with-name-from-contents.js
- test/commons/aria/roles.js
- test/commons/standards/get-aria-roles-supporting-name-from-content.js
The function did mostly what `getGlobalAriaAttrs` did so moved it to the standards table as another function that aggregates information about the standards object.
Part of #2108
> feat(standards): add get-aria-roles-supporting-name-from-content and deprecate aria/get-roles-with-name-from-content

- lib/commons/aria/allowed-attr.js
- lib/commons/standards/get-global-aria-attrs.js
- test/commons/aria/allowed-attr.js
- test/commons/aria/attributes.js
- test/integration/rules/aria-allowed-attr/passes.html
Refactored `allowedAttr` to have a better happy path and return early if no role def was found, also didn't need to `concat` everything. Since getting global attrs is found in a lot of code, went ahead and cached the result as it shouldn't change during a run. 
The integration tests were expected from the diff in our lookup table in https://github.com/dequelabs/axe-core/pull/2328#issuecomment-651218760
Part of #2108 
> fix(aria/allowed-attr): work with standards object

- lib/commons/aria/get-role-type.js
- test/commons/aria/get-role-type.js
- test/commons/aria/roles.js
Refactored `get-role-type` to have a better happy path and return early rather than doing the `&&` and `||` checks.
Part of #2108
> fix(aria/get-role-type): work with standards object

- lib/checks/keyboard/landmark-is-top-level-evaluate.js
- lib/checks/navigation/region-evaluate.js
- lib/commons/aria/get-roles-by-type.js
- lib/rules/landmark-unique-matches.js
- test/commons/aria/get-roles-by-type.js
- test/commons/aria/roles.js
We should probably have a discussion about what `commons/aria` functions should be moved into the standards helpers.
Part of #2108
> feat(aria/get-roles-by-type): deprecate in favor of standards/get-aria-roles-by-type

- lib/standards/aria-roles.js
- test/commons/standards/get-aria-roles-by-type.js
Noticed the `none` role wasn't in the standards object. I think what happened is I took the standards object as the base and compared it agains the lookup table instead of the other way around. So I did that and this is the new results (that are different than the ones we already approved in https://github.com/dequelabs/axe-core/pull/2328#issuecomment-651218760)
```js
allowed attrs is not present for role: doc-pullquote, ['aria-expanded']
allowed attrs is not present for role: rowgroup, ['aria-activedescendant', 'aria-expanded', 'aria-errormessage']
```
Also, fun fact: the dpub roles in the lookup table all use `namefrom` (no capital F) and so they would never return `true` when checking name from contents. But we wouldn't know because when we ask name from contents of a role, [dpub roles …
> chore: fix standard roles

- lib/commons/aria/get-role.js
- test/commons/aria/get-role.js
> chore(get-role): work with standards object

- lib/checks/aria/aria-errormessage-evaluate.js
- test/checks/aria/errormessage.js
> chore(aria-errormessage): work with standards object

- lib/commons/aria/is-aria-role-allowed-on-element.js
- lib/commons/matches/from-primative.js
- lib/standards/html-elms.js
- test/checks/aria/aria-allowed-role.js
- test/commons/aria/get-element-unallowed-roles.js
- test/commons/aria/is-aria-role-allowed-on-element.js
- test/commons/matches/from-primative.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
Discovered regex `.test(str)` typecasts the str to a String value, so doing `/.+/.test(null) === true` as null is cast to the string "null." So had to fix that in our matcher. Also fixed the standards object to allow roles on things the spec says are allowed no role (no alt imgs and inputs type=tel,url.search,email).
I also think our test for `get-element-unallowed-roles.js` was a false-positive as it should not have passed before but did (`menubar` should not be allowed on `li`).
Part of #2108
> chore(aria-allowed-role): work with standards object

- lib/commons/aria/is-unsupported-role.js
- lib/commons/aria/is-valid-role.js
- test/checks/aria/unsupportedrole.js
- test/commons/aria/is-unsupported-role.js
- test/commons/aria/is-valid-role.js
- test/commons/aria/roles.js
Notice that `is-valid-role` should have used `is-unsupported-role` but duplicated the code so converted it to use it.
> chore(is-unsupported-role,is-valid-role): work with standards object

- lib/checks/aria/aria-unsupported-attr-evaluate.js
- lib/commons/aria/validate-attr.js
- test/checks/aria/unsupportedattr.js
- test/checks/aria/valid-attr.js
- test/commons/aria/attributes.js
- test/commons/aria/validate-attr.js
- test/integration/rules/aria-allowed-attr/failures.html
- test/integration/rules/aria-allowed-attr/failures.json
Aria-describat was removed in https://github.com/dequelabs/axe-core/pull/2315.
> chore(validate-attr,unsupported-attr): work with standards object

- lib/checks/navigation/region-evaluate.js
- test/integration/full/region/region-fail.html
- test/integration/full/region/region-pass.html
`title` no longer provides a `<section>` element an accessible name as we went with the [Safari implementation](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/aria/lookup-table.js#L2117-L2125).
> chore(region): work with standards object

- lib/rules/autocomplete-matches.js
- lib/rules/label-content-name-mismatch-matches.js
> chore(autocomplete/label-content-name-mismatch-matches): work with standards object

- lib/commons/aria/named-from-contents.js
- test/commons/aria/named-from-contents.js
> chore(named-from-contents): work with standards object

- lib/checks/aria/aria-required-parent-evaluate.js
- lib/commons/aria/implicit-nodes.js
- lib/commons/aria/required-context.js
- test/commons/aria/required-context.js
- test/commons/aria/roles.js
Implicit nodes is being deprecated in favor of just getting the role of the node in question. 
> chore(aria-required-parent): work with standards object

- lib/checks/aria/aria-required-children-evaluate.js
- lib/commons/aria/required-owned.js
- lib/standards/aria-roles.js
- test/commons/aria/required-owned.js
- test/commons/aria/roles.js
Huge refactor of the code since we aren't using `implicitNodes` anymore. This is the last bit of code that uses the `lookupTable`
> chore(required-children): work with standards object

- lib/checks/aria/aria-allowed-attr-evaluate.js
- lib/commons/aria/lookup-table.js
- test/checks/aria/allowed-attr.js
- test/commons/aria/get-explicit-role.js
This pr officially closes #2108 as it removes all lookup table references in our codebase expect where we still need it (mostly for `implicitNodes` which is deprecated as well and keeping `lookupTable` as a public API).
I noticed the `aria-allowed-attr` test still used the lookup table to configure the options test, which shouldn't have worked. Digging further I found multiple things wrong with that test that would cause it to never fail. 
First, without `mccheddarton` being configured into the standards object, the check would always pass as there was no allowed role data for an invalid role. Second, since `aria-snuggles` was not configured into the standards object, it would not be counted as a valid attribute so wouldn't fail on it either. Lastly, even if those were configured, since …
> feat(aria/lookupTable, aria-allowed-attr): deprecate aria.lookupTable and passing allowed attributes to aria-allowed-attr

- lib/core/base/metadata-function-map.js
- lib/rules/layout-table-matches.js
TECH DEBT: There are no tests for this. Because this matches isn't used in any rule, it can't be accessed on the `axe` object. This can be solved once we have Babel enabled on our tests.
Closes issue:
> feat: add layout-table-matches method

- lib/checks/keyboard/focusable-no-name-evaluate.js
- lib/commons/aria/get-role.js
- lib/commons/standards/implicit-html-roles.js
- test/integration/virtual-rules/index.html
- test/integration/virtual-rules/link-name.js
> tests: add test for link-name for serial nodes

- locales/da.json
- locales/de.json
- locales/es.json
- locales/eu.json
- locales/fr.json
- locales/ja.json
- locales/ko.json
- locales/nl.json
- locales/pt_BR.json
Used a script to auto-convert each file. 
Note: the `failureSummaries` section is not converted as we didn't even do it in the English version. Looking at it I'm not sure what the appropriate value should be so we'll need to discuss that before we merge this in. Here's what it currently looks like:
```js
"failureMessage": "Fix any of the following:{{~it:value}}\n  {{=value.split('\\n').join('\\n  ')}}{{~}}
```
Closes issue: #2190
> chore: update all locales to new format

- doc/API.md
- lib/checks/color/color-contrast-evaluate.js
- lib/commons/color/get-foreground-color.js
- lib/core/public/run-rules.js
- test/core/public/run.js
Note: the comment is more for us internally as a way to remind us to remove it at some point. The option is actually inert but the public API still accepts it as a parameter.
Closes issue: #2388
> chore: remove noScroll option from color-contrast

- lib/core/base/audit.js
- lib/core/base/check.js
- lib/core/base/rule.js
- test/core/base/check.js
- test/core/base/rule.js
@downzer0 discovered this one when trying to configure a rule with a `matches` function ID. I added tests to ensure this should work now as well as throw a more helpful message as the default was eval the string as code and you'd get a `thing is not defined` error which was super unhelpful. So now you should get an error with the name of the string you used.
> fix(rule,check): allow function ids for matches property in rule.configure

- doc/API.md
- doc/accessibility-supported.md
- doc/code-submission-guidelines.md
- doc/developer-guide.md
- doc/rule-development.md
The [API docs for standards](https://github.com/dequelabs/axe-core/pull/2417/files) has a few additional things I didn't pull over. Also, the formatting of newlines was a bit odd so I fixed some of that too where I saw it.
Closes issues: #2277, #1936, #2323, and #840
> docs: ensure up-to-date

- doc/check-options.md
I only included checks whose options modified how the check behaved. Checks which used generic checks (such as `non-empty-title`) were not added to list as their options are not really there for the user to customize. Generic checks will be described in another doc about creating custom rules.
Note: I do not understand what all the options for `p-as-heading` do even from looking at the code. If anyone can provide that understanding that'd be great.
Rendered view https://github.com/dequelabs/axe-core/blob/62e559fd7c65b8f426d01d99803854b3b9dcef6c/doc/check-options.md
Closes issue: #2187 
> docs: add docs for check options

- doc/check-options.md
Forgot the `reivewOnFail` global option.
> docs: add reviewOnFail

- lib/core/base/audit.js
- lib/core/base/check.js
- lib/core/core.js
- test/core/base/check.js
- test/core/base/rule.js
- test/integration/full/configure-options/configure-options.js
Prevent breaking change to custom check options. Moved the `metadataFunctionMap` to the private test object as it was suppose to be there to begin with and not on the private `audit` object.
#Reviewer checks
> fix(checks): do not normalize options for custom checks

- .circleci/config.yml
- .circleci/verify-release.sh
Copying over what we did in [react-axe](https://github.com/dequelabs/react-axe/pull/176) to verify releases before and after publish
> ci: verify release

- lib/commons/dom/reduce-to-elements-below-floating.js
- test/checks/color/color-contrast.js
Found this as a bug when testing on a site. The variable is reassigned to an empty array under certain conditions.
> fix(color-contrast): dont error for floating element

- lib/checks/shared/svg-non-empty-title-evaluate.js
- lib/checks/shared/svg-non-empty-title.json
- test/checks/shared/svg-non-empty-title.js
Update fail message to indicate if the title element is empty or missing
Closes issue #2452
> feat(svg-non-empty-title): update fail message

- lib/checks/navigation/heading-order-evaluate.js
- test/checks/navigation/heading-order.js
Use vitrual node rather than node
Closes issue #2465
> refactor(heading-order): use virtual node

- lib/rules/link-name.json
- test/integration/rules/link-name/link-name.html
- test/integration/rules/link-name/link-name.json
- test/integration/virtual-rules/link-name.js
> fix(link-name): fix regression where link was not named from title attribute

- .circleci/config.yml
- Gruntfile.js
Our tests are failing because of chrome-mobile. Turning off for now, created a [tech debt ticket for it](https://github.com/dequelabs/axe-core/issues/2497). Also [fixing our puppeteer example test](https://app.circleci.com/pipelines/github/dequelabs/axe-core/1125/workflows/793b36c0-0ddc-4507-adc7-ccb402918002/jobs/21505) by including the [circleci orb](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-circleci) that has all the required dependencies. 
> tests: disable chrome-mobile testing, fix puppeteer example test

- lib/checks/generic/attr-non-space-content-evaluate.js
- lib/checks/shared/non-empty-alt.json
- lib/checks/shared/non-empty-placeholder.json
- lib/checks/shared/non-empty-title.json
- lib/checks/shared/non-empty-value.json
- test/checks/shared/non-empty-alt.js
- test/checks/shared/non-empty-placeholder.js
- test/checks/shared/non-empty-title.js
- test/checks/shared/non-empty-value.js
Split no attribute and empty attribute message
Closes issue: fixes #2451, fixes #2453
> fix(attr-non-space-content-evaluate): Split no attribute and empty attribute message

- locales/fr.json
- fixed basic typos
- replaced "s'assure que" by "vérifier que"
- removed subjunctive forms
- typography: homogenized apostrophes
- typography: added spaces before : and !
- fixed singular / plural
- fixed genders
- added some elisions of vowels
Closes issue #2484
> style(locales): proofreading of the french translations

- lib/rules/object-alt.json
- test/integration/rules/object-alt/object-alt.html
- test/integration/rules/object-alt/object-alt.json
- test/integration/virtual-rules/object-alt.js
Fallback content can not be used to give an object an accessible name. Instead us aria-label(ledby) or title.
Closes issue: #2524
> fix(object-alt): do not allow fallback content for objects

- lib/core/base/metadata-function-map.js
- lib/rules/bypass-matches.js
- lib/rules/document-title.json
- lib/rules/html-has-lang.json
- lib/rules/is-initiator-matches.js
- lib/rules/window-is-top-matches.js
- test/rule-matches/is-initiator-matches.js
This allows Cypress to run `document-title` and `html-has-lang` rules inside the iframe by making whichever context `axe.run` was called the "top-level" context (be it an iframe or the top-most window).
Closes issue: #1618 
> feat(rule-matches): depreacte window-is-top-matches for is-intiator-matches

- .circleci/config.yml
- .circleci/verify-release.sh
Our verify-next-release script keeps failing because of a race condition between npm having it and when our verify script tries to pull it down. Fixing the condition by putting in a sleep command to make the verify script wait before trying to pull it down from npm.
> cli: wait before verifying

- package-lock.json
- package.json
Upgrades standard-version to v9.0.0, which has a security fix for dot-prop. The major change for v9 was that node 8 is no longer supported.
> chore: update standard-version to v9.0.0

- doc/accessibility-supported.md
Adds note about how we determine what new screen readers, browsers, or environments we accessibly support and add JAWS/Chrome as an accessibility supported combination.
> docs: add note about how to determine new accessibility supported

- lib/commons/standards/implicit-html-roles.js
- test/commons/aria/implicit-role.js
Closes issue: #2514 (axe should be aware of input type default of text )
> fix(implilcit-role): use type property instead of attribute to resolve input role

- README.md
Remove the CircleCI badge because it is no longer needed now that we have Slack integration and it changes status multiple times over the day making us look bad on npm
> chore: remove CircleCI badge

- lib/checks/aria/aria-errormessage-evaluate.js
- lib/checks/aria/aria-errormessage.json
- test/checks/aria/errormessage.js
If IDs in aria-errormessage do not correspond to existing elements, return undefined to mark for review.
Closes issue #2460
> fix(checks/aria): mark elements missing from aria-errormessage for review

- lib/commons/aria/get-role.js
- test/commons/aria/get-role.js
Add option to getRole to return null if 'presentation' or 'none'
would be returned
Closes issue #1792
Closes issue:
> feat(get-role): add noPresentational option

- lib/rules/aria-hidden-body.json
- test/integration/full/aria-hidden-body/pass.html
- Adding "is-initiator-matches" to aria-hidden-body.json
- Updating aria-hidden-body/pass.html integration test to include an iframe with aria-hidden='true' on the body
Closes issue: https://github.com/dequelabs/axe-core/issues/1251
> fix(aria-hidden-body): Do not run on iframes

- doc/API.md
> docs: note that axe.configure reporter option can be a function

- lib/checks/label/explicit-evaluate.js
- test/checks/label/explicit.js
> fix(explicit-label): work with multiple labels

- doc/check-options.md
- lib/checks/navigation/region.json
- test/checks/navigation/region.js
I was looking into how our region rule was passing a test for `role=dialog` when an issue said it wasn't. Turns out our test wasn't written correctly so even though the code should have been failing it wasn't. I made sure to edit all the tests to ensure they work as expected and added a note at the top of the file on how to properly add a new test fixture. 
I also removed the form with title test since with 4.0 it is [no longer considered a landmark](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/standards/implicit-html-roles.js#L33-L45) and also suffered from the same problem as the dialog test.
Lastly, our code already supported a `regionMatcher` option so I just made sure to provide defaults for dialog and svg.
Closes issue: #1832 and #2556 
**Required fields, to be …
> fix(region): allow role=dialog and svg elements outside regions

- lib/checks/aria/aria-errormessage-evaluate.js
Spec (https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage) only states that "authors MAY use live regions for the error message element applying either an aria-live property or using one of the live region roles".
So we probably shouldn't enforce any role, unless we consider it a bad practice. In that case we should at least allow "polite" announcements, as "authors SHOULD NOT use the assertive value unless the interruption is imperative".
> fix(aria-errormessage): allow aria-live="polite" on aria-errormessage target

- lib/core/utils/css-parser.js
- lib/rules/scrollable-region-focusable-matches.js
- test/core/utils/matches.js
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.html
- test/rule-matches/scrollable-region-focusable-matches.js
The changes to the `css-parser` and `matches` file were to accommodate matching the space separated attributes of `aria-controls` and `aria-owns` (otherwise `aria-controls="foo target"` would fail when it shouldn't). The parser and our `matches` file can handle them so I'm not sure why they were turned off to begin with. I also added tests to test each attribute equation style we support.
Closes issue: #1763
> fix(scrollable-region-focusable): do not fail for combobox pattern

- lib/core/base/rule.js
- test/core/base/rule.js
This was more difficult than I had hoped. The functions all mutate the original results through various passes, which meant that I couldn't return a new object as the final filter of `item.filtered === true` had to run on the original `result.nodes`. I'm not a fan of how we're doing it, but it would take a huge refactor to get it to work differently, and an even bigger understanding of why we are doing what we are doing.
I then tried to just add the `node` object directly to the check result, but that resulted in the final `results` object that axe returns having the node property for every check result. This wasn't ideal and frankly not needed as the parent check object has the node in question. 
So to get everything to work, I added the node to the object and then deleted it after we …
> fix(rule): add check node to the check result object

- lib/rules/aria-toggle-field-name.json
- package-lock.json
- test/integration/rules/aria-toggle-field-name/aria-toggle-field-name.html
- test/integration/rules/aria-toggle-field-name/aria-toggle-field-name.json
- test/integration/virtual-rules/aria-toggle-field-name.js
Test that elements with role=option have an accessible name. There's really no good reason for empty options to exist that I can think of, so those should be flag up.
Part of issue #2421
> feat(aria-toggle-field-name): add option role

- lib/standards/aria-roles.js
Added superclassRole attributes as an array of strings per WAI-ARIA 1.1 spec
Closes issue #2151
Added superclassRole to each aria-role per WAI-ARIA 1.1 spec
Closes issue:
> feat(standards): add superclassRole to ariaRoles

- doc/API.md
Just found a dangling link, not sure if this required to create an issue on its own
Best
> docs: Fix broken link to heading-order-evaluate.js

- lib/checks/navigation/region.json
- test/checks/navigation/region.js
- test/integration/full/region/frames/region.html
- test/integration/full/region/region-pass.html
- test/integration/full/region/region-pass.js
Treat iframes as regions. If content inside the iframe does not have a region, we'll get a report on just that content.
Closes issue: #2330 
> fix(region): treat iframes as regions

- lib/checks/color/color-contrast-evaluate.js
- lib/checks/color/color-contrast.json
- test/checks/color/color-contrast.js
Checking for pseudo content adds about 1 second on a [very large site](https://js.tensorflow.org/api/latest/) (26,678 nodes) to our color-contrast check:
| Branch | Time (ms) | 
| --------  | ---------------- |
| Develop | 8413.33 |
| Contrast-pseudo | 9649.56 |
Closes issue: #975 
> fix(color-contrast): mark elements with pseudo content as needs review

- Gruntfile.js
- package-lock.json
- package.json
Just outputting the file size of `axe.js` and `axe.min.js`.
**Note:** Based on these numbers, we've reduced axe-cores' minified file size (from our [4.0 release](https://github.com/dequelabs/axe-core/issues/2357)) by 135 kB and gzipped size by 30 kB. So far all we've done is changed the way we stored [valid-lang](https://github.com/dequelabs/axe-core/pull/2527) and switched from [webpack to esbuild](https://github.com/dequelabs/axe-core/pull/2579).
> chore: add file size to grunt output

- lib/commons/dom/get-text-element-stack.js
- test/commons/dom/get-element-stack.js
Text whose container was smaller than the text itself caused the same problems as [truncated text](https://github.com/dequelabs/axe-core/pull/2302). 
Closes issue: #2483
> fix(color-contrast): properly handle scrolling text

- Gruntfile.js
I got tired of waiting for axe-core to fully build just because I changed a test file. Updated the Gruntfile to only build axe-core when the `lib` or `Gruntfile` changes and only build test files when the `test` changes.
> chore: don't rebuild axe when tests change

- lib/commons/text/subtree-text.js
- test/commons/text/accessible-text.js
- test/integration/rules/link-name/link-name.html
- test/integration/rules/link-name/link-name.json
To figure this one out I tested the following code:
```html
<label for="bar" id="foo">
<a href="/" id="baz">
<div role="alert" aria-label="Goodbye">Hello</div>
<div role="textbox" aria-label="mars">earth</div>
<div role="img">people</div>
</a>
</label>
<input type="button" aria-labelledby="foo" id="bar" />
```
The surprising thing is that AT gave different names than the browsers do. The button works fairly consistently, but most AT seem to have something in place to deal with this `a[href] > article:not([aria-label])` scenario. Here are my test results:
(either aria-labelledby or explicit label)
| Browser (+AT)  | Link                | Button
|----------------|---------------------|-----------------
| Chrome name    | Goodbye mars        | Goodbye mars
| NVDA + Chrome  | Hello mars …
> fix(link-name): pass landmark content as link text

- doc/standards-object.md
- lib/core/base/metadata-function-map.js
- lib/rules/button-name.json
- lib/rules/image-alt.json
- lib/rules/input-button-name.json
- lib/rules/input-image-alt.json
- lib/rules/no-explicit-name-required-matches.js
- lib/rules/object-alt.json
- lib/standards/aria-roles.js
- test/integration/rules/button-name/button-name.html
- test/integration/rules/button-name/button-name.json
- test/integration/rules/image-alt/image-alt.html
- test/integration/rules/image-alt/image-alt.json
- test/integration/rules/input-button-name/input-button-name.html
- test/integration/rules/input-button-name/input-button-name.json
- test/integration/rules/input-image-alt/input-image-alt.html
- test/integration/rules/input-image-alt/input-image-alt.json
- test/integration/rules/object-alt/object-alt.html
- test/integration/rules/object-alt/object-alt.json
- test/rule-matches/no-explicit-name-required-matches.js
Accessible name rules for native elements (image-alt, button-name, etc.) should be inapplicable if the role is changed to a role that does not require an accessible name, but only if that element is not focusable. This does not include link-name /area-alt because even with `tabindex="-1"`, these can be focused with click / touch.
Closes issue: #2578
> fix(name-rules): ignore when explicit roles don't require a name

- lib/commons/dom/get-text-element-stack.js
- test/commons/dom/get-element-stack.js
Padma found that if there was whitespace before the text my code didn't fix the issue. This change should address that.
Closes issue: #2483
> fix(commons/get-text-element-stack): account for newline characters when text is larger than container

- Gruntfile.js
When a `lib` file was changed the `build` task would clean the entire `tmp` directory. However, the tests need the `tmp/integration-tests.js` file in order to run the integration tests. So I updated the clean task to not clean the integration test file unless the tests change.
> chore: fix watch

- lib/core/imports/index.js
- package-lock.json
- package.json
These polyfills, previously provided by `core-js` / `core-js-pure`, can also be fulfilled by existing bundled dependencies within `axe-core`.
In particular:
- `es6-promise` can provide `Promise`
- `typedarray` can provide `Uint32Array` (and was an implicit dependency, but is now added to `package.json` explicitly)
- `weakmap-polyfill` can provide `WeakMap`
This *might* provide an opportunity to remove `core-js` and `core-js-pure` completely from `axe-core`'s dependencies.
Unit tests pass **intermittently** locally, so additional verification would definitely help.  In particular, `UnhandledPromiseRejectionWarning` exceptions appear to be thrown unpredictably from the headless browser environment.
**Build Size Impact**
Before @ 3c2429b4032d29cdcfd3083e46e91854dccd733b
```sh
$ npm …
```
> core(cleanup): core/lib/imports: remove core-js and core-js-pure dependencies

- lib/core/imports/index.js
- package-lock.json
- package.json
- test/integration/full/umd/umd-module-exports.js
- test/integration/full/umd/umd-window.js
For some reason switching from esbuild allowed axios to run which made navigator not defined. 
> fix: remove axios import

- lib/commons/text/subtree-text.js
- lib/standards/html-elms.js
- test/playground.html
Had to make `input` not a phrasing element in order to pass the accessible name acceptance tests. Also, should we add `#text` as an html element so we don't have to concat it to the end of the array?
Closes issue: #2632 
> chore: replace phrasing elements in subtree-text

- package-lock.json
- package.json
- test/integration/full/test-webdriver.js
Chrome is [failing to start a lot](https://app.circleci.com/pipelines/github/dequelabs/axe-core/1479/workflows/c9511638-cba6-4217-b2b5-2a5efa5b1fa2/jobs/24819) and with no apparent reason as this was all working fine when running it as Grunt. This is a copied/pasted file that worked before but now fails. Trying this to see if it resolves the issues as suggested in various sites.
Going to cancel and rerun this build a couple of times to see if it's working consistently.
> tests: run ChromeHeadless for integration test 

- lib/rules/select-name.json
I noticed this while testing some pages, just a minor typo fix.
> fix(select-name): fix typo in accessible name help

- lib/standards/aria-roles.js
- lib/standards/dpub-roles.js
Required for #601. Using this we can do the following for the rule:
1. look for all `[role]` elements and match by any roles that have `childrenPresentational: true`
1. look at all descendants of said elements and return `false` if any element is focusable (using `dom.isFocusable`)
> feat(standards/aria-roles): add presentational children property

- Gruntfile.js
- build/tasks/test.js
- test/integration/api/external/index.js
- test/karma.conf.js
This fixes `npm run develop` by running tests after a file has changed. The karma file then runs only the tests that are associated with the file that was changed (instead of all tests). 
It does this by looking at the passed in file path and matching it against known tests. For example, a file ending with `-matches.js` should run a rule by the same name in the `rule-matches` directory. This isn't guaranteed to find a file that matches (for example, there are some rule-matches that aren't tested, or some aria checks that don't have the same name of the test file), but karma will alert you if there isn't a test by that name. So you can either fix it (like we should with the aria checks) or ignore it.
This also fixes a test failure in the api tests that would happen very sporadically. It …
> chore: fix grunt develop

- README.md
Added information on building for locale with npm. Grunt still works fine but the documentation didn't cover the correct way to pass arguments to grunt through npm. Since this is core npm behavior, it isn't something that can or should be changed, but should be documented so that it can be used for building.
Closes issue: #2649
> docs: added information on building for locale with npm

- test/karma.conf.js
Right now it tries to run the `html` file, which is not a valid test file.
> tests: re-run tests for integration/rule html files in develop mode

- .circleci/config.yml
Testing to see if circle ci even has nightly browsers set up.
Closes issue: https://github.com/dequelabs/axe-core/issues/980
> ci: run tests against nightly browsers

- lib/checks/aria/no-implicit-explicit-label-evaluate.js
- lib/checks/label/explicit-evaluate.js
- lib/checks/label/hidden-explicit-label-evaluate.js
- lib/checks/shared/svg-non-empty-title-evaluate.js
> chore: don't be so greedy in virtual checks with try/catch

- lib/checks/aria/aria-valid-attr-value-evaluate.js
- test/checks/aria/valid-attr-value.js
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
Closes issue: https://github.com/dequelabs/axe-core/issues/2621
> fix(aria-valid-attr-value): report when aria-labelledby ref is not in DOM

- lib/commons/table/get-headers.js
- lib/commons/table/to-grid.js
- test/commons/table/get-headers.js
- test/commons/table/to-grid.js
Even though MDN reports that it isn't supported, I tested it in Windows and Mac and it's supported in all browsers:
Closes issue: #2553
> fix(to-grid/get-headers): work with rowspan=0

- test/karma.conf.js
Changing files in the `lib/core` directories would not auto-run the appropriate tests.
> tests: fix karma auto-run tests for lib/core

- lib/rules/color-contrast-matches.js
In Firefox, a warning is logged when passing an empty string to `document.getElementById`. This changes the color-contrast-matches code so we don't do that anymore for implicit `labels`.
Closes issue: #2729
> fix(color-contrast-matches): do not pass empty string to getElementById

- lib/core/base/virtual-node/abstract-virtual-node.js
- lib/core/base/virtual-node/serial-virtual-node.js
- lib/core/base/virtual-node/virtual-node.js
- lib/core/utils/get-node-attributes.js
- test/core/base/virtual-node/abstract-virtual-node.js
- test/core/base/virtual-node/serial-virtual-node.js
- test/core/base/virtual-node/virtual-node.js
The `getNodeAttributes` function does not support virtual nodes. Deprecating `getNodeAttributes` in favor of a property on the virtual node that returns an array of attribute names. From the list of names we can call `vNode.attr(name)` to get the value.
Part of issue #2734
> feat(virtual-node): add attrNames property which returns list of attribute names

- lib/checks/keyboard/page-has-heading-one.json
- lib/checks/navigation/header-present.json
- lib/core/utils/css-parser.js
- lib/core/utils/matches.js
- lib/rules/color-contrast-matches.js
- lib/rules/role-img-alt.json
- test/core/utils/matches.js
Been wanting to do this for awhile now so decided to take some time to do it. We can now support the Selectors Level 4 [:is pseudo selector](https://drafts.csswg.org/selectors-4/#matches) (which allows us to simplify some heading selecting) and allows [:not to support more than one selector](https://drafts.csswg.org/selectors-4/#negation), which also helps us shorten and simplify selectors.
Since we use `utils/matches` for everything and we don't go through the DOM selector API, we don't have to worry about browser support since we match everything virtually.
> feat(utils/matches): support selectors level 4 :not and :is

- locales/de.json
Maybe requires proofreading here & there.
> feat(locale): missing translations for DE

- lib/core/core.js
- lib/core/public/run-rules.js
- lib/core/public/setup.js
- lib/core/public/teardown.js
- test/core/public/setup.js
- test/core/public/teardown.js
New functions for setup up and teardown of axe-core internal data `axe._tree` and caches. As we're returning the tree now that is created, we are deprecating `axe._tree` in favor of the return from `axe.setup`
```js
const rootNode = axe.setup();
// use rootNode instead of axe._tree
```
Closes issue: #2570
> feat(setup/teardown): add functions to setup and teardown axe-core internal data, deprecate axe._tree

- README.md
One of the most common questions people have is what rules axe-core has, and how they map to WCAG. I hope that by being more explicit in the readme, and putting this section higher up we can limit how often this question is asked.
> docs: reorganise the readme

- doc/rule-development.md
I was just reading the docs for writing custom rules & noticed an inconsistency in the check properties table
> docs: consistent dot notation in rule-development docs

- test/integration/virtual-rules/tabindex.js
Tabindex rule can already run virtual, just adding tests.
Part of issue: #2734
> tests: add virtual-rules test for tabindex

- test/commons/text/subtree-text.js
- test/core/base/audit.js
- test/core/utils/preload.js
- test/testutils.js
Use the new `axe.teardown` method after every test. I'm sure there's plenty of places in our test that we can replace `axe._tree` with the new setup function. Will open a separate PR for that.
> tests: teardown after every test

- lib/core/public/teardown.js
- test/commons/aria/arialabelledby-text.js
- test/commons/dom/find-elms-in-context.js
- test/commons/dom/get-tabbable-elements.js
- test/commons/dom/is-modal-open.js
- test/commons/dom/is-visible.js
- test/commons/text/is-icon-ligature.js
- test/core/public/teardown.js
- test/integration/full/contrast/code-highlighting.js
- test/rule-matches/aria-hidden-focus-matches.js
- test/testutils.js
Wanted to start updating the tests to stop using `axe._tree` everywhere and use the new `axe.setup` method, starting by updating the testUtils code. However this was a bit of a rabbit hole as to remove `axe._tree` I needed the root node returned by `axe._setup` which was done in `fixtureSetup`. 
However, updating `fixtureSetup` cause code that relied on it returning the fixture element to stop working, so had to update those tests to not use fixture from `fixtureSetup` (most of the time they just needed to use `queryFixture` instead).
I also found that code would use `fixtureSetup` multiple times when really what it wanted was to setup the fixture, do some shadow work, then setup the tree. To resolve these issues I created a new function to just inject code into the fixture without …
> tests: use new axe.setup method

- build/tasks/validate.js
- lib/rules/accesskeys.json
- lib/rules/aria-allowed-role.json
- lib/rules/aria-dialog-name.json
- lib/rules/aria-treeitem-name.json
- lib/rules/empty-heading.json
- lib/rules/form-field-multiple-labels.json
- lib/rules/frame-tested.json
- lib/rules/frame-title-unique.json
- lib/rules/landmark-banner-is-top-level.json
- lib/rules/landmark-complementary-is-top-level.json
- lib/rules/landmark-contentinfo-is-top-level.json
- lib/rules/landmark-main-is-top-level.json
- lib/rules/landmark-no-duplicate-banner.json
- lib/rules/landmark-no-duplicate-contentinfo.json
- lib/rules/landmark-no-duplicate-main.json
- lib/rules/landmark-one-main.json
- lib/rules/landmark-unique.json
- lib/rules/meta-viewport.json
- lib/rules/page-has-heading-one.json
- lib/rules/region.json
- lib/rules/scrollable-region-focusable.json
- lib/rules/table-fake-caption.json
Ensure that best practices never use the word "must" in its description / help text, and that other rules don't use the word "should".
Closes issue: #1491
> fix(metadata): consistent use of 'must' and 'should'

- lib/core/utils/process-message.js
- test/core/utils/process-message.js
Sometimes "undefined" can get into the data object. Especially "messageKey" can be undefined at times. This PR does two things:
1. It prevents "undefined" from ever showing in the message.
2. It ensures that buggy implementations of string.replace() always get a string passed as its second argument. The later one caused issues on a customer website.
> fix: avoid 'undefined' showing in check messages

- lib/core/base/context.js
- lib/core/utils/collect-results-from-frames.js
- test/checks/aria/aria-prohibited-attr.js
- test/core/base/context.js
This is a small portion from #2762 that I'm hoping we can isolate to see if it's the thing causing ie11 to fail the frame-title stuff.
> chore: add parent frame context info

- axe.d.ts
was missed in the 4.1.2 release
Closes #2793
> fix(types): Add noHtml option

- README.md
We dropped support for IE9 and 10 ages ago. We missed this change in our readme it seems though.
> docs(readme): remove outdated IE support info

- lib/core/utils/dq-element.js
- lib/core/utils/filter-html-attrs.js
- lib/core/utils/index.js
- test/core/utils/filter-html-attrs.js
Remove unwanted attributes from source string. Will add all the audit code around it in another pr so this one doesn't get too big.
For the record; this does add a small feature, but it is a feature necessary to address a security fix that will need to be applied to all supported minor versions of axe-core. We are therefor tagging this as a "fix" instead of a "feat".
> fix(utils): remove attributes from source string

- .circleci/config.yml
- package-lock.json
Needed latest version of chromedriver. However, just updating the `packge-lock.json` file didn't work as we checksum the `package.json` file. This also meant security updates that just modify the package-lock file do not cause our builds to use the latest versions.
Fixed by checksuming the package-lock file. Also removed testing examples in Windows as it was breaking but we already do that in the unix path. We had to [do that for `master` as well](https://github.com/dequelabs/axe-core/pull/2826/commits/6216e7a47f058654583df31c1f35da1cbbfe7e5e).
> ci: fix tests

- doc/examples/jest_react/README.md
According to `doc/examples/jest_react/package.json`, as well as terminal output, the `npm test` script runs **Jest**, not Jasmine within the scope of the `doc/examples/jest_react` directory. The `doc/examples/jest_react/README.md` has been updated to accurately describe this script event.
>  docs(examples/jest_react): fix typo referring to Jasmine 

- lib/core/utils/uuid.js
https://github.com/dequelabs/axe-core/issues/2840#issuecomment-800588057
This PR updates [a line added in the recent 4.1.3 release](https://github.com/dequelabs/axe-core/pull/2826/files#diff-fb259cc117394538f4c068d26b0e2bc427ffc8b8d4d5f8eeb58f4783b7b35891R27). Webpack is throwing a warning when this library is included in a bundle, pointed at the given line.
I believe what's happening here is that Webpack sees the word "require", but doesn't understand that it's not being used to actually "require" something. Webpack doesn't know what to do with it, so it throws a warning.
The line is already wrapped in a try, so it should be fine to just drop the `&& require` in the condition. If `const nodeCrypto = require('crypto')` fails, the error will get caught and we can continue on.
Closes issue: …
> fix(utils): fix warning thrown by Webpack

- build/configure.js
> fix: properly translate checks when building axe.js using --lang

- lib/core/utils/respondable/assert-window.js
- test/core/utils/respondable.js
Instead of checking window.frames, check frame.parent. Checked the HTML specs, apparently the spec authors thought this makes sense: https://github.com/WICG/webcomponents/issues/145
Closes issue: #2835
> fix(respondable): work on iframes in shadow DOM

- lib/checks/aria/valid-scrollable-semantics-evaluate.js
- lib/checks/aria/valid-scrollable-semantics.json
- test/checks/aria/valid-scrollable-semantics.js
- test/integration/rules/focus-order-semantics/focus-order-semantics.html
- test/integration/rules/focus-order-semantics/focus-order-semantics.json
Added option to `valid-scrollable-semaantics` to accept a list of roles to pass.
Closes #2813
> fix(focus-order-semantics): allow role=tooltip to pass

- .github/workflows/sync-master-develop.yml
This PR template is no longer relevant here.
> ci(sync-branches): Do not include PR template

- axe.d.ts
> fix(types): make `evaluate` check optional

- lib/core/utils/get-standards.js
- lib/core/utils/index.js
- test/core/utils/get-standards.js
Should have made this info available before. Not sure why we overlooked that.
Closes issue #2889
> fix(getStandards): Read standards from utils

- doc/check-options.md
- lib/checks/aria/aria-required-parent-evaluate.js
- lib/checks/aria/aria-required-parent.json
- lib/standards/aria-roles.js
- test/checks/aria/required-parent.js
- test/integration/rules/aria-required-parent/aria-required-parent.html
- test/integration/rules/aria-required-parent/aria-required-parent.json
- test/integration/rules/preprocessor.js
Related to #2897. 
Need to look into menuitem before we merge this. `menuitem > group > menuitem` doesn't work nearly as well as treeitem and listitem seem to.
> fix(required-parent): Allow *item > group > *item nesting

- lib/commons/text/subtree-text.js
- lib/standards/html-elms.js
- test/commons/text/accessible-text.js
This regression was introduced in [the commit to replace phrasing elements](https://github.com/dequelabs/axe-core/commit/6aab97f782304d3c43379d6f234673cbad6c0cdd), that replaced a hard-coded list of elements with a call to `getElementsByContentType('phrasing')`. 
In the hardcoded array, there are 44 elements that make up the `phrasingElements` array. In the new code using the function, there are 54 elements that are now considered phrasing elements. If the virtual node is a phrasing element as defined in that array, the new content does not get spaces added around it when appending to the virtual name. 
With this in mind, I think it's possible other regressions/behavior changes were caused by that commit but not caught by tests. I'm not sure what the correct behavior is - possibly to only …
> fix(accessible name) Fix regression in accessible name computation

- lib/commons/standards/implicit-html-roles.js
- test/commons/aria/implicit-role.js
Have `<input type="password" aria-label="password">` pass aria-allowed-attr.
Related issue: #2926 -  **does not close it**.
> fix: treat input with no role as textbox

- build/cherry-pick.js
Ran into a small problem with the [latest release](https://github.com/dequelabs/axe-core/pull/2946) when I tried to run the cherry-pick script. Seems that because one of the PRs was not squashed, we got a lot of commits without a `subject` which broke when the script tried to use `subject.startsWith`.
> chore: fix cherry-pick script

- lib/checks/navigation/heading-order-after.js
Noticed a small bug when testing out a newer version of @axe-core/react (we were on a pretty old version of react-axe), we have a case where a heading gets removed during an animation and it seems that heading-order-after is called with a stale result such that when trying to find it's index in the heading order it can't be found and we see a error in the console like `TypeError: Cannot read property 'level' of undefined`. This is a simple naive fix to not use the index if it is -1, but I'm happy to try a different strategy if somebody with more context has a better one!
Closes issue:
`TypeError: Cannot read property 'level' of undefined` when @axe-core/react runs axe-core against a rapidly updating heading structure
> FIX: JS error in @axe-core/react caused by stale reference to heading

- lib/commons/aria/lookup-table.js
- lib/standards/aria-roles.js
- test/integration/rules/aria-allowed-attr/passes.html
- test/integration/rules/aria-allowed-attr/passes.json
Adds aria-posinset and aria-setsize to the allowed aria attributes for row elements, in accordance with the [treegrid examples](https://www.w3.org/TR/wai-aria-practices-1.1/examples/treegrid/treegrid-1.html). 
See a live test case [on glitch](https://aria-treegrid-example.glitch.me/), which runs a local copy of axe that's been built with these changes. 
When I run this locally, the test I added isn't getting picked up and I'm not sure why - might need to pair on that. 
Closes #2720
> fix(aria-allowed-attr): allow aria-posinset and aria-setsize on row elements for treegrids

- lib/checks/mobile/meta-viewport.json
- lib/rules/meta-viewport-large.json
- lib/rules/meta-viewport.json
- test/integration/rules/meta-viewport/frames/iframe-with-zooming-disabled.html
- test/integration/rules/meta-viewport/meta-viewport-pass3.html
- test/integration/rules/meta-viewport/meta-viewport-pass3.json
Adds a matcher to the meta-viewport rules so that only the top-level/initiator page is checked to see if zooming and scaling is available appropriately.
Closes #2210
> fix(meta-viewport) Don't check zooming/scaling ability in iframe-embedded pages

- lib/checks/mobile/meta-viewport-scale-evaluate.js
- test/checks/mobile/meta-viewport-scale.js
- test/integration/virtual-rules/meta-viewport.js
Check if the user-scalable attribute of the viewport meta is between -1 & 1 to be able to zoom.
In addition to check if the`user-scalable` attribute of the viewport meta is set to `no` we need to test if it's in between -1 & 1.
On iOS devices when `user-scalable` is set to `0` you can't zoom.
Related: 
-  [CCWG specs](https://drafts.csswg.org/css-device-adapt/#user-scalable)
- [This google lighthouse discussion](https://github.com/GoogleChrome/lighthouse/discussions/12448)
> fix(meta-viewport): test that a user-scalable number does not prevent zoom

- package.json
I believe this was causing our changelogs to always be incorrect and require manual editing. When we run `standard-version`, it automatically creates a tag for the next version. However that tag is never pushed to the remote and we instead have our CI script create a tag for us after the PR has been merged. This causes the tag on the local machine to be out-of-sync with the tag in the remote.
By skipping the tagging step of standard-version and forcing the release script to fetch all tags before creating a release, this should allow standard-version to find the correct tagged commit and create the changelog properly.
> chore: don't tag releases

- doc/standards-object.md
- lib/checks/aria/aria-prohibited-attr-evaluate.js
- lib/checks/aria/aria-prohibited-attr.json
- lib/commons/aria/get-role.js
- lib/commons/aria/implicit-role.js
- lib/commons/aria/index.js
- lib/core/base/metadata-function-map.js
- lib/rules/has-implicit-chromium-role-matches.js
- lib/rules/presentation-role-conflict-matches.js
- lib/rules/presentation-role-conflict.json
- lib/standards/html-elms.js
- test/checks/aria/aria-prohibited-attr.js
- test/commons/aria/implicit-role.js
- test/integration/rules/presentation-role-conflict/presentation-role-conflict.html
- test/integration/rules/presentation-role-conflict/presentation-role-conflict.json
- test/rule-matches/has-implicit-chromium-role-matches.js
- test/rule-matches/presentation-role-conflict-matches.js
Adds a matcher to the presentation-role-conflict rule so that only elements that have an implicit role that could potentially conflict with an explicit role should be tested against the rule.
Since `div`s don't have an implicit role and thus should not be matched by the rule, two of the passing tests had to be removed.
Closes issue: #2859
> fix(2859) presentation role conflict

- lib/checks/forms/autocomplete-appropriate.json
- lib/rules/autocomplete-valid.json
- test/act-mapping/autocomplete-valid.json
- test/integration/rules/autocomplete-valid/autocomplete-valid.html
- test/integration/rules/autocomplete-valid/autocomplete-valid.json
- test/integration/virtual-rules/autocomplete-valid.js
Deprecates autocomplete-appropriate
Closes issue: #2912
> feat: deprecate autocomplete appropriate check

- build/cherry-pick.js
If a commit message used the word "commit" then it threw off the script, so now it will use a regex that looks ahead to match a commit hash for the split.
> chore(cherry-pick): account for the word commit in commit message

- .github/workflows/sync-master-develop.yml
Rather than explicitly using `v1.0.0`, we'll just use `v1`, which contains many bug fixes.
> ci: Fix sync branches workflow

- lib/checks/color/color-contrast-evaluate.js
- test/integration/full/incomplete/color-contrast.html
We should return elements as Needs Review/incomplete if there is a pseudo element on the element, not just if any of the element's parents have pseudo elements. This PR makes that the case. 
Closes issue: #2966
> fix(color-contrast): check for pseudo elements on element itself, not just parents

- .circleci/config.yml
Use beta branch instead of canary branch as Chrome Canary doesn't really exist for linux. This still allow us to test what's coming in Chrome a 4-6 weeks ahead of it shipping to the stable branch. You can see this working here https://app.circleci.com/pipelines/github/dequelabs/axe-core/2285/workflows/99972573-a9a8-459c-9311-31bf54ac409b/jobs/31628 (I ran nighty as part of the build so we could see it work).
Closes issue: #2967
> ci: fix chrome nightly test

- lib/core/utils/publish-metadata.js
- test/core/utils/publish-metadata.js
- test/playground.html
Use the failure message from a check if a rule sets `reviewOnFail: true`.
Closes issue: #2956
> fix(publish-metadata): use fail message for rules with reviewOnFail:true

- lib/commons/dom/is-visible.js
- test/commons/dom/is-visible.js
The minimum CSS that makes the element from the example visually hidden is a combination of: 
```css
overflow: hidden;
position: absolute;
height: 1px;
```
So if the user is doing that, they are probably trying to hide the element visually and axe-core should recognize that.
Note that the repro case will not fail in Firefox even without this code. 
Closes #2962
> fix(color-contrast): add special case for new sr-only technique

- Gruntfile.js
- README.md
- build/tasks/aria-supported.js
Most of the code for this was already in place; only the aria-supported task was failing when you tried to enter multiple languages to build for. It doesn't seem like that task actually does anything different depending on the language, so this code uses the first language of the languages that were entered (if any) to find the right axe.**.js file to use to generate aria-supported.md. 
Closes issue #2714
> feat: Support multiple languages at once in builds

- axe.d.ts
- doc/frame-messenger.md
- lib/core/utils/frame-messenger/channel-store.js
Processing some feedback from @dbjorge. Thanks for the thorough review.
> docs(frameMessenger): clarify advanced use cases

- axe.d.ts
- doc/API.md
- lib/core/base/audit.js
- test/core/base/audit.js
Allows you to do `axe.run({runOnly: 'specialRule'})`
Closes issue: #3003
> feat(options): accept a string for options.runOnly

- doc/API.md
The docs implied that `axe.run` could change rules or check metadata (like passing a check option) when it doesn't. Changed it to not imply that.
> docs: clarify axe.run options paramter does not modify rules or checks

- package-lock.json
- package.json
npm v7 causes a multitude of problems, namely that we can't run `npm ci` for the release script since it uses ssh protocol for all dependencies to read from it, which fails if you don't have ssh permissions.
```terminal
npm ci 
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/act-rules/act-rules.github.io.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
> chore: downgrade npm to v6 and regenerate package-lock

- lib/checks/color/color-contrast-evaluate.js
- test/checks/color/color-contrast.js
Makes it so thin shadows must have a nonzero ratio in order to be counted as something the background or foreground will get compared against. Builds off the work in PR #3001, which includes text shadows as part of the foreground color if blur is 0 and offset is 0.
Closes issue: #2930
> fix(color-contrast) Zero size text shadow should not be included as background color

- locales/pl.json
1. minor correction
2. add new constants into pl.json
> chore(i18n): Update pl.json

- lib/commons/text/subtree-text.js
- lib/standards/html-elms.js
- test/checks/shared/has-visible-text.js
- test/commons/standards/get-elements-by-content-type.js
- test/commons/text/subtree-text.js
Content inside embedded elements like `video`, `canvas`, `object`, etc. should be ignored in computing the accessible name.
Closes  issue #3017
> fix(accText): ignore text in embedded content elements

- lib/core/base/audit.js
Minor tweak to the jsdoc comment for `Audit`'s `run` method in /lib/core/base/audit.js
Closes: #2795
> docs(audit): add reject param for audit.run

- lib/checks/aria/fallbackrole-evaluate.js
- lib/checks/aria/fallbackrole.json
- test/checks/aria/fallbackrole.js
> fix(aria-roles): Mark as needs review if both none and presentation are used on element with no implicit role

- lib/checks/color/color-contrast-evaluate.js
- lib/checks/color/color-contrast.json
- test/checks/color/color-contrast.js
Builds off the other color contrast work that's been happening, so base of the PR is not `develop`
Closes issue: #2925
> Use more specific failure messages for color contrast failures

- lib/checks/navigation/heading-order-evaluate.js
- test/checks/navigation/heading-order.js
Allow aria-level on hn elements to override the semantic level of the element. 
Closes issue: #2971
> fix(heading-order): use aria-level on headings in addition to role=header elements

- lib/commons/dom/is-visible.js
- test/commons/dom/is-visible.js
Clip is only applied on absolutely positioned elements (`position: fixed` or `position: absolute`), so if an element is using `clip` but doesn't have that positioning, it will still be visible.
Closes issue: #3037
> fix(color-contrast-matches): only absolutely positioned elements using clip should be not visible

- test/integration/full/aria-hidden-body/fail.html
- test/integration/full/aria-hidden-body/fail.js
- test/integration/full/aria-hidden-body/pass.html
- test/integration/full/aria-hidden-body/pass.js
- test/integration/full/bypass/aria-header.html
- test/integration/full/bypass/fail.html
- test/integration/full/bypass/fail.js
- test/integration/full/bypass/header1.html
- test/integration/full/bypass/header2.html
- test/integration/full/bypass/pass-tests.js
- test/integration/full/bypass/region.html
- test/integration/full/bypass/skip-link.html
Adds wait for iframes to be ready to all the places that didn't have it in the full integration tests, with the exception of preloadcssom - that test file is doing some timeout stuff already and I'm not sure if waiting for iframes is appropriate there.
Closes issue: #3048
> (tech-debt): wait for iframes to be ready in tests

- lib/core/utils/index.js
- lib/core/utils/shadow-select.js
- test/core/utils/shadow-select.js
Adds axe.utils.shadowSelect to select elements within a shadow tree. This method was created to be used along side `axe.utils.getFrameContexts()`.
> fix(utils): unify selecting nodes in shadow tree with shadowSelect()

- doc/API.md
- doc/frame-messenger.md
- doc/run-partial.md
Describe how to use `axe.runPartial()` and `axe.finishRun()` in browser drivers.
Closes #3059
> docs(runPartial): recommendations on runPartial / finishRun.

- lib/commons/dom/focus-disabled.js
- test/checks/keyboard/focusable-disabled.js
> fix(aria-hidden-focusable): disabled aria-hidden fieldset should not have focusable children

- lib/core/base/context.js
- lib/core/utils/clone.js
- test/core/base/context.js
- test/core/utils/get-frame-contexts.js
getFrameContexts was mutating its input because Context mutates its input. This change makes it so Context no longer mutates its input. 
Closes issue: #3045
> fix(core): stop mutating Context's input

- lib/checks/aria/aria-required-parent-evaluate.js
- test/checks/aria/required-parent.js
If group is present and also a required parent, we should not report that `group` is missing from the required parents. 
Closes issue: #2904
> fix(aria-required-parent): Filter out group from required parent roles if group is present

- lib/checks/aria/aria-required-attr-evaluate.js
- test/checks/aria/aria-required-attr.js
Closes issue #3090
The diff's a bit off as it thinks I changed contents of the first test instead of adding one above what was there.
> fix(aria-required-attr): only require aria-controls if aria-expanded=true

- lib/core/public/finish-run.js
- lib/core/public/run/normalize-run-params.js
- test/core/public/finish-run.js
- test/core/public/run-partial.js
- test/core/public/run.js
- test/testutils.js
This fixes an issue where not passing an `options` object to `axe.finishRun` would result in axe not using the `v1` reporter even though the [v1 reporter is the default for a axe.run](https://github.com/dequelabs/axe-core/blob/develop/lib/core/public/run/normalize-run-params.js#L39). This caused the results of the `axe.finishRun` to not include `failureSummary`.
```js
const results = await axe.runPartial()
await axe.finishRun([results])  // v1 reporter not used
```
The better question would be why we [set the v2 reporter as default](https://github.com/dequelabs/axe-core/blob/develop/lib/core/core.js#L95) when axe.run uses the v1 by default.
> fix(run,finishRun): don't mutate options, set default reporter to v1

- build/tasks/aria-supported.js
Currently nothing is unsupported in our standards object though, but I tested it with `aria-busy` and it worked.
Closes issue: #3081
> chore: use standards in aria-supported script

- lib/standards/html-elms.js
- test/commons/aria/is-aria-role-allowed-on-element.js
Replaces #3117 due to CircleCI problem of not running tests for outside contributors.
Closes issue: #3082
> fix(aria-allowed-role): Update allowed roles based on ARIA spec updates

- lib/checks/navigation/internal-link-present-evaluate.js
- test/checks/navigation/internal-link-present.js
Make `internal-link-present-evaluate` work with virtualNode rather than actualNode.
Closes issue #2466
> refactor(checks/navigation): improve `internal-link-present-evaluate`

- lib/commons/text/form-control-value.js
- lib/core/base/virtual-node/virtual-node.js
- test/commons/text/form-control-value.js
- test/core/base/virtual-node/virtual-node.js
`nativeSelectValue` doesn't return the selected value after manual selection. This PR fixes that by using the [`selected`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-selected) on `<option>` to get the up-to-date value.
> fix(nativeSelectValue): update selected value on change

- axe.d.ts
As per the spec, the context parameter can be passed one of the following:
> A `NodeList` such as returned by `document.querySelectorAll`.
Source: https://www.deque.com/axe/core-documentation/api-documentation/#context-parameter
> fix(typescript): allow passing a NodeList to ElementContext

- .circleci/config.yml
- lib/commons/dom/is-visible.js
- package.json
- test/test-virtual-rules.js
Allows `isVisible` to be run if `window.Node` is not defined.
> fix(is-visible): do not error if window.Node does not exist

- lib/commons/dom/is-visible.js
- test/commons/dom/is-visible.js
- test/integration/rules/color-contrast/color-contrast.html
Should fix the particular case brought up by the issue. I tested the other sites users said the problem occurred on and I couldn't get it to throw an error on any of them. Even the current page of the original issue has been updated and no longer throws the error, but luckily I left a note on what the issue was so could reproduce it.
Closes issue: #3171, #2674
> fix(color-contrast): account for 0 width scroll regions with children

- lib/core/utils/get-selector.js
- test/core/utils/get-selector.js
When trying to get the selector for the images on https://github.com/dequelabs/axe-core/issues/3109, the end result of the `getAttributeNameValue` would end up being URI encoded and token escaped. 
What that means is that instead of returning `[href$="1 Seater"]` (a valid CSS attribute selector) it would first URI encode it, which would turn into `[href$="1%20Seater"]`, and then token escape it which would try to prevent the first character from being a number (an invalid CSS token) and escape it, resulting in `[href$="\31 %20Seater"]`. This selector would not find anything in the document so [`:root` would be returned by default](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/get-selector.js#L378-L384).
Since [attribute selectors can be …
> fix(get-selector): do not URL encode or token escape attribute selectors

- .circleci/config.yml
Also updated the image syntax for our normal runs.
See https://circleci.com/developer/images/image/cimg/node
> ci: use lts-browsers for nightly tests

- lib/checks/keyboard/no-focusable-content-evaluate.js
- lib/core/utils/check-helper.js
- test/checks/keyboard/no-focusable-content.js
- test/core/utils/check-helper.js
Closes issue: https://github.com/dequelabs/axe-core/issues/3258
> fix(nested-interactive): add focusable descendants as related nodes

- lib/core/utils/frame-messenger/message-handler.js
- lib/core/utils/frame-messenger/message-parser.js
- test/core/utils/respondable.js
axe-core crashes if another process sends a `window.postMessage` with
data equals to `null`.
In the previous version, because `null` has a type of `'object'`, it
crashed when trying to access the `channelId`.
This change detects first if the data is not `null`.
> fix(respondable): avoid crashes if the data in `window.postMessage` is `null`

- axe.d.ts
- doc/run-partial.md
- lib/core/utils/get-frame-contexts.js
- test/core/utils/get-frame-contexts.js
Accept the options object for axe.utils.getFrameContexts. When passed `iframe:false`, it always returns an empty array. I.e. frames should not be tested.
Closes issue:  #3242
> fix(getFrameContext): option.iframe=false always returns an empty array

- axe.d.ts
- doc/API.md
- lib/core/base/audit.js
- test/core/base/audit.js
Because the `brand` property is no longer in use, it is deprecated as of version 4.4. This makes it unnecessary to configure `branding` using an object, which now only has one property. So along with deprecating the `brand` property, the Branding object is also deprecated. Use a string instead:
```js
// previously
axe.configure({
branding: { application: 'axe-playwright' }
})
// current
axe.configure({ branding: 'axe-playwright' })
```
Closes issue: #2891
> feat(configure): Deprecate branding: Object, use a string instead.

- lib/standards/html-elms.js
- test/commons/aria/is-aria-role-allowed-on-element.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
As per a recent update in ARIA in HTML
Closes issue: #3266
> fix(allowed-role): area without href can have a button or link role

- axe.d.ts
- doc/API.md
- doc/frame-messenger.md
- lib/core/utils/send-command-to-frame.js
- test/core/utils/send-command-to-frame.js
- Document the existence of pingWaitTime
- Have `pingWaitTime: 0` skip the ping step altogether
Closes issue: #3272
> feat(options): make axe.ping configurable with pingWaitTime

- lib/checks/navigation/region-evaluate.js
- test/aria-practices/apg.spec.js
- test/checks/navigation/region.js
Allow buttons as skip menus
Closes issue: #3260
> fix(region): Allow skip menu buttons

- test/act-mapping/scrollable-region-focus.json
Long story short; Chrome 96 came out and turned something that wasn't an issue into a legit accessibility issue. Axe-core caught it right away, and because we can't pin versions of Chrome, we're disabling this test until ACT has accepted and put out the change. This takes at least a weak and I don't want CI broken for a week.
> chore(act): disable act rule until the test is fixed

- lib/core/utils/get-scroll.js
- test/core/utils/get-scroll.js
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.html
Fix a bug where elements with overflow:clip could be considered scrollable.
Closes issue: #3283
> fix(scrollable-region-focusable): treat overflow:clip as hidden

- build/configure.js
- lib/core/reporters/helpers/incomplete-fallback-msg.js
- test/core/reporters/helpers/incomplete-fallback-msg.js
A bug in the build step caused the incomplete fallback message to be an empty object, rather than a string. When an error occurred, rather than failing gracefully this caused infinite recursion. This change prevents that.
Closes issue: #3289
> fix(core): Incomplete fallback message was missing

- lib/checks/lists/listitem-evaluate.js
- test/checks/lists/listitem.js
- test/integration/rules/listitem/listitem.html
- test/integration/rules/listitem/listitem.json
- Allow `<li>` as children of `<menu>`
- Refactor, update to more modern check writing style
Closes issue: #3284
> fix(listitem): allow li as child of menu

- lib/commons/color/get-background-stack.js
- test/checks/color/color-contrast.js
- test/commons/color/get-background-color.js
bgOverlap was not computed correctly. What it was doing is use elementsFromPoint on the top-right pixel of a field. It got the tests to pass, but doing that doesn't actually tell us the difference between an element that overlaps, and a non-text element that simply sits inline with the text of an element. Because axe-core no longer scrolls the page when running color-contrast, our use of elementsFromPoint caused inconsistencies.
The fix here is to check if an element that appears visually on top of the element with text is actually an inline descendant of it. That gets rid of elementsFromPoint, solving the inconsistency problem, and it means we can actually properly tell what elements might overlap, and which ones are in the same flow as the text.
Closes issue: #3309
> fix(color-contrast): inconsistency of bgOverlap message based on scroll

- lib/standards/html-elms.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
A `role=radio` was meant to be an allowance for an `img alt=foo`, but it had mistakenly been left out of the spec.
ARIA in HTML is fixing this oversight, https://github.com/w3c/html-aria/pull/381, so this PR is to match this added allowance.
> adds role=radio to img alt=foo allowances

- lib/commons/aria/get-accessible-refs.js
- test/commons/aria/get-accessible-refs.js
Encountered a site with custom elements which had its own `.children` property. Since this was an easy one to work around, and it completely choked up testing that site it seemed like something worth fixing.
> fix(custom-elms): Don't error on custom Element.children prop

- lib/core/utils/contains.js
- lib/core/utils/select.js
- test/integration/virtual-rules/nested-interactive.js
Testing if deeply nested shadow DOM nodes are in context can be a very slow operation, especially on sites that make extreme use of shadow DOM (think 30+ layers of nested shadow trees). For a very large part, this is because calling  `containsShadowChild` thousands of times recursively is very slow.
This PR avoids calling `isNodeInContext` when it isn't necessary (when there are no excluded nodes), and makes `containsShadowChild` significantly faster by walking down to the root, rather than walking the entire tree.
> perf(gather): Faster shadowDOM testing

- axe.d.ts
- doc/API.md
- typings/axe-core/axe-core-tests.ts
These all work correctly:
```js
const div = document.querySelector('div');
await axe.run({ include: div });
await axe.run({ include: [div] });
await axe.run({ include: doument.querySelectorAll('div') });
```
Closes issue: #3334
> fix(axe.d.ts): allow Node for include/exclude object

- lib/standards/dpub-roles.js
- test/integration/rules/aria-roles/aria-roles.html
> fix(dpub): deprecate doc-endnote rather than doc-endnotes (plural)

- doc/projects.md
docs: change `/docs/projects.md` to include Parcel
Parcel.io (https://parcel.io) now integrates axe-core. Change `/docs/projects.md` to include Parcel
Closes issue: n/a
> docs: change `/docs/projects.md` to include Parcel

- test/core/base/audit.js
`audit.run` expects the context to already have been resolved with vNodes. Passing regular HTML elements breaks the QSA code.
Closes issue: #2436
> tests: fix audit tests include

- test/integration/full/isolated-env/isolated-env.js
Turns out there was a race condition in the isolated-env tests between when the iframe `load` event was triggered and when the script contents to fetch axe and inject it into the page via `eval` would complete. Tests would fail if the script couldn't execute faster than the `load` event.
Fixed that by properly waiting for the post message the script sends in addition to waiting for the nested load function.
Closes issue: #3367
> tests: resolve isolated-env race condition

- locales/ja.json
grunt translate --lang=ja based on the develop branch as of 2021-12-03
Add ja translation for checks/aria-errormessage/fail/hidden
Add ja translation for checks/aria-errormessage/incomplete/idrefs
add ja translation for checks/aria-level/{pass,fail}
Add ja translation for checks/aria-valid-attr-value/incomplete/idrefs
Add ja transation for checks/deprecatedrole/{pass,fail}
Add ja translation for checks/fallbackrole/incomplete
add ja translation for checks/p-as-heading/incomplete
Add ja translation for checks/color-contrast-enhanced/fail/*
Add ja translation for checks/color-contrast/fail/*
Closes issue:
> chore(i18n): update Japanese translation

- lib/standards/html-elms.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
closes #3401
allows `none` and `presentation` role on `<nav>` element.
> fix(html-elms): update role allowances for nav element

- .circleci/config.yml
- package.json
We had the ACT job fail because of an update to one of the rules. This PR makes it so we run tests against a pinned version of ACT. We'll have a nightly job run against the latest ACT rules so we can see if something in ACT broke our implementation.
I haven't looked at what was failing specifically. I'll do that in a separate PR.
> ci(act): Add nightly job to run latest ACT rules

- lib/checks/keyboard/focusable-disabled-evaluate.js
- lib/checks/keyboard/focusable-disabled.json
- lib/checks/keyboard/focusable-not-tabbable-evaluate.js
- lib/checks/keyboard/focusable-not-tabbable.json
- test/act-mapping/aria-hidden-is-focusable.json
- test/checks/keyboard/focusable-disabled.js
- test/checks/keyboard/focusable-not-tabbable.js
Report aria-hidden-focusable as incomplete if all its children have an onfocus event.
This also removes the mapping to ACT, as I think the current interpretation of that rule is too strict (see issue).
Closes issue: #3406
> fix(aria-hidden-focusable): report incomplete with onfocus

- lib/standards/html-elms.js
closes #3417
fix 'addres' to 'address'
> fix(standards): fix address typo in html-elms.js

- lib/rules/aria-hidden-focus.json
The current `help` value does not include the scenario in which `aria-hidden="true"` is on a focusable element. I updated it to include that scenario. Here's the PR, per @WilcoFiers suggestion. Slack thread: https://deque.slack.com/archives/C0LA5E545/p1646762357136919
> fix(aria-hidden-focus): Update rule help & description

- locales/nb-no.json
- locales/no_NB.json
I copied the danish locale (de.json) and translated to Norwegian (the languages are very similar). 
The added locale is the for the main dialect in Norway. The other one, Nynorsk, is often used on websites with high focus on accessibility, so it's a good idea to keep the file naming as proposed rather than just no.json.
> feat(locale): Added Norwegian Bokmål locale

- .circleci/config.yml
Apparently what was going on was that after `npx browser-driver-manager install chromedriver` installed chromedriver 99/100, doing `npm install w3c/aria-practices#main` would __override__ the previously installed chromedriver with the version listed in `package-lock.json`. So the fix was to change the order of installs so that chromedriver was installed as the last thing.
Also fixed the nightly act running apg instead.
Here's the build showing nightly works now https://app.circleci.com/pipelines/github/dequelabs/axe-core/3537/workflows/1685f851-de20-40d5-b955-bf36ab194c51
> ci: fix nightly build

- lib/rules/empty-table-header.json
- test/aria-practices/apg.spec.js
- test/integration/rules/empty-table-header/empty-table-header.html
- test/integration/rules/empty-table-header/empty-table-header.json
References #3404
Updated empty table headers rule to be best practice rather than a WCAG failure.
Closes issue:
> feat(empty-table-headers): rule is now best-practice and fails instead of incompletes

- axe.d.ts
- doc/API.md
- lib/core/base/rule.js
- lib/core/public/get-rules.js
- test/core/base/rule.js
- test/core/public/get-rules.js
Return `actIds` from `axe.getRules()`.
Closes issue #3469
> feat(getRules): return actIds when set

- lib/checks/keyboard/frame-focusable-content-evaluate.js
- lib/commons/dom/is-focusable.js
- test/checks/keyboard/frame-focusable-content.js
- test/integration/rules/frame-focusable-content/frame-focusable-content.html
- test/integration/rules/frame-focusable-content/frame-focusable-content.json
- test/integration/rules/frame-focusable-content/frames/focusable-negative-tabindex.html
- test/playground.html
Updated the `isFocusable` code since we were looking at it to 1) default export at top and 2) update the description as we spent a bit of time trying to figure out why an element with tabindex=-1 was still considered focusable.
Also, having the `frame-focusable-content` test have all the elements wrapped in `buttons` was strange so changed them to `divs`
Closes issue: #3466
> fix(frame-focusable-content): don't fail for elements with negative tabindex

- package-lock.json
[Npm v7 introduced a "feature"](https://github.com/npm/cli/issues/2610) that changed any `github:` urls to be `ssh+git` urls, which broke CI as we didn't have ssh read permissions to public 3rd party repos. This caused us to keep our npm versions at v6. Npm v8 doesn't fix the problem, but it seems CI or github fixed the issues on their end as the CI install process now installs without issues, so we can now update to latest npm version.
> chore: update latest npm

- axe.d.ts
…meter reviewOnFail
Updates the type definition file to add reviewOnFail to Rule type. ReviewOnFail is a valid configuration parameter that can be passed into the configure command in an array of rules.
Example:
`axe.configure({
rules: [
{
id: 'new-rule',
reviewOnFail: true
// ...
}
]
})`
Closes issue:
No issue attached.
> fix(axe.d.ts): updates type definition for Rule to add reviewOnFail

- doc/check-options.md
- lib/checks/navigation/meta-refresh-evaluate.js
- lib/checks/navigation/meta-refresh.json
- lib/rules/meta-refresh.json
- test/checks/navigation/meta-refresh.js
- test/integration/full/meta-refresh/meta-refresh-fail.js
- test/integration/full/meta-refresh/meta-refresh-fail1.html
- test/integration/full/meta-refresh/meta-refresh-inapplicable.js
- test/integration/full/meta-refresh/meta-refresh-inapplicable1.html
- test/integration/full/meta-refresh/meta-refresh-inapplicable2.html
- test/integration/full/meta-refresh/meta-refresh-pass.js
- test/integration/full/meta-refresh/meta-refresh-pass1.html
- test/integration/full/meta-refresh/meta-refresh-pass2.html
- test/integration/virtual-rules/meta-refresh.js
1. Ensure that redirects after 20 hours are passed
2. Improve the accuracy of the redirect number parsing
3. Add options for minDelay and maxDelay, to make the check configurable
4. Make the rule inapplicable when there's no content attribute
5. Add more integration tests
Closes issue: #3496
> fix(meta-refresh): Add WCAG's 20-hour exception

- Gruntfile.js
- README.md
- locales/_template.json
Adding a template for localisations, this should hopefully make reviewing a little easier.
> chore: add locale/_template.json

- lib/rules/not-html-matches.js
As of https://github.com/dequelabs/axe-core/pull/3523 we no longer need the not-html-matches check. This just marks the matches method as deprecated.
> feat(matches): deprecate not-html-matches, use :not(html) instead

- test/integration/api/external/index.js
Trying to reduce the chance of a timeout in IE11. Running the `axe.utils.validLangs` multiple times may be slow due to converting the tri back into a string array, so saved the variable off. Also only called it once more with an invalid value rather than twice.
Will restart multiple times to see if this triggers the failure anymore.
Part of #3561
> ci: fix flakey validLang test

- test/integration/full/isolated-env/isolated-env.html
- test/integration/full/isolated-env/isolated-env.js
- test/testutils.js
The `awaitNestedLoad` function never took a fail callback, so if the queue for whatever reason failed, it would go to the default fail function which was just to log the error to console. Since we don't see console logs when we run the full tests, and since the fail case was never reported back to the promise, our tests could easily timeout with no clue as to why.
Added a fail callback and made sure each promise in the isolated-env code (which [had a timeout](https://app.circleci.com/pipelines/github/dequelabs/axe-core/3855/workflows/8c57f2be-1832-4a49-b963-dc0f15416242/jobs/45110)) had a `catch` clause that reported the error back Mocha. Hopefully if the code does fail now we'll get a helpful error rather than a test timeout.
Part of #3561
> tests: support fail case for testutils.awaitNestedLoad

- test/core/public/run.js
Mocha is already set with a timeout of 4s, setting the timeout to be 1s increases the chance of a failed test due to a frame taking slightly longer to load. Removed the timeout to just use the default one. 
I looked at the history and the timeout was added in https://github.com/dequelabs/axe-core/pull/2816 but there's no comment as to why the timeout was added (or why it was so short).
Part of #3561
> ci: remove timeout from axe.run tests

- test/checks/navigation/heading-order.js
- test/commons/text/form-control-value.js
- test/commons/text/native-text-alternative.js
- test/testutils.js
- Adds an assert to the `axe.testUtils.queryFixture()` to guide developers in usage of the fixture helper.
- Refactor to help VS Code pick up correct signatures
- Add JSDoc
- Whitespace fixes
> chore: add target assert to queryFixture

- lib/core/reporters/na.js
na reporter was deprecated in [3.3.0](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md#330-2019-07-08) but we forgot to add the jsDoc `@deprecated` comment so we missed removing it in 4.0 as we planned. Just adding the doc comment in so we don't forget to remove it in 5.0.
> chore: add deprecated jsdoc to na reporter

- README.md
Updated the typo found in the documentation under the section Localization.
> docs: Typographical Error

- .github/workflows/label-extension-linter-issues.yml
With the new issue forms, we can now auto-assign opened issues with the `extension` or `linting`  labels based on the Product dropdown. It was difficult to figure out the proper matching of newline characters. 
You can see it working https://github.com/straker/issue-template-tests/issues and https://github.com/straker/issue-template-tests/actions
> chore: create action to auto-label extension and linting issues

- lib/commons/text/accessible-text-virtual.js
- test/integration/virtual-rules/aria-toggle-field-name.js
- test/integration/virtual-rules/button-name.js
Noticed that the `accessible-text-virtual` functions didn't all completely use virtual node and sometimes accessed the `actualNode` just to look at the `nodeType` and call `isVisible`. Updated to just use virtual nodes.
> refactor(accessible-text-virtual): finalize virtualNode

- lib/checks/aria/aria-required-children-evaluate.js
- lib/checks/aria/aria-required-children.json
- lib/standards/aria-roles.js
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
> feat(aria-required-children): fail for children which are not listed as required

- .github/ISSUE_TEMPLATE/possible-bug.yml
Change associated label for id: latest-axe to `Latest Version` instead of `Lastest Version`. If spelling was intentional, feel free to close!
> chore: update typo for possible-bug issue template

- lib/commons/standards/implicit-html-roles.js
- lib/commons/table/get-scope.js
- test/commons/table/get-scope.js
- test/commons/table/is-header.js
- test/integration/virtual-rules/empty-table-header.js
use virtual node
references: #3473
> refactor(empty-table-header): use virtual node

- .github/workflows/update-generated-files.yaml
We have two files that are automatically generated on build: `doc/rule-descriptions.md` and `locales/_template.json`. These files can easily become out-of-sync when a pull request makes changes to a rule or check metadata file. If a metadata file gets suggestions and the suggestions are accepted, the generated files would need to be rebuilt and redployed to the pr. Most of the time this doesn't happen and the changes aren't applied to the generated files. This causes any new builds on local branches to have new changes from develop.
This action will run the build on pushes to develop and make a pr with the built files if there are changes. You can see it working here: https://github.com/straker/issue-template-tests/pull/22. If there are no changes, the action will fail and not create a pr …
> chore: add action to create pr for generated files

- lib/checks/aria/aria-valid-attr-value-evaluate.js
- lib/checks/aria/aria-valid-attr-value.json
- lib/standards/aria-attrs.js
- test/checks/aria/aria-required-attr.js
- test/checks/aria/valid-attr-value.js
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
There is no real difference between an empty ARIA attribute, a null attribute, and not having the attribute at all. Failing empty ARIA attributes therefor seems a little strict. They shouldn't be passed either though, since it is pretty easy to mistakenly assume `<input aria-invalid>` means the input is invalid. Reporting `incomplete` seems more appropriate. This PR makes that change, along with:
- String type attributes, like aria-valuenow are still not allowed empty
- `aria-invalid` is now reported as incomplete when empty, rather than passed
- Extra tests were added to aria-required-attr to ensure empty attributes when required are failed there
Closes issue: #3489
> fix(aria-valid-attr-value): report empty values as incomplete

- lib/rules/presentation-role-conflict-matches.js
This matches method is no longer in used. No need to keep it.
Closes issue: #3591
> feat: deprecate presentation-role-conflict-matches

- build/sri-update.js
Axe-core generated an src-history.json file in its root. This keeps hashes of previous versions of axe-core, so that tool loading an older version of axe-core from an unknown source can verify its authenticity before running it. This feature was primarily used by browser extensions, however as of Chrome's manifest v3 change it is no longer permitted to run remote scripts in browser extensions anyway. We therefore no longer need to generate the sri-history.json file.
Closes issue: #3645
> feat: deprecate sri-history.json file

- doc/projects.md
Webatool is an Web Accessibility Tool for testing application for websites and other HTML-based user interfaces. Designed using on Axe Core Engine
Closes issue:
> Webatool Open Source community Project

- .eslintrc.js
Since axe-core no longer needs to run tests in IE11, we can rely on modern javascript natively supported by browsers.
> chore(eslint): allow es2021 in tests

- lib/checks/keyboard/focusable-disabled-evaluate.js
- lib/checks/keyboard/focusable-not-tabbable-evaluate.js
- test/checks/keyboard/focusable-disabled.js
- test/checks/keyboard/focusable-not-tabbable.js
- test/integration/rules/aria-hidden-focus/aria-hidden-focus.html
- test/integration/rules/aria-hidden-focus/aria-hidden-focus.json
Closes issue: https://github.com/dequelabs/axe-core/issues/3430
> fix(aria-hidden-focus): do not fail for focus trap bumper elements

- Gruntfile.js
In #3631, moving the prettier step out of the Gruntfile and into a `postbuild` script only solved half the problem. Running `npm run develop` would not cause the `build` npm script to run so the `locales/_template` file would still be out-of-sync. 
This change is minimal in order to use what we have already created and still get prettier to run after running `develop`.
> chore: run prettier after develop build

- lib/core/utils/matches.js
- test/core/utils/matches.js
Fixes the issue discovered in #3663 where we couldn't properly match `[attr=""]`
> fix(utils.matches): fix attribute exists selector to match empty attributes

- lib/checks/tables/td-headers-attr-evaluate.js
- lib/rules/table-or-grid-role-matches.js
- lib/rules/td-headers-attr.json
- test/checks/tables/td-headers-attr.js
- test/integration/rules/td-headers-attr/td-headers-attr.html
- test/integration/rules/td-headers-attr/td-headers-attr.json
- test/rule-matches/table-or-grid-role-matches.js
> fix(td-headers-attr): ignore table elements with their role changed

- lib/rules/avoid-inline-spacing.json
- lib/rules/is-visible-matches.js
- lib/rules/is-visible-on-screen-matches.js
- test/rule-matches/is-visible-matches.js
- test/rule-matches/is-visible-on-screen-matches.js
Just copied the tests from `is-visible-matches` to `is-visible-on-screen-matches`.
Part of https://github.com/dequelabs/axe-core/issues/3655
> feat(matches): deprecate is-visible-matches, use is-visible-on-screen-matches

- lib/checks/label/explicit-evaluate.js
- lib/checks/label/implicit-evaluate.js
- test/checks/label/explicit.js
- test/checks/label/implicit.js
- test/checks/shared/aria-labelledby.js
- test/integration/rules/label/label.html
- test/integration/rules/label/label.json
- test/integration/rules/select-name/select-name.html
- test/integration/rules/select-name/select-name.json
Avoid the value of an input / textarea / select element getting picked up as its label.
This problem is specifically with how the checks are running a partial accessible name computation, and were doing it incorrectly. This issue only exists on the implicit-label and explicit-label checks. I added tests to aria-labelledby to prove it didn't have this issue.
Closes issue: #3686
> fix(label): avoid passing labels because of an input[value]

- lib/rules/object-alt.json
- lib/rules/object-is-loaded-matches.js
- test/integration/full/isolated-env/isolated-env.html
- test/integration/rules/object-alt/object-alt.html
- test/integration/virtual-rules/object-alt.js
- test/rule-matches/object-is-loaded-matches.js
Skip objects on the object-alt rule if they either have no data attribute, or if any of their fallback content is visible.
Closes issue: #3656
I was having difficulty getting the ACT tests to pass because the server doesn't correctly map the URLs. I opened a separate PR for that: #3681
> fix(object-alt): ignore unloaded objects

- build/configure.js
- doc/rule-descriptions.md
- lib/rules/target-size.json
- Make sure all WCAG 2.2 rules are disabled
- Separate WCAG 2.2 rules in rule-descriptions.md
Closes issue: #3705
> chore: list wcag22 rules as disabled

- lib/rules/meta-refresh.json
When we made meta-refresh-no-exceptions not test for things covered by meta-refresh, we should have added the No Exceptions ACT rule to meta-refresh, since now the combination of these two axe-core rules are required to test the entirety of the No Exceptions ACT rule.
> chore(meta-refresh): fix mapping to AAA rule

- doc/check-options.md
- lib/checks/lists/invalid-children-evaluate.js
- lib/checks/lists/only-dlitems.json
- lib/checks/lists/only-listitems.json
- lib/rules/no-role-matches.js
- locales/_template.json
- test/checks/lists/only-dlitems.js
- test/checks/lists/only-listitems.js
- test/integration/rules/list/list.json
- test/integration/virtual-rules/definition-list.js
- test/integration/virtual-rules/list.js
- test/rule-matches/no-role-matches.js
Improve on messages reported by the `list` and `definition-list` checks. Since they had so much in common I unified them into a new `invalid-children-evaluate` method. That got me 95% of the way to running their rules on virtual nodes, so I then also updated the matches method to run on virtual. 
This rule gets rid of the (minor) exception on `list`, where if you have `li` elements, where some have a role and others do not, the rule will pass. I don't recall why we put that in, but it doesn't make too much sense to me.
The `only-dlitems-evaluate` and `only-listitems-evaluate` methods need to be deprecated, but this belongs in a separate PR.
Closes issue: #3559
> feat(list/definition-list): only allow required owned roles

- lib/checks/lists/only-dlitems-evaluate.js
- lib/checks/lists/only-listitems-evaluate.js
> feat: Deprecate only-dlitems-evaluate & only-listitems-evaluate methods

- lib/commons/dom/is-hidden-for-everyone.js
- lib/commons/dom/visibility-methods.js
- lib/core/_exposed-for-testing.js
- test/commons/dom/is-hidden-for-everyone.js
- test/commons/dom/visibility-methods.js
- test/integration/rules/color-contrast/color-contrast.html
- test/integration/rules/color-contrast/color-contrast.json
> fix(is-hidden-for-everyone): count elements inside closed details as hidden

- .circleci/config.yml
- test/integration/full/test-webdriver.js
Noticed that our [Chrome integration tests were silently failing](https://app.circleci.com/pipelines/github/dequelabs/axe-core/4426/workflows/9aa9b669-2128-47b7-8e8f-c3adb0f16470/jobs/50608) due to `setDefaultService` not being a function anymore in selenium-webdriver 4.3.1+. Fixed the issue by using [the new way to create drivers](https://stackoverflow.com/questions/72993126/selenium-webdriver-error-chrome-setdefaultservice-is-not-a-function) and also split the firefox and chrome tests while I was at it.
Since we're not running safari or mobile-chrome, I also removed the code logic for those since they won't work with the new way of creating drivers. Will have to add those back in when we re-enable those browsers in separate pr.
Closes issue: #3653
> ci: fix chrome integration tests and split browser tests

- sri-history.json
Had an issue with sri-history.json because we did the release a bit out of order.
> chore: release axe-core 4.5.0 (sri-history corrected)

- .github/workflows/update-generated-files.yaml
Run `npm ci` instead of `npm install` so `package-lock.json` isn't updated during the action. This caused [the action to think there was new changes](https://github.com/dequelabs/axe-core/actions/runs/3299227438/jobs/5442346330#step:4:10) to generated files even though there wasn't, thus failing.
> chore: npm ci for generated files action

- lib/core/utils/preload-cssom.js
- cssom package does not implement StyleSheet.media
Adds a simple `if` to check whether `StyleSheet` has `media`.
Closes #3753
> fix: prevent crash on jsdom when preloading CSSOM

- lib/commons/dom/create-grid.js
- lib/commons/dom/find-nearby-elms.js
- lib/commons/dom/get-rect-stack.js
- lib/commons/dom/get-text-element-stack.js
- lib/commons/math/get-bounding-rect.js
- lib/commons/math/get-rect-center.js
- lib/commons/math/index.js
- lib/commons/math/is-point-in-rect.js
- lib/commons/math/rects-overlap.js
- lib/commons/math/split-rects.js
- test/commons/dom/create-grid.js
- test/commons/dom/find-nearby-elms.js
- test/commons/math/get-bounding-rect.js
- test/commons/math/get-rect-center.js
- test/commons/math/is-point-in-rect.js
- test/integration/full/all-rules/all-rules.html
- test/integration/full/all-rules/all-rules.js
- test/integration/full/all-rules/frames/focusable.html
> fix(create-grid): include elements scrolled out of view in the grid

- package-lock.json
- package.json
- test/commons/color/get-background-color.js
- test/integration/full/contrast/blending.html
Following the steps in the ticket, this fixes the webpack output to not warn of the critical dependency. Seems something about esbuild v0.11+ causes the problem. For now this is a fix to the problem, but I'll investigate further at some later date to see if I can figure out what's going on. 
Closes issue: #3771
> fix: do not warn when using webpack

- lib/core/reporters/helpers/process-aggregate.js
- test/core/reporters/helpers/process-aggregate.js
This PR fixes the reporter throwing an error when the relatedNode is undefined.
Instead the source is now reported as "Undefined"
Closes issues #3733 and #3627
> fix: prevent undefined relatedNodes from halting axe

- lib/standards/aria-roles.js
- test/act-rules/act-runner.js
- test/act-rules/aria-required-owned-element-bc4a75.spec.js
- test/checks/aria/required-children.js
- test/checks/aria/required-parent.js
Part of issue https://github.com/dequelabs/axe-core/issues/3708
> feat(list,listitem): do not allow group as allowed parent or child

- lib/standards/aria-roles.js
- test/integration/rules/aria-required-attr/required-attr.html
- test/integration/rules/aria-required-attr/required-attr.json
Part of issue https://github.com/dequelabs/axe-core/issues/3708
> feat(required-attr): require aria-checked for checkbox-like and radio-like roles

- lib/core/base/context.js
- lib/core/base/context/create-frame-context.js
- lib/core/base/context/normalize-context.js
- lib/core/base/context/parse-selector-array.js
- test/core/base/context.js
- test/core/public/finish-run.js
- test/core/public/run-partial.js
- test/core/utils/get-frame-contexts.js
In refactoring the context file I found this bug:
Related to #3793
> refactor: break up context.js and clean it up a bit

- lib/core/utils/index.js
- lib/core/utils/shadow-select-all.js
- test/core/utils/shadow-select-all.js
This new `axe.utils.shadowSelectAll()` method should make it a little easier to explicitly include or exclude nodes in shadow DOM trees. This is a first step in providing a context that can include/exclude shadow DOM nodes without additional code.
Related to #3765
> feat(utils): new shadowSelectAll utility

- doc/check-options.md
- lib/checks/label/label-content-name-mismatch-evaluate.js
- lib/checks/label/label-content-name-mismatch.json
- lib/checks/mobile/css-orientation-lock-evaluate.js
- lib/commons/text/accessible-text-virtual.js
- lib/commons/text/is-icon-ligature.js
- test/commons/text/is-icon-ligature.js
Fixes typos of the word "occurrence" throughout axe-core.
> feat(checks/label-content-name-mismatch): deprecate occuranceThreshold option in favor of occurrenceThreshold to fix typo

- lib/commons/color/flatten-shadow-colors.js
As of PR #3791, the flattenShadowColors method is no longer in use.
Closes #3199
> feat(commons): deprecate flattenShadowColors in favor of flattenColors

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
Address some issues introduced in #3798
1. Separate SerialContextObject from FrameContextObject
2. Allow changing the reporter type
3. Fix issue with the frameSelector type -- This should have been a CrossTreeSelector
> chore: improve type definitions

- .github/workflows/release.yml
Release script doesn't work. I think because install isn't happening:
https://github.com/dequelabs/axe-core/actions/runs/3659002795/jobs/6184493234#step:5:41
> ci: fix release script not installing

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
Address is minor "break" in the types caused by 4.6.0.
> fix(d.ts): add optional include to ContextObject

- doc/API.md
We don't have any `wcag21aaa` rules and we recently introduced our first `wcag22aa` rule.
> docs(api.md): update list of allowed tags

- lib/commons/color/get-background-color.js
`axe-core` was setting a read-only property, resulting in errors when run from an extension.
Closes: https://github.com/dequelabs/axe-core/issues/3837
> fix(color-contrast): fix color-contrast check when running in an extension

- sri-history.json
The sri-history sha was incorrect from our bot process. Re-releasing the release with a corrected sha.
> chore(release): v4.6.2

- .circleci/config.yml
In order to help prevent the release bot from releasing a bad sri sha (cause still unknown), we'll verify the sha in the circle job [against branches that start with `release-`](https://circleci.com/docs/configuration-reference/#jobfilters). That way we should be able to prevent merging bad shas into master.
> ci: verify sri-history in release pr

- .circleci/config.yml
While looking through the circle ci script I saw a few things we could improve to speed up the process or just clean up the file a bit. In total, this shaved off about 3.5 minutes from the build.
- current config: avg. 12m (based on the last few runs, 10m min, 13m max).
- streamlined: 8m 42s
Here's the changes:
- check if the npm cache was restored before running `npm ci` and saving the cache. `npm ci` [removes `node_modules` before installing](https://docs.npmjs.com/cli/v9/commands/npm-ci), so restoring the cache before installing isn't helpful. [You can see this working here](https://app.circleci.com/pipelines/github/dequelabs/axe-core/4771/workflows/35937673-9a59-4eac-8ed0-a588b86ba21a/jobs/53463) and [when the cache doesn't exist …
> ci: streamline ci

- lib/commons/dom/create-grid.js
- test/checks/color/color-contrast.js
- test/commons/dom/get-element-stack.js
> fix(color-contrast): correctly compute color contrast of <slot> elements

- .circleci/config.yml
For some reason if you don't run the `checkout` step before installing browser tools it fails due to `license.Chromedriver` existing in `~/axe-core` 
Ref: https://app.circleci.com/pipelines/github/dequelabs/axe-core/4791/workflows/1fd9a6d9-2420-4129-b164-eb085503f53d/jobs/53640
> ci: checkout before installing chrome

- test/testutils.js
Overriding the prototype for `DOMRectReadOnly` to throw errors on setting `left`, `right`, `top`, and `bottom` properties to match what happens in an extension context.
```js
const test = $0.getBoundingClientRect();
test.right = 1;  // Uncaught TypeError: setting getter-only property "right"
```
This should fail tests any time we do this now. If I try to set the `right` property in `get-background-color`, multiple tests fail:
Closes: https://github.com/dequelabs/axe-core/issues/3837
> test: prevent setting read-only properties on DOMRect

- lib/commons/dom/focus-disabled.js
- lib/commons/dom/index.js
- lib/commons/dom/is-inert.js
- lib/commons/dom/is-visible-for-screenreader.js
- test/commons/dom/focus-disabled.js
- test/commons/dom/is-inert.js
- test/commons/dom/is-visible-for-screenreader.js
- test/integration/rules/aria-hidden-focus/aria-hidden-focus.html
- test/integration/rules/aria-hidden-focus/aria-hidden-focus.json
- test/integration/rules/frame-focusable-content/frame-focusable-content.html
Also adds `dom.isInert`.
Closes #3448
> feat(dom.focusDisabled,dom.isVisibleForScreenreader): support the inert attribute

- lib/rules/scrollable-region-focusable.json
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.html
This rule isn't intended to test native controls. I'm honestly surprised that `getScroll()` doesn't cause `select` and `textarea` to be skipped like it does for `input` elements with lengthy texts. I suppose browsers did that to give the things their scrollbar, which `input` never gets.
Closes #3692,  closes #3691, closes #3701
> fix(scrollable-region-focusable): skip native controls

- doc/check-options.md
- lib/checks/color/link-in-text-block-evaluate.js
- lib/checks/color/link-in-text-block.json
- test/checks/color/link-in-text-block.js
- test/integration/rules/link-in-text-block/link-in-text-block.html
- test/integration/rules/link-in-text-block/link-in-text-block.json
Pass link-in-text-block when the link has the same text color and background color as the text surrounding it. It also add a check option to disable this feature, since while this technically passes WCAG, it's a bad practice.
Closes: #3848
> fix(link-in-text-block): allow links with identical colors

- lib/commons/text/is-valid-autocomplete.js
- test/commons/text/is-valid-autocomplete.js
- test/integration/rules/autocomplete-valid/autocomplete-valid.html
- test/integration/rules/autocomplete-valid/autocomplete-valid.json
Allow webauthn at the end of the autocomplete tokens list.
Closes:  #3854
> fix(autocomplete-valid): allow webauthn token

- lib/standards/aria-roles.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
Closes: #3758
I have an issue open to ARIA to mention separator on `menu` and `menubar` too: https://github.com/w3c/aria/issues/1844
> fix(aria-required-children): allow separator in menu & menubar

- .circleci/config.yml
Missed the `.` when writing the regex to have it properly run on `release-` branches. While there, also made it match the start of the string only.
> ci: fix sri-validation job regex

- .circleci/config.yml
Because this CI pipeline takes over 3 minutes longer than it needs to.
> ci: more things in parallel

- build/cherry-pick.js
Tried to use this today and it broke due to the git logs [exceeding the buffer size of `exec`](https://nodejs.org/api/child_process.html#child_processexecsynccommand-options). Instead of setting the `maxBuffer` to an arbitrary number that could break in the future, we'll just reduce the amount of commits that log outputs. 3 years should be sufficient to find previous `feat` commits while not exceeding the buffer.
> chore: fix buffer size of git logs for cherry-pick script

- bower.json
Since bower has been deprecated for a while, it makes no sense for axe-core to continue support for it. When the next major version of axe-core is released the bowers.json file will be removed.
Closes: #3728
> feat: deprecate bower

- lib/commons/dom/create-grid.js
- test/commons/dom/get-element-stack.js
- test/integration/rules/color-contrast/color-contrast.html
- test/integration/rules/color-contrast/color-contrast.json
> fix(color-contrast): correctly calculate contrast of flex/grid items with z-index

- lib/rules/color-contrast-matches.js
- test/integration/rules/color-contrast/color-contrast.html
- test/rule-matches/color-contrast-matches.js
Finishes the work on supporting inert. One question I have is if we want to not check the color contrast of labels (implicit, explicit, etc.) for inputs that are inerted. So this example:
```html
<div id="t1"><span>Test</span></div>
<div role="textbox" aria-labelledby="bob t1 fred" inert></div>
```
We prevent checking this type of setup if the input is disabled (or `aria-disabled`). Do we need to do the same if the input has `inert`?
Closes: #3448
> fix(color-contrast): do not check contrast for inert elements

- .circleci/config.yml
Seems I missed this when I did https://github.com/dequelabs/axe-core/pull/3846, and is now causing nightly to fail.
> ci: nightly - build axe.js cache before tests

- lib/commons/dom/get-modal-dialog.js
- lib/commons/dom/index.js
- lib/commons/dom/is-inert.js
- lib/commons/dom/is-visible-for-screenreader.js
- test/commons/dom/get-modal-dialog.js
- test/commons/dom/is-inert.js
- test/integration/full/dialog/dialog.html
- test/integration/full/dialog/dialog.js
> feat: support the dialog element

- lib/commons/text/is-icon-ligature.js
Removes the console warning related to font-icon checking and improves the speed of multiple readback operations, as mentioned in the warning.
> Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
Closes: [3900](https://github.com/dequelabs/axe-core/issues/3900)
> fix(is-icon-ligature): prevent canvas2d warning willReadFrequently

- lib/commons/dom/create-grid.js
- test/commons/dom/get-element-stack.js
While working on the code, I realized that the spec said that if _any_ element that creates a stacking context it would remove the fake stacks created from float or positioned elements that use auto or 0 z-index. So I was able to merge those functions into a single if statement. I also simplified the loop to remove fake stacks so it only needs to look through the array and `splice` once (since any new stack removes all previous fake stacks).
Closes: #3929
> fix(create-grid): correctly compute stack order for non-positioned stacking contexts

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
Add types for various missing public options and methods:
- axe.setup()
- axe.teardown()
- axe.getReporter()
- axe.hasReporter()
- axe.addReporter()
- axe.configure({ reporter })
- axe.configure({ rules: { metadata } })
- axe.configure({ checks: { metadata } })
Closes: #3965
> fix(d.ts): Add missing types for public axe methods

- lib/standards/html-elms.js
`datalist` is not visible (even when the list is "open") so this change won't report anything (thus the `chore`). Just keeping up with the spec changes so we aren't out of date.
Closes: #3322
> chore: update datalist spec to disallow aria attrs

- lib/checks/mobile/css-orientation-lock-evaluate.js
- package-lock.json
- package.json
- test/checks/mobile/css-orientation-lock.js
- test/integration/full/css-orientation-lock/violations.css
- test/integration/full/css-orientation-lock/violations.html
- test/integration/full/css-orientation-lock/violations.js
> fix(css-orientation-lock): support the css rotate property

- lib/commons/color/get-foreground-color.js
- lib/commons/color/stacking-context.js
- test/commons/color/get-foreground-color.js
- test/commons/color/stacking-context.js
- test/playground.html
> fix(color-contrast): correcly apply opacity to foreground color

- doc/release-and-support.md
- Remove wording suggesting a major release every 12 to 18 months. Major releases are done as needed. We only want to do them when they are necessary
- Minor releases have a 3 week lead-time instead of 6
- Added a section on the use of milestones and code freeze
- Fix a couple typos
Closes: #3897
> docs(release-and-support): Adjust  release cadence

- lib/checks/aria/aria-required-children-evaluate.js
- lib/standards/aria-roles.js
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
When an element such as menu or list is set for review when it's empty, it should also be set for review if it has only hidden content.
Closes: #4010
> fix(aria-required-children): trigger reviewEmpty with hidden children

- lib/checks/color/link-in-text-block-style-evaluate.js
- lib/checks/color/link-in-text-block-style.json
- lib/standards/aria-roles.js
- locales/_template.json
- test/checks/color/link-in-text-block-style.js
- test/integration/rules/link-in-text-block/link-in-text-block.html
- test/integration/rules/link-in-text-block/link-in-text-block.json
Links with content on a :before or :after pseudo-elements are reported as incomplete, as those may pseudo elements may or may not be used to indicate these are links.
Closes: #3993
> fix(link-in-text-block): set links with pseudo-content for review

- lib/core/utils/check-helper.js
- test/core/utils/check-helper.js
Ensure virtual nodes are accepted as related nodes. This prevented aria-required-children from reporting related nodes. I would've added a test to `aria-required-children` for related nodes, but it turned out it already has them. We just never noticed it wasn't working.
Closes: #4032
> fix(aria-required-children): set related nodes for invalid children

- lib/standards/html-elms.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
closes #4054
as stated in the PR title, this adds the meter element to be an allowed role for the img element when it is provided an accessible name.
> fix(aria-allowed-role): add meter to allowed roles for named img

- build/tasks/esbuild.js
- lib/checks/navigation/region-evaluate.js
- lib/commons/color/incomplete-data.js
- lib/commons/standards/implicit-html-roles.js
- lib/core/base/virtual-node/virtual-node.js
- lib/core/utils/frame-messenger/message-id.js
- lib/core/utils/frame-messenger/post-message.js
- lib/core/utils/get-selector.js
- lib/core/utils/is-xhtml.js
- lib/core/utils/query-selector-all-filter.js
- lib/standards/html-elms.js
- test/checks/navigation/region.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
I went over the entire codebase looking for places where we're keeping variables we should clean up after a run. Probably the biggest one was in `querySelectorAllFilter`, which was indicated as a problem in the issue. I found a few other places where info was stored in file scope where it shouldn't have been. Those have been fixed. There shouldn't be any of those left now.
The issue indicated the biggest problem with in FrameMessenger's [channels](https://github.com/dequelabs/axe-core/blob/0e73be039eed78fda20e9bf28ee7f6f7c0d62fd8/lib/core/utils/frame-messenger/channel-store.js#L3). That's not something we can put into the cache though. FrameMessenger isn't necessarily tied to a run, so we can't clear channels after the run is closed. What I've tried to do instead is move things around a …
> fix: avoid memory issues by doing better cleanup

- lib/core/base/rule.js
- test/core/base/rule.js
Fixes a 9 year old bug that effects nothing, since we don't have after methods that use options.
> chore(rules): avoid passing unnecessary info into afters

- doc/API.md
No behavior change, just documenting an existing bit of behavior that surprised me when it came up during a conversation with @WilcoFiers and @straker last week.
> docs(api.md): note preloading may be skipped even if enabled

- lib/commons/dom/create-grid.js
- lib/commons/dom/visually-sort.js
- test/commons/dom/create-grid.js
- test/commons/dom/get-element-stack.js
- test/commons/dom/visually-sort.js
Mostly it's rearranging the order of the `createStackingContext` function to handle elements that created stacking context and needed to be positioned or floated. The code didn't handle elements that were both positioned with `z-index: auto` and another property that made it a stacking context (like `display: flex`). 
Also changed how to handle adding the node index to every context by making it it's own property instead of combining it with the stacking context value. Made things simpler when creating / comparing the numbers. This was needed to allow sorting elements from different (but equal) stacking contexts correctly. Before they would be sorted as equal (stacking contexts were the same value) and then relied on the document order and positional sorting (based on float or inline), …
> fix(color-contrast): correctly handle flex and position

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
Improve axe.d.ts types based on what we found was missing/incorrect and was needed in our code. I added more details for each change in commit messages (I tried to verify that each change is correct by looking at axe internals). Some of the issues were introduced with a recent update in #3966, which prompted me to look into this more.
> feat(d.ts): improve axe.d.ts types

- lib/checks/generic/page-no-duplicate-evaluate.js
- lib/checks/keyboard/page-no-duplicate-banner.json
- lib/checks/keyboard/page-no-duplicate-contentinfo.json
- test/checks/keyboard/page-no-duplicate.js
- test/integration/full/landmark-no-duplicate-banner/frames/level1.html
- test/integration/full/landmark-no-duplicate-contentinfo/frames/level1.html
Our `nativeScopeFilter` selector only accounted for native elements and not elements with sectioning roles. Instead of adding sectioning roles to the selector, I  decided to add the new `role` option to let the check look at the role of the element, which computes the implicit html role based on [sectioning ancestors](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/standards/implicit-html-roles.js#L16-L25). That way our selectors can't become out-of-sync and cause issues in the future.
I also deprecated the `nativeScopeFilter` option since we shouldn't be using it over the `role` option. 
Closes: #3943
> feat(page-no-duplicate-banner/contentinfo): deprecate options.nativeScopeFilter, take into ancestors with sectioning roles

- lib/commons/text/has-unicode.js
- lib/commons/text/remove-unicode.js
- lib/commons/text/unicode.js
- test/commons/text/unicode.js
Format characters such as zero-width spaces were not checked in the `nonBMP` section of the unicode functions. I generated the regex by using [regenerate](https://github.com/mathiasbynens/regenerate) and adding all [format unicode to it](https://www.compart.com/en/unicode/category/Cf).
In making this change I also discovered a bug in `hasUnicode` in that it only checked the first option that matched and not all options due to the early return style. So trying to check if a string contained punctuation while also checking if it had emoji would only ever check if it had emoji. Fixed that while I was here.
Closes: #3913
> fix(color-contrast): ignore format unicode characters

- lib/commons/dom/create-grid.js
- test/commons/dom/create-grid.js
- test/integration/full/contrast/memory.html
- test/integration/full/contrast/memory.js
Implementing https://github.com/dequelabs/axe-core/issues/3923#issuecomment-1624013523
Closes: #3923
> fix(commons/dom/createGrid): only add the visible, non-overflow areas of an element to the grid

- build/rule-generator.js
- build/rule-generator/get-files-metadata.js
- package-lock.json
- package.json
Was working on a new rule, spotted the indentation was all off. I figured that while I'm fixing that, I might as well modernise a couple things.
> chore: modernized rule generator

- lib/standards/aria-attrs.js
- test/checks/aria/valid-attr-value.js
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
- test/integration/virtual-rules/aria-valid-attr-value.js
Allow the following attributes to be empty:
- aria-braillelaberl
- aria-brailleroledescription
- aria-valuetext
Closes: #4108
> fix(aria-valid-attr-value): allow  empty value on aria-braille* & aria-valuetext

- doc/examples/jsdom/test/a11y.js
- lib/core/public/run.js
- lib/core/public/setup.js
- test/core/public/setup.js
- test/node/jsdom.js
`axe.setup()` should set up temporary globals when `globalThis.window` and/or `globalThis.document` aren't set up. This PR fixes that.
Closes #3962
> fix(jsdom): allow axe.setup() without a global window

- lib/standards/aria-roles.js
- test/integration/rules/aria-allowed-attr/passes.html
WAI-ARIA 1.3 has proposed to dramatically change which roles allow aria-expanded. Per this PR, `checkbox` and `switch` now allow this attribute. Quite a few more roles no longer allow `aria-expanded`.
I've opened up an issue requesting that ARIA 1.3 deprecate aria-expanded on those roles, instead of simply removing them. I think simply removing them would create a lot of unnecessary friction. If the W3C decides not to stay backward compatible we may have to figure out a different way to present this, but by far the best solution here would be to use deprecation, which is what they've also done in other places. See https://github.com/w3c/aria/issues/1990
Closes #3339, closes #3343
> fix(aria-allowed-attr): pass aria-expanded on checkbox & switch

- lib/commons/text/form-control-value.js
- lib/commons/text/subtree-text.js
- lib/commons/text/unsupported.js
- test/commons/text/accessible-text.js
- test/commons/text/form-control-value.js
- test/commons/text/subtree-text.js
- test/integration/rules/aria-dialog-name/aria-dialog-name.html
- test/integration/rules/aria-dialog-name/aria-dialog-name.json
- test/integration/rules/label/label.html
- test/integration/rules/label/label.json
- test/testutils.js
The content of landmarks and other elements that have "name from author" should not be ignored when referenced by aria-labelledby or another label. 
This is a bug, where axe was inconsistent with the accessible name spec. Specifically, [step F](https://www.w3.org/TR/accname-1.1/#step2F):
> if the current node's role allows name from content, or if the current node is referenced by aria-labelledby, aria-describedby, or is a native host language text alternative element (e.g. label in HTML), or is a descendant of a native host language text alternative element
Previously axe-core was only considering the first part of this sentence, and skipping name from author elements while following aria-labelledby and `<label>` IDREFs. This was a problem on dialogs (as the issue reported), but had …
> fix(access-name): get name from header elements

- lib/checks/aria/braille-roledescription-equivalent.json
- locales/_template.json
Fix copy/paste error on the pass message of braille-roledescription-equivalent. "Chore" instead of "fix" because this is unreleased.
> chore(braille-roledescription): correct pass message

- .circleci/config.yml
This should temporarily fix the circleci issue with chromedriver version not existing since it is an upcoming stable and not yet stable but is stable for chrome
Also I made this into a command to easily revert or fix in the future 
Ref: https://github.com/CircleCI-Public/browser-tools-orb/issues/90
> ci: pin chrome version

- CHANGELOG.md
Adds some details to the 4.8 changelog. These are already in https://github.com/dequelabs/axe-core/releases/tag/v4.8.0
> chore: add clarifications to changelog

- lib/checks/mobile/target-offset.json
- locales/_template.json
Fixes a typo in the remediation message. I checked the localisations, none of them have the `{$` instead of `${` problem, although we do need the translators to fix the bracket issue I think. Hoping @ma10 can pick that up for Japanese. 
Closes: #4148, closes #4149
> fix(target-size): show closest offset in message

- lib/core/imports/index.js
From #4060; fixes https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/953.
> fix: polyfill Object.hasOwn for node 14

- .github/dependabot.yml
Saw this in the [dependabot pr to update Inquirer to v9](https://github.com/dequelabs/axe-core/pull/4187). Inquirer v9 [moved to ESM only](https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%409.0.0). We use it only for development and only when calling the npm script `rule-gen` to prompt for the name of the rule, if it needs checks, etc.
> chore(dependabot): ignore inquirerv9

- .circleci/config.yml
This is required since chromedriver version stable is currently 118.0.5993.70 but chrome is a higher version and that version of chrome does not exist for chromedriver so we should pin to the latest stable version.
> ci: pin chrome version to `118.0.5993.70`

- build/check-node-version.js
We have dev dependencies that require Node 18 minimum. There's no reason to be on anything older than that.
> chore: set minimum node version for dev to 18

- README.md
This fixes a couple of minor issues I saw while looking over the README file.
> docs: fix gramatical typos in README

- .circleci/config.yml
Per the chromedriver dashboard this pin is no longer required https://googlechromelabs.github.io/chrome-for-testing/.
> ci: remove chromedriver pin

- package-lock.json
- package.json
- test/act-rules/aria-required-id-references-in6db8.spec.js
- test/act-rules/letter-spacing-not-important-24afc2.spec.js
- test/act-rules/meta-viewport-b4f0c3.spec.js
- test/act-rules/word-spacing-not-important-9e45ec.spec.js
Updated to the latest ACT tests (with some notes on things that are no longer consistent). This should prevent nightly from failing.
> chore: update ACT tests

- .circleci/config.yml
As of 1.4.5 they added a fallback https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.4.5. Hopefully this resolves https://app.circleci.com/pipelines/github/dequelabs/axe-core/5786/workflows/f9a6a8cb-8628-4021-a5eb-6a0e9e74a308/jobs/63785
No QA Required
> ci: update browser-tools orb for CircleCI

- build/tasks/aria-supported.js
- build/tasks/configure.js
Prettier api was made [async in v3](https://prettier.io/blog/2023/07/05/3.0.0.html#change-public-apis-to-asynchronous-12574httpsgithubcomprettierprettierpull12574-12788httpsgithubcomprettierprettierpull12788-12790httpsgithubcomprettierprettierpull12790-13265httpsgithubcomprettierprettierpull13265-by-fiskerhttpsgithubcomfisker). This updates the build files where the `format` script was used to wait for the promise instead of writing the promise object to the files.
> chore: fix prettier format for built files

- doc/API.md
When hearing the term "needs review" we don't make it clear in our docs that what we really mean is the `incomplete` results. Adding a bit of context to make sure it's clearly stated.
> docs: clarify that `incomplete` means "needs review"

- .eslintrc.js
- CHANGELOG.md
- bower.json
- lib/core/imports/index.js
- lib/core/imports/polyfills.js
- lib/core/utils/index.js
- lib/core/utils/pollyfill-elements-from-point.js
- package-lock.json
- package.json
- sri-history.json
* fix: add Object.values polyfill for node <=6 (#4274)
> chore(release): 4.8.3

- .github/dependabot.yml
- doc/examples/mocha/package.json
[Chai 5.0.0 moved to ESM](https://github.com/chaijs/chai/releases/tag/v5.0.0).
Closes: https://github.com/dequelabs/axe-core/pull/4293
> chore(dependabot): ignore esm chai >= 5.0.0

- lib/core/utils/get-selector.js
- test/core/utils/get-selector.js
Ignore the "xmlns" attribute when generating a selector, since the selector spec does not support namespaces.
Closes: https://github.com/dequelabs/axe-core/issues/4302
> fix(utils/get-selector): ignore 'xmlns' attribute when generating a selector

- package-lock.json
- package.json
- test/act-rules/visible-label-in-accessible-name-2ee8b8.spec.js
Temporarily suppresses the ACT mismatch described by #4311 to avoid nightly ACT test noise until we can fix the inconsistency
~Reviewer note: this suppression only has any effect if you're using ACT content that we haven't yet picked up; you'll need to `npm install w3c/wcag-act-rules#main` (like the nightly build does) to meaningfully validate the change locally.~ As of 9a370b6, this can be tested without updating to main
No QA required
> test: suppress "visible label in accessible name" ACT test issue

- lib/core/base/virtual-node/virtual-node.js
- test/core/base/virtual-node/virtual-node.js
Updates VirtualNode's `props` initialization path to avoid reading properties that we know based on `nodeType` won't be present anyway. This should mitigate #4316 by avoiding reading the problematic `value` prop present on certain text nodes.
I also cleaned up some missing test coverage in the impacted code.
Closes: #4316
> fix: avoid reading element-specific node properties of non-element node types

- .github/workflows/release.yml
It looks like `hub` was removed from all newer versions of GitHub Actions and users are required to install it on their systems to be able to use it. Instead of using `hub` this PR replaces it with `gh` cli
No QA required
> ci: replce `hub` with `gh` CLI

- lib/commons/dom/get-visible-child-text-rects.js
- lib/rules/color-contrast-matches.js
- test/commons/dom/get-visible-child-text-rects.js
- test/integration/rules/color-contrast/color-contrast.html
- test/rule-matches/color-contrast-matches.js
> fix(color-contrast): handle text that is outside `overflow: hidden` ancestor

- .eslintrc.js
- lib/commons/color/color.js
- test/commons/color/color.js
- test/commons/color/get-stroke-colors-from-shadows.js
- test/commons/color/get-text-shadow-colors.js
Decided to move the Color improvements from https://github.com/dequelabs/axe-core/pull/4365/files into their own PR. This also fixes the `clip` bug mentioned in https://github.com/dequelabs/axe-core/pull/4365/files#r1517706612
No QA needed
> feat(color): add color channel values and luminosity, saturation, clip functions

- lib/checks/mobile/target-offset-evaluate.js
- lib/checks/mobile/target-offset.json
- lib/checks/mobile/target-size-evaluate.js
- lib/checks/mobile/target-size.json
- locales/_template.json
- test/checks/mobile/target-offset.js
- test/checks/mobile/target-size.js
- test/integration/full/target-size/too-many-rects.html
Let targets that are more than 240x240 auto-pass the target-size rule to avoid performance issues.
QA note: Test that the page provided in https://github.com/dequelabs/axe-core/issues/4360 results in a pass for the tabpanel in the comment section (https://almanac.httparchive.org/en/2021/ecommerce)
> fix(target-size): always pass 10x targets (avoid perf bottleneck)

- README.md
- locales/zh_CN.json
- Added `zh_CN.json` for Simplified Chinese translation.
- Modified some minor issues in README.md:
- Fixed the issue that the path docs/check-message-template.md was not found.
- Updated the supported languages (added Greek, Italian, Simplified Chinese and Traditional Chinese).
> feat(i18n): Add Simplified Chinese translation

- lib/standards/html-elms.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
Closes: https://github.com/dequelabs/axe-core/issues/4397
> fix(aria-allowed-role): add gridcell, separator, slider and treeitem to allowed roles of button element

- build/tasks/configure.js
Figured a simple `split` would do the job without needing to write a complicated regex to do it. Otherwise we'd need something like `/\.([a-zA-Z_]+)\.js$/`
Closes: #4388
> fix: fix building axe-core translation files with region locales

- lib/checks/label/label-content-name-mismatch-evaluate.js
- lib/commons/text/is-human-interpretable.js
- package.json
- test/commons/text/is-human-interpretable.js
- test/integration/rules/label-content-name-mismatch/label-content-name-mismatch.html
- test/integration/rules/label-content-name-mismatch/label-content-name-mismatch.json
adds exceptions for (dismiss) `×`, wysiwyg characters `b`, `aA`, `abc`
fix: #4386
---
This does _not_ handle all potential use cases. Potential shortcomings worth discussing and opening further issues for are as follows:
- Considering other languages, such as [this example in German including "UT", "AD" or "DGS"](https://github.com/w3c/wcag/issues/3304)
- The original issue #4386 mentioned this being handled as a character limit, but it's unclear if that's a valid option. Consider [the WCAG `ABC` example](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception#examples)
- **EDIT**: Does not specifically have test cases for [math expressions and formulae](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#mathematical-expressions-and-formulae)
> fix(label-content-name-mismatch): better dismiss and wysiwyg symbolic text characters

- lib/commons/dom/visibility-methods.js
- test/commons/dom/visibility-methods.js
Also tested various ways to try to get the `position: absolute` to be hidden by the node. Turns out there are a few cases where it will be hidden:
* overflow node uses position itself other than static
* node in-between the overflow node and the positioned child uses position `relative` or `sticky`
and cases where it won't be hidden
* positioned child uses a position of `fixed` (it won't be hidden by any ancestor overflow, even if the ancestor uses position itself)
Closes: #4016
> fix(isVisibleOnScreen): account for position: absolute elements inside overflow container

- .eslintrc.js
- lib/checks/mobile/target-size-evaluate.js
- lib/commons/dom/get-target-rects.js
- lib/core/utils/contains.js
- test/checks/mobile/target-size.js
- test/commons/dom/get-target-rects.js
- test/integration/full/target-size/shadow-dom.html
- test/integration/full/target-size/shadow-dom.js
This also adds to the `.eslintrc` to error if `node.contains()` or `vNode.actualNode.contains()` or used. (also upgraded the `node.attributes` error to account for `vNode.actualNode.attributes` as I noticed it was missing).
Closes: https://github.com/dequelabs/axe-core/issues/4194
> fix(target-size): ignore descendant elements in shadow dom

- README.md
- locales/README.md
Just clarifying that the `_template.json` file is generated so contributors don't edit it without knowing. The rest of the text is mostly copied from the root level README, which I also corrected gramatical mistakes.
> docs: add readme to locales dir to note _template is generated

- doc/developer-guide.md
Was the only reference to a required node version I could find in the docs. Our node version script is already set to 18.
Closes: https://github.com/dequelabs/axe-core/issues/4323
> docs: update required develop node version to 18

- lib/commons/color/color.js
- lib/core/imports/index.js
- lib/core/imports/polyfills.js
- package-lock.json
- package.json
- test/commons/color/color.js
- test/integration/full/contrast/prototype-lib-1.7.3.js
- test/integration/full/contrast/prototype.html
- test/integration/full/contrast/prototype.js
This [puts back the v0.4.3 code](https://github.com/dequelabs/axe-core/pull/4366) in `color.js` to handle colorjs.io not handling rad and turn values in hsl.
I also decided to use core-js `Array.from` polyfill rather than our own internal one since I needed to bring it in outside of the `polyfill.js` file and could then add it as an import and reuse it in both places.
Closes: https://github.com/dequelabs/axe-core/issues/4428
> revert(color-contrast): revert upgrade to colorjs.io v0.5.0 to work with prototype.js

- .vscode/launch.json
- CONTRIBUTING.md
- doc/developer-guide.md
- package.json
- test/integration/rules/README.md
- test/karma.conf.js
This updates the existing `test:debug` run script to pass `--remote-debugging-port` to chrome, and then sets up a vscode launch profile to connect to that port.
No QA required.
> chore: set up vscode config to attach to test:debug

- lib/commons/standards/implicit-html-roles.js
- test/integration/rules/aria-allowed-attr/passes.html
Turns out we didn't list the `meter` element's implicit role.
Ref: https://github.com/w3c/html-aria/issues/517
QA notes: verify a `meter` element allows non-global aria attributes from the [`meter` role](https://www.w3.org/TR/wai-aria-1.2/#meter).
> fix(aria-allowed-attr): allow meter role allowed aria-* attributes on meter element

- package.json
prettier autofixes some issues eslint finds, letting prettier run first leads to less developer hassle
for example, I've forgotten for weeks to change how my editor does tabs instead of spaces and I've been manually running `npm run fmt` to get around this. While yes I will also correct my editor, this feels like a positive change for all contributors
Closes:
> build: lint-staged prettier before eslint

- lib/checks/aria/aria-required-parent-evaluate.js
- lib/checks/aria/valid-scrollable-semantics-evaluate.js
- lib/checks/color/link-in-text-block-evaluate.js
- lib/checks/color/link-in-text-block-style-evaluate.js
- lib/checks/keyboard/accesskeys-after.js
- lib/checks/keyboard/landmark-is-top-level-evaluate.js
- lib/checks/label/help-same-as-label-evaluate.js
- lib/checks/landmarks/landmark-is-unique-after.js
- lib/checks/landmarks/landmark-is-unique-evaluate.js
- lib/checks/lists/structured-dlitems-evaluate.js
- lib/checks/navigation/unique-frame-title-after.js
- lib/checks/navigation/unique-frame-title-evaluate.js
- lib/checks/parsing/duplicate-id-after.js
- lib/checks/shared/doc-has-title-evaluate.js
- lib/checks/tables/caption-faked-evaluate.js
- lib/checks/tables/same-caption-summary-evaluate.js
- lib/checks/tables/scope-value-evaluate.js
This is a piece of a larger creative time PR so it's easier to review, the full scope can be seen here and includes eslint adjustments not seen here https://github.com/dequelabs/axe-core/pull/4444
---
Who else does this?
- Google (JS style guide) https://google.github.io/styleguide/jsguide.html#features-local-variable-declarations
- Airbnb (popular JS style guide) https://github.com/airbnb/javascript
Why do this?
Gaiety's explanation: "`let` works the way most devs think `var` works. scope leaking and variable hoisting is a messy confusing idea, JS got updated for a reason" also it's 2024, this isn't too controversial anymore
- https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/
- https://blog.javascripttoday.com/blog/var-vs-let-vs-const/ "The var keyword was …
> style(lib/checks): var -> let and const codemod

- test/integration/full/all-rules/all-rules.html
wilco and I believe marque is to blame because it is animated
This fixes the `all-rules` check, particularly on Firefox. We believe the issue is because marque has a moving bounding client rect, leading to inconsistent results. So instead we set the motion to none for a consistent testing environment.
---
To see that it works, I've run the CI tests on this branch five times. It only failed on one unrelated flakey test this does not address.
Also, https://github.com/dequelabs/axe-core/pull/4456 finally builds after many consistent test failures in the same place in a row after rebasing on this change.
We can see this test failing on other branches, such as `develop` in places like this: https://app.circleci.com/pipelines/github/dequelabs/axe-core/6332/workflows/b3e2a293-c89b-4201-898d-1c6c6 …
> fix(all-rules): fix flakey all-rules firefox test

- lib/core/utils/dq-element.js
- test/core/utils/dq-element.js
- test/core/utils/node-serializer.js
Noticed this when trying to debug perf issues in `duplicate-id-aria`. We've run into problems on sites that have a module repeat 1000s of times on the page and the module has an aria id that is also then repeated. Axe-core would take a really long time to run the rule. Looking into it what I discovered is that a majority of the time was spent on resolving the `relatedNodes` for each check. Since each each duplicate id node was also in the `relatedNodes` for every other node, this caused the single node to [be converted to a DqElement](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/check-helper.js#L46) _n_ times. This lead to many performance problems, but specifically calling the `getSelector` of a DqElement would call `outerHTML` for the node _n*2_ times which would be …
> perf: memoize DqElement

- Gruntfile.js
This change updates the code path that is invoked when the build is run using the `--all-lang` option. When assembling the list of locale files from the `/locales` directory, this change only includes files that satisfy _both_ of the following criteria:
- Does not start with `_`
- Ends with `.json`
This effectively excludes `_template.json` and `README.md`, and may proactively filter out future utility files that do not follow the typical locale-file naming standard.
Closes: #4485
> fix(build): limit locales to valid files when using the --all-lang option

- .github/dependabot.yml
Conventional commits upgraded to ESM only in v6.
Closes: https://github.com/dequelabs/axe-core/pull/4476
> chore: ignore conventional-commits-parser >= 6 as esm

- build/cherry-pick.js
The build script wasn't committed as executable, nor had the node comment.
No QA needed
> chore: make cherry-pick script executable

- lib/commons/standards/implicit-html-roles.js
- lib/rules/landmark-unique-matches.js
- test/commons/aria/implicit-role.js
- test/rule-matches/landmark-unique-matches.js
Update the landmark-unique rule matcher for aside elements so that they are treated as landmarks using the same criteria specified in [Sections 3.4.8 and 3.4.9 of the HTML Accessibility API Mappings 1.0](https://w3c.github.io/html-aam/#el-aside-ancestorbodymain). 
Closes: #4460
> fix(landmark-unique): follow spec, aside -> landmark

- .github/workflows/test.yml
> ci: fix usage of deprecated `artifact` actions

- lib/checks/aria/aria-required-attr-evaluate.js
- test/checks/aria/aria-required-attr.js
- test/integration/rules/aria-required-attr/required-attr.html
- test/integration/rules/aria-required-attr/required-attr.json
> fix(required-attr): allow aria-valuetext on slider instead of valuenow

- test/rule-matches/object-is-loaded-matches.js
These test failures are happening because the test isn't allowing sufficient time for slower test scenarios (headed browsers in CI machines) to finish setting up test fixtures before testing against them.
I experimented with using `load`/`error` events on the fixtures instead of a flat time, but this didn't work reliably; in the case where the browser renders fallback content, it fires the `error` event *before* the fallback content is ready, at least in Chromium stable. I wanted to stick to a timebox for this so I settled for just increasing the time allotment instead.
Closes: #4529
> test(object-is-loaded-matches): prevent test flakiness by allowing more time to load <object> data

- test/integration/rules/summary-name/summary-name.html
- test/integration/rules/summary-name/summary-name.json
> chore(summary-name): add role=button example

- lib/core/base/audit.js
- test/core/base/audit.js
- test/core/public/configure.js
- test/integration/full/configuration/tag-exclude.html
- test/integration/full/configuration/tag-exclude.js
Deprecated rules are disabled by default, but because they still have WCAG / best-practice tags, using tags can unintentionally turn them back on. This PR makes it so that rules with the `deprecated` tag do not run unless they are explicitly enabled.
Closes: #4523
> fix(aria-roledescription): keep disabled with { runOnly: 'wcag2a' }

- axe.d.ts
- lib/core/base/context/normalize-context.js
- lib/core/public/run/normalize-run-params.js
- lib/core/utils/index.js
- lib/core/utils/is-array-like.js
- lib/core/utils/is-context.js
- lib/core/utils/object-has-own.js
- test/core/utils/is-array-like.js
- test/core/utils/is-context.js
- test/core/utils/object-has-own.js
- typings/axe-core/axe-core-tests.ts
Had a couple scenarios where this code was getting copied over to other repos. For backward compat reasons that's going to need to stay, but at least if we have these methods on axe.utils we can prevent problems in the future if we change how context works. 
No QA needed on this one.
> refactor: put isContext methods on axe.utils

- test/karma.conf.js
Noticed this while trying to debug a test that we were loading `axe.min.js` into the unit tests instead of using `axe.js`. This made debugging impossible, so I'm just serving the file needed for the [colorjs test](https://github.com/dequelabs/axe-core/blob/develop/test/integration/full/patch/patch.mjs#L43) instead of loading it for the entire test run.
No QA required
> test: don't load axe.min

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
Adds the TypeScript typings for passing an object to the `preload` setting for `axe.run`, as documented here: https://www.deque.com/axe/core-documentation/api-documentation/#preload-configuration-details
> Specifying an object
```js
axe.run(
{
preload: { assets: ['cssom'], timeout: 50000 }
},
(err, results) => {
// ...
}
);
```
> fix(axe.d.ts): add typings for preload options object

- test/integration/rules/runner.js
> test: add workaround for target-size test failure in Firefox 131 nightly

- doc/examples/jest_react/jest.setup.js
- doc/examples/jest_react/link.test.js
- doc/examples/jest_react/package.json
- doc/examples/qunit/Gruntfile.js
- doc/examples/qunit/package.json
- doc/examples/qunit/test/test.html
When I updated https://github.com/dequelabs/axe-core/pull/4548 to latest it caused the qunit tests to fail. Turns out that [qunitjs](https://www.npmjs.com/package/qunitjs) has been deprecated and is now called just `qunit`, and `grunt-contrib-qunit` [has issues](https://github.com/gruntjs/grunt-contrib-qunit/issues/209) if not using latest qunit. Once upgraded I was able to get the tests passing but only in headed mode. That was because puppeteer [is now headless by default](https://github.com/gruntjs/grunt-contrib-qunit/blob/main/docs/qunit-options.md#puppeteer), so passing the `ignoreDefaultArgs` param and the `--headless` arg was causing the issue.
`jest_react` was also failing and after trying to fix it with it's current dependencies @dbjorge  suggested it would be better to just …
> docs: fix example tests

- test/integration/full/run-partial/after-method.js
- test/integration/full/run-partial/context-size-focusable.js
- test/integration/full/run-partial/page-level.js
- test/testutils.js
This should fix the issue with the tests failing on`windowHeight` being different between two consecutive runs. 
I also added a deep axe-core results compare function that can do two significant things for us when comparing result objects. First it can ignore keys (like `timestamp`) so we don't have to always set it equal to each other in the tests. Second is that instead of dumping the entire result objects when a value is different this will output they key path and the values that are different which make debugging a lot easier.
```
Expected result.testEnvironment.windowHeight to equal "948" but got "896"
```
> test: ignore windowHeight in partialRun tests

- locales/README.md
Update the doc for clarity and consistency with present tense. Also, "rules' description and help properties as well as each checks' metadata.messages property" → should be "rule's description and help properties, as well as each check's metadata.messages property" (singular possessive for "rule" and "check," and add a comma before "as well as").
> docs: Update README.md with grammatical fixes

- test/aria-practices/apg.spec.js
Fixes our nightly tests by ignoring the experimental page for `aria-actions` on tabs.
> test: ignore apg tabs-action

- lib/standards/html-elms.js
The ARIA in HTML spec [allows a form element to have role=form](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties#el-form), but [axe does not allow it](https://github.com/dequelabs/axe-core/blob/develop/lib/standards/html-elms.js#L264). This PR adds form to the allowedRoles of form.
> fix(aria-allowed-role): add form to allowed roles of form element

- lib/rules/area-alt.json
- lib/rules/image-alt.json
- lib/rules/input-image-alt.json
- lib/rules/object-alt.json
- lib/rules/role-img-alt.json
It should be alternative text, not alternate text. 
Closes:
> fix(rules): Change "alternate text" to "alternative text"

- lib/core/utils/get-ancestry.js
- test/core/utils/get-ancestry.js
> fix(get-ancestry): add nth-child selector for multiple siblings of shadow root

- lib/core/utils/get-ancestry.js
- test/core/utils/get-ancestry.js
Seems I removed the conditional check on the children lookup during a refactor. Adding it back in and ensuring there's a test so this doesn't happen again.
> fix(get-ancestry): don't error when there is no parent

- locales/de.json
fixed typos in de.json ("nichtleer" vs "nicht leer")
Closes:
> fix(locale): fixed typos in german (DE) locale

- locales/ko.json
Other rule description ends with period, but "landmark-one-main" doesn't.(ends with comma)
To align with the context, I changed comma to period
> chore: fix comma to period

- lib/standards/html-elms.js
- test/integration/rules/aria-allowed-role/aria-allowed-role.html
- test/integration/rules/aria-allowed-role/aria-allowed-role.json
img element can have 'math' as its role
Closes: #4657
> fix(aria-allowed-role): Add math to allowed roles for img element

- doc/API.md
Fix invalid anchor link in the API.md documentation file.
> docs: fix anchor to runPartial / finishRun docs heading

- .github/dependabot.yml
Prevent dependabot upgrade to glob@11 as it drops support for node 18, which we still support in our tests. 
Ref: https://github.com/dequelabs/axe-core/pull/4549
> chore: don't upgrade glob@11 due to node 18 support

- .circleci/config.yml
Firefox 135 switched from distributing `.tar.bz2` files to `.tar.gz` files. This adjusts our circleci config to account for that. See https://github.com/CircleCI-Public/browser-tools-orb/pull/123
Resolves yesterday's nightly build failures.
> test: resolve nightly failure installing firefox 135

- test/checks/color/link-in-text-block.js
Axe-core nightly tests seem to be failing because Firefox nightly changed their link color.  It use to be `rgb(0,0,238)` but now is `rgb(0,102,204)`. This is causing one of our link-in-text block tests to fail as the link is now passing color contrast ratio with 3.68 (instead of failing with 2.18) https://app.circleci.com/pipelines/github/dequelabs/axe-core/6974/workflows/ba733cb4-6dc9-4a15-8002-660c46e6cf55/jobs/75535
This hard codes the expected foreground color on the link as the test is expecting a specific value for the data.
> test(link-in-text-block): fix firefox nightly update to link color

- test/integration/full/preload/preload.js
Seems the unpkg link `https://unpkg.com/gutenberg-css@0.4` now redirects to a `.scss` file rather than a css file, which caused the link to fail to load the resource. Updated the link to hardcode the css file path.
Also added a `return` to the `done` call as it would call done on failure, but then continue to try to remove the stylesheet that didn't exist.
> test(preload): fix link to gutenberg css

- CONTRIBUTING.md
Just wanted to add some information about developing in axe-core.
> docs(contributing): add info about structure, import, and philosophy of axe-core development

- package-lock.json
- package.json
Updates `@axe-core/webdriverjs` to current [latest version](https://github.com/dequelabs/axe-core-npm/releases/tag/v4.10.2)
no qa required
> chore: update to use `@axe-core/webdriverjs` 4.10.2

- .github/dependabot.yml
This applies the new [cooldown option](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-) for dependabot. It will hold updates until after they have been out for at least a week. This will allow a reasonable time for packages to exist and if any issues exist in the supply chain, get caught before the updates come through.
No QA Needed
Refs: https://github.com/dequelabs/axe-api-team/issues/598
> ci(dependabot): use cooldown delay recent updates

- lib/core/utils/performance-timer.js
- test/core/utils/performance-timer.js
I ran into a problem with this:
https://github.com/dequelabs/axe-core/blob/e7dae4ec48cbfef74de9f833fdcfb178c1002985/lib/core/base/rule.js#L297-L300
If the end mark isn't set, performance.measure throws an error. Since we call performance.measure in the catch, it is quite possible that the end mark doesn't exist. And then throwing from a catch completely throws the run. I don't think axe should fail if the performance measure fails, so instead I'm going to have it just log the error and move forward.
> fix(performanceTimer): throwing in axe catch clause

- lib/core/utils/dq-element.js
- test/core/utils/dq-element.js
feat(DqElement): Fixed truncation logic for large outerHTML for the the element itself
Changed truncation logic to also truncate the element of DqElement's source, while preserving the earlier truncation logic.
Closes: Issue #4544
> feat(DqElement): Truncate large `html` strings when the element has a large outerHTML string

- lib/core/utils/dq-element.js
The function is no longer used in the code base and was replaced in #4093 
Closes: https://github.com/dequelabs/axe-core/issues/4129
> feat(DqElement): deprecate fromFrame function

- axe.d.ts
When changing SupportError to RuleError I missed the type file.
> fix(type): correct RuleError type

- test/core/utils/performance-timer.js
Resolves continuing issues like https://app.circleci.com/pipelines/github/dequelabs/axe-core/7418/workflows/a3f6cd97-f7f7-4093-99ae-3b7b6e8f5934/jobs/79830
> test(performance-timer): reduce flakiness of tests involving actual sleeps (round 2)

- build/tasks/validate.js
- lib/rules/focus-order-semantics.json
- lib/rules/region.json
- lib/rules/skip-link.json
- lib/rules/table-duplicate-name.json
Mark the following best practice rules as part of RGAA:
- focus-order-semantics (experimental)
- region
- skip-link
- table-duplicate-name
> feat(tap): some best practice rules map to RGAA
