dequelabs/axe-core

- lib/rules/image-alt.json
- test/integration/rules/image-alt/image-alt.html
- test/integration/rules/image-alt/image-alt.json
> Add role-presentation to image-alt

- doc/rule-descriptions.md
- lib/rules/tabindex.json
> Make tabindex a best practice

- README.md
> Add bower badge

- .editorconfig
- .travis.yml
- Gruntfile.js
- README.md
- build/sauce.conf.js
- package.json
- test/commons/table/is-data-table.js
- test/commons/text/accessible-text.js
- test/runner.tmpl
- test/unit/public/run-rules.js
- test/unit/public/run-tool.js
- test/unit/utils/collect-results-from-frames.js
> Add sauce labs

- lib/checks/color/color-contrast-matches.js
- test/checks/color/color-contrast.js
- test/integration/rules/color-contrast/color-contrast.html
> Add exemption for labels of disabled controls

- build/configure.js
- doc/rule-descriptions.md
- package.json
> Encode HTML in descriptions and correct format

- lib/core/reporters/full.js
- lib/core/reporters/helpers/format-check.js
- lib/core/reporters/helpers/format-checks.js
- lib/core/reporters/helpers/format-rule-result.js
- lib/core/reporters/helpers/split-results-checks.js
- lib/core/reporters/helpers/split-results.js
- lib/core/reporters/na.js
- lib/core/reporters/no-passes.js
- lib/core/reporters/v1.js
- test/core/reporters/helpers/format-check.js
- test/core/reporters/helpers/format-checks.js
- test/core/reporters/helpers/format-node.js
- test/core/reporters/helpers/format-rule-result.js
- test/core/reporters/helpers/split-results-checks.js
- test/core/reporters/na.js
- test/core/reporters/no-passes.js
- test/core/reporters/raw.js
> Add na and no-passes reporters

- lib/core/utils/check-helper.js
- test/core/utils/check-helper.js
> More defensive checks in relatedNodes

- lib/checks/shared/duplicate-id.json
> Add duplicate ID to message

- lib/core/base/context.js
- test/core/base/context.js
- test/playground.html
> Default include to `document`

- doc/API.md
> Clarify a couple areas, consistent indentation in examples

- lib/core/public/get-rules.js
- test/core/public/get-rules.js
> Add help, helpUrl and tags to axe.getRules

- lib/core/base/rule.js
- lib/core/utils/check-helper.js
- lib/core/utils/dq-element.js
- lib/core/utils/merge-results.js
- test/core/utils/dq-element.js
- test/core/utils/index.js
> Move DqElement to utils

- Gruntfile.js
- build/tasks/nodeify.js
- package.json
> Add Node exports / index.js

- lib/core/base/audit.js
- test/core/public/configure.js
- test/core/public/load.js
Resolves #50 for real
Resolves #114
> Expose commons and set data for custom rules

- lib/core/utils/dq-element.js
- test/core/utils/dq-element.js
> Make triple sure source is a String

- lib/commons/color/get-background-color.js
- lib/commons/table/is-data-table.js
- test/commons/color/get-background-color.js
- test/integration/full/contrast/sticky-header.html
- test/integration/full/contrast/sticky-header.js
> Exclude elements obscured by other elements from analysis (Color Contrast)

- README.md
2 back for Chrome; Last ESR for Firefox
> Update supported browsers

- lib/checks/lists/listitem.js
- lib/checks/lists/listitem.json
- lib/rules/definition-list.json
- lib/rules/dlitem.json
- lib/rules/list.json
- lib/rules/listitem.json
- test/checks/lists/listitem.js
- test/integration/full/definition-list/dl-role.html
- test/integration/full/definition-list/dl-role.js
- test/integration/full/definition-list/dlitem-role.html
- test/integration/full/definition-list/dlitem-role.js
- test/integration/full/list/li-role.html
- test/integration/full/list/li-role.js
- test/integration/full/list/list-role.html
- test/integration/full/list/list-role.js
Turn off list rules when role is overridden and allow an ARIA role=list to contain list items
Fixes #129
> Lists with overridden roles

- CHANGELOG
We probably want to add more information about rules and checks.
> Update changelog with release info

- doc/API.md
> Add missing documentation

- doc/projects.md
> Update projects that use axe-core

- README.md
Add report measurements of quality for packages
> Add package quality badge

- build/configure.js
- doc/rule-descriptions.md
- lib/checks/navigation/href-no-hash.js
- lib/checks/navigation/href-no-hash.json
- lib/rules/href-no-hash.json
- test/checks/navigation/href-no-hash.js
- test/integration/rules/href-no-hash/href-no-hash.html
- test/integration/rules/href-no-hash/href-no-hash.json
New best practice rule as discussed here: https://github.com/dequelabs/axe-core/issues/209
> add best practice rule href-no-hash

- doc/projects.md
Change the plugin gulp-axe-core in favor of gulp-axe-webdriver.
> Replace gulp-axe-core with gulp-axe-webdriver

- CONTRIBUTING.md
- package.json
- typings/axe-core/axe-core-tests.ts
- typings/axe-core/axe-core.d.ts
Closes https://github.com/dequelabs/axe-core/issues/183
> feat: add typescript definition file

- CONTRIBUTING.md
- doc/code-submission-guidelines.md
> docs: add commit and PR guidelines

- doc/API.md
> Fix typo on API.md

- lib/core/public/a11y-check.js
- lib/core/public/run-rules.js
- lib/core/reporters/helpers/process-aggregate.js
- lib/core/utils/dq-element.js
- test/core/public/run-rules.js
- test/core/public/run.js
- test/integration/full/options/frames/frame.html
- test/integration/full/options/options.html
- test/integration/full/options/options.js
- test/mock/frames/test.html
- `iframes`: if false, only collect results from top frame
- `elementRef`: if true, return live element references for results from top frame
- `noSelectors`: if true, omit `target` for results from top frame.
> Add configuration options

- test/core/reporters/na.js
- test/core/reporters/no-passes.js
- test/core/reporters/v1.js
- test/core/reporters/v2.js
Opening this PR to make sure the tests pass in CI, then I'll merge.
> test: add selectors option to reporters

- lib/core/utils/publish-metadata.js
- test/core/utils/publish-metadata.js
@dylanb here's the logic we talked about. I'll have to talk with Wilco about how to localize the fallback message.
> feat: add fallback fallback message

- lib/checks/shared/duplicate-id.json
Change the impact of duplicate-id rule to moderate, in accordance with Deque Way.
> Duplicate id impact

- Gruntfile.js
- doc/examples/jest+react/.babelrc
- doc/examples/jest+react/README.md
- doc/examples/jest+react/link.js
- doc/examples/jest+react/link.test.js
- doc/examples/jest+react/package.json
- doc/examples/jest+react/test-helpers.js
Small example of how to use aXe on a React component, using Jest, Enzyme and JSDOM.
> Jest example

- doc/rule-descriptions.md
- lib/checks/visibility/hidden-content.js
- lib/checks/visibility/hidden-content.json
- lib/rules/hidden-content.json
- test/checks/visibility/hidden-content.js
- test/integration/rules/hidden-content/hidden-content.html
- test/integration/rules/hidden-content/hidden-content.json
Adds a new rule/check:
1. checks for content with `display: none`, `visibility: hidden`, or `aria-hidden` and flags it for review
Tests are included.
> feat: added new rule/check notifying for unseen or hidden content

- lib/checks/color/color-contrast.js
- lib/checks/color/color-contrast.json
- lib/commons/color/incomplete-data.js
- test/checks/color/color-contrast.js
- test/commons/color/contrast.js
- test/integration/rules/color-contrast/color-contrast.html
- test/integration/rules/color-contrast/color-contrast.json
This PR builds on #330, so that one should be merged first. 
This change puts 1:1 ratio elements into Needs Review instead of pass or fail. That way, developers have the opportunity to review an item and see if it is actually an issue, or if it was intentional (like in #319). The new aXe interface will make this easier to debug, while helping us identify edge cases like https://github.com/dequelabs/axe-core/issues/273 instead of passing them outright.
Closes https://github.com/dequelabs/axe-core/issues/319
> Color contrast: equal ratio as incomplete

- doc/projects.md
Added aXe-Testcafe a TestCafé module that allows you to use the aXe accessibility engine in TestCafe tests. (More on TestCafé here: http://devexpress.github.io/testcafe/)
> Updates projects.md

- lib/checks/mobile/meta-viewport-large.json
- lib/checks/mobile/meta-viewport.json
As per request of the great JF.
> Add 'on mobile' to viewport rule

- lib/checks/label/duplicate-img-label.js
- test/checks/label/duplicate-img-label.js
Closes https://github.com/dequelabs/axe-core/issues/386
> fix: use virtualNode in duplicate-img-label

- .gitignore
- Gruntfile.js
Noticed this during while creating another PR
> Minor build chores for whitespace and lockfile

- .retireignore.json
- test/checks/visibility/hidden-content.js
- test/commons/aria/attributes.js
- test/commons/dom/find-up.js
- test/commons/dom/get-composed-parent.js
- test/commons/dom/get-root-node.js
- test/commons/dom/has-content.js
- test/commons/dom/idrefs.js
- test/commons/dom/is-visible.js
- test/commons/text/visible.js
- test/core/utils/contains.js
- test/core/utils/flattened-tree.js
- test/core/utils/get-selector.js
- test/core/utils/is-hidden.js
- test/runner.tmpl
- test/testutils.js
To make v1 and v0 shadow support a little more portable, this PR introduces a test utility file. I'd to write tests for it, but I don't know the best place to put them without sinking a bunch of time into our build system. So if anyone has suggestions let me know and I can add some tests :)
> test: add shadowDOM test utility

- test/commons/dom/find-up.js
> test dom.findUp in shadow DOM v0

- .gitignore
- .retireignore.json
- CONTRIBUTING.md
- Gruntfile.js
- lib/checks/aria/required-parent.js
- lib/checks/color/color-contrast.js
- lib/checks/color/link-in-text-block.js
- lib/checks/label/explicit.js
- lib/checks/label/multiple-label.js
- lib/checks/shared/duplicate-id.js
- lib/checks/tables/td-headers-attr.js
- lib/checks/tables/th-has-data-cells.js
- lib/commons/table/is-header.js
- lib/commons/text/accessible-text.js
- lib/commons/text/label.js
- lib/core/utils/get-selector.js
- lib/core/utils/get-xpath.js
- lib/rules/color-contrast-matches.js
- test/checks/color/color-contrast.js
- test/checks/color/link-in-text-block.js
- test/checks/shared/duplicate-id.js
- test/commons/table/is-header.js
- test/core/utils/get-selector.js
The id property can be overloaded, so we should use getAttribute()
> fix implicit attribute use in duplicate-id

- test/checks/shared/button-has-visible-text.js
Closes https://github.com/dequelabs/axe-core/issues/419
> test: add unit tests for button-has-visible-text

- lib/core/base/rule.js
- test/core/base/rule.js
This PR should be added on top of #415.
Closes #394
> Pass virtualNode to rules to get color-contrast integration tests passing

- lib/checks/navigation/landmark.js
- test/checks/navigation/landmark.js
> feat: Add shadow DOM to landmark check

- lib/checks/aria/required-parent.js
- test/checks/aria/required-parent.js
Closes https://github.com/dequelabs/axe-core/issues/422
> feat(aria-required-parent): add Shadow DOM support

- lib/checks/color/link-in-text-block.js
- lib/commons/dom/is-in-text-block.js
- test/checks/color/link-in-text-block.js
- test/commons/dom/is-in-text-block.js
> feat(link-in-text-block): Add shadow DOM support

- lib/checks/forms/labelledby.js
- test/checks/forms/labelledby.js
Should close https://github.com/dequelabs/axe-core/issues/426.
> feat: add shadow support to group-labelledby

- lib/checks/forms/fieldset.js
- test/checks/forms/fieldset.js
This solves #425. It builds on #447 (which should be merged first).
> shadowDOM fieldset check

- build/tasks/add-locale.js
- build/tasks/configure.js
- build/tasks/fixture.js
- build/tasks/langs.js
- build/tasks/test-webdriver.js
- build/tasks/testconfig.js
- build/tasks/update-help.js
- build/tasks/validate.js
Feel free to suggest more descriptive task descriptions, if necessary! 
Closes https://github.com/dequelabs/axe-core/issues/364
> chore: add descriptions to Grunt tasks

- lib/commons/aria/index.js
- test/checks/aria/required-attr.js
- test/integration/rules/aria-required-attr/required-attr.html
- test/integration/rules/aria-required-attr/required-attr.json
> fix(aria): Allow implicit attribute values

- lib/commons/aria/index.js
Add support for role=feed, role=term, aria-placeholder, aria-modal,
aria-current and aria-keyshortcuts.
This PR closes #350.
> feat(aria): Support progressive ARIA 1.1 attributes / roles

- CHANGELOG
@dylanb do you want to review the changelog and develop branch before I cut the alpha release?
> chore: add changelog for 3.0.0-alpha-1

- lib/commons/aria/index.js
This closes a few issues: #275, #276, #282.
> Aria 1.1 fixes

- doc/API.md
> Update API.md - Fix Typo

- lib/core/public/run-rules.js
Fixes an issue reported in JIRA WWD-1115.
> fix: RestoreScroll was running  out of sync

- bin/postinstall.sh
- build/utils/postinstall.js
- package.json
Closes https://github.com/dequelabs/axe-core/issues/516
> fix(postinstall): use node, more conditionals

- lib/core/base/audit.js
- test/core/base/audit.js
Simple but important fix for releasing Coconut.
> fix: Match prerelease versions for helpUrl

- doc/projects.md
Ace (as in “Accessibility Checker for EPUB”) is a tool developed by
the DAISY Consortium to run automated checks and content extraction
in order to assist with the evaluation of EPUB accessibility.
It uses aXe under the hood to check EPUB’s XHTML Content Documents.
More info at https://daisy.github.io/ace/
> Add Ace by DAISY to the projects list

- appveyor.yml
Adds testing for Windows related to #519
Currently failing here for the last set of IE tests https://ci.appveyor.com/project/nschonni/axe-core/build/1.0.1
> build: add AppVeyor config

- lib/checks/aria/errormessage.js
- lib/checks/aria/errormessage.json
- lib/checks/aria/valid-attr-value.js
- lib/commons/aria/index.js
- lib/rules/aria-valid-attr-value.json
- test/checks/aria/errormessage.js
- test/integration/rules/aria-allowed-attr/passes.json
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
- test/runner.tmpl
- test/testutils.js
This PR adds #517 to the 2x branch. Rather than hard-coding a checkContext in the tests, I introduced a basic testutils file to ease the transition when we're finally ready to kill off the 2x branch.
> aria-errormessage for the 2x branch

- CONTRIBUTING.md
- doc/API.md
- doc/developer-guide.md
closes https://github.com/dequelabs/axe-core/issues/576
> docs: add notes about open Shadow DOM

- build/sri-update.js
- package.json
Hope this helps :) We'll add it to our auto-build tool.
> docs: Clarify how to use sri-history in sri-update.js

- lib/checks/shared/non-empty-if-present.js
- lib/commons/color/get-background-color.js
- lib/commons/text/index.js
- lib/core/utils/pollyfills.js
- test/checks/color/color-contrast.js
- test/checks/shared/non-empty-if-present.js
- test/commons/text/accessible-text.js
This fixed all but one issue with IE and Edge. The one issue still open is a color-contrast one, for some reason overlap wasn't getting caught in IE, if the element existed below the fold.
> Bunch of fixes for IE and Edge

- doc/rule-descriptions.md
- lib/core/utils/check-helper.js
- test/core/base/check.js
- test/integration/full/async/async.html
- test/integration/full/async/async.js
> fix bug with async checks (2)

- doc/API.md
- lib/core/utils/collect-results-from-frames.js
- test/core/utils/collect-results-from-frames.js
- test/integration/full/frame-wait-time/frame-wait-time.html
- test/integration/full/frame-wait-time/frame-wait-time.js
- test/integration/full/frame-wait-time/frames/frame.html
Closes https://github.com/dequelabs/axe-core/issues/660
> feat(collect-results-from-frames): add frameWaitTime option

- test/integration/full/context/context.html
- test/integration/full/context/context.js
- test/integration/full/document-title/document-title-fail.html
- test/integration/full/document-title/document-title-fail.js
- test/integration/full/document-title/document-title-pass.html
- test/integration/full/document-title/document-title-pass.js
- test/integration/full/html-has-lang/html-has-lang.html
- test/integration/full/html-has-lang/html-has-lang.js
- test/integration/full/html-lang-valid/html-lang-valid.html
- test/integration/full/html-lang-valid/html-lang-valid.js
- test/integration/full/landmark-main-is-top-level/landmark-main-is-top-level-fail.html
- test/integration/full/landmark-main-is-top-level/landmark-main-is-top-level-fail.js
- test/integration/full/landmark-main-is-top-level/landmark-main-is-top-level-pass.html
- test/integration/full/landmark-main-is-top-level/landmark-main-is-top-level-pass.js
- test/integration/full/options-parameter/options-parameter.html
- test/integration/full/options-parameter/options-parameter.js
- test/testutils.js
> test(testUtils): Add awaitNestedLoad utility function

- doc/API.md
- lib/core/public/configure.js
- test/core/public/configure.js
- test/integration/full/configure-options/configure-options.js
> axe.configure disableOtherRules option

- lib/checks/color/link-in-text-block.json
> docs(link-in-text-block): Improved check messages #742

- lib/commons/aria/index.js
- test/integration/rules/aria-allowed-attr/passes.html
- test/integration/rules/aria-required-attr/required-attr.html
- test/integration/rules/aria-required-attr/required-attr.json
> feat: Make aria-level required with role=heading #740

- axe.d.ts
- doc/API.md
Noticed this problem in one of the docs.
> docs: Correct minor API.md example

- lib/checks/navigation/region.js
- test/checks/navigation/region.js
- test/integration/full/region/region-fail.html
- test/integration/full/region/region-fail.js
- test/integration/full/region/region-pass.html
> fix(region): Ignore forms without accessible name as landmarks

- doc/rule-descriptions.md
- lib/checks/media/frame-tested.js
- lib/checks/media/frame-tested.json
- lib/core/utils/collect-results-from-frames.js
- lib/rules/frame-tested.json
- test/checks/media/frame-tested.js
- test/integration/full/frame-tested/frame-tested-fail.html
- test/integration/full/frame-tested/frame-tested-fail.js
- test/integration/full/frame-tested/frame-tested-incomplete.html
- test/integration/full/frame-tested/frame-tested-incomplete.js
- test/integration/full/frame-tested/frame-tested-pass.html
- test/integration/full/frame-tested/frame-tested-pass.js
- test/integration/full/frame-tested/frames/nested-no-axe.html
- test/integration/full/frame-tested/frames/no-axe.html
- test/integration/full/frame-tested/frames/with-axe.html
- test/testutils.js
> New rule: Test that frames have axe in them

- lib/core/base/audit.js
- lib/core/base/context.js
- lib/core/public/run-rules.js
- lib/core/public/run.js
- lib/core/utils/get-selector.js
- test/core/base/audit.js
- test/core/base/context.js
- test/core/public/run-rules.js
- test/core/utils/collect-results-from-frames.js
- test/core/utils/dq-element.js
- test/core/utils/get-selector.js
- test/integration/full/context/context.html
- test/integration/full/context/context.js
- test/testutils.js
> Shadow DOM exclude

- doc/API.md
- lib/core/base/audit.js
- test/core/base/audit.js
BREAKING CHANGE: Incorrect use of runOnly now throws errors
Closes #752
> feat: Make options.runOnly more forgiving about plurality

- lib/core/public/load.js
- lib/core/public/run-rules.js
- lib/core/public/run.js
- test/core/public/run-rules.js
- test/core/public/run.js
- test/core/reporters/na.js
- test/core/reporters/no-passes.js
- test/core/reporters/raw.js
- test/core/reporters/v1.js
- test/core/reporters/v2.js
- test/integration/full/rerun/frames/frame.html
- test/integration/full/rerun/rerun.html
- test/integration/full/rerun/rerun.js
Closes https://github.com/dequelabs/react-axe/issues/28
> fix: Avoid timing issue with axe cleanup method

- CONTRIBUTING.md
For some additional syntax highlighting
> chore: Add codefences for Contributing.md

- lib/checks/tables/same-caption-summary.js
- test/checks/tables/same-caption-summary.js
Closes https://github.com/dequelabs/axe-core/issues/771
> fix: allow mixed casing of caption/summary

- Gruntfile.js
- build/build-manual.js
- build/configure.js
- build/sri-update.js
- build/test/engine.js
- build/utils/postinstall.js
Opted the rest of the build folder into the linting and rans some more cleanups
> Eslint fixes

- CONTRIBUTING.md
Selenium is compatible with newer FF now
> chore: Drop note about Firefox 47 incompat

- lib/checks/navigation/internal-link-present.js
- lib/rules/skip-link-matches.js
- test/checks/navigation/internal-link-present.js
- test/integration/full/bypass/skip-link.html
- test/rule-matches/skip-link-matches.js
> fix: Ignore hashbang URLs for skiplinks

- test/checks/media/frame-tested.js
This one has been randomly crashing our test runner, depending on if the execution of the checks test took more than 500ms or not.
> chore: Fix async is null error in test runner

- doc/rule-descriptions.md
- lib/rules/checkboxgroup.json
- test/rule-matches/data-table-matches.js
There were two issues addressed here, but one was already fixed (#561). The other is a single word change in a check description.
Closes https://github.com/dequelabs/axe-core/issues/526
> Check typo & data-table matches tests

- .editorconfig
- .github/PULL_REQUEST_TEMPLATE.md
- .markdownlint.json
- README.md
- doc/API.md
- doc/accessibility-supported.md
- doc/code-submission-guidelines.md
- doc/developer-guide.md
- doc/examples/html-handlebars.md
- doc/plugins.md
- doc/rule-development.md
Enable and resolve a few more Markdownlint flagged items
```
[ ] Yes
[x] No
```
> Further markdownlint

- package.json
> chore(package): update grunt-contrib-watch to version 1.1.0

- package.json
> chore(package): update grunt-markdownlint to version 1.1.5

- locales/de.json
- feat: translated rules help and checks fail into German
> feat: translated rules help and checks fail into German

- lib/checks/aria/valid-scrollable-semantics.js
- test/integration/rules/focus-order-semantics/focus-order-semantics.html
- test/integration/rules/focus-order-semantics/focus-order-semantics.json
> fix(rules): Allow focusable role=application elements

- doc/examples/jest_react/package.json
> chore(package): update jest-cli to version 22.4.4

- doc/examples/jest_react/package.json
> chore(package): update react-dom to version 16.4.0

- doc/examples/jest_react/package.json
> chore(package): update jest-cli to version 23.0.1

- doc/API.md
> docs: Indicate that only experimental rules do not run by default

- lib/core/utils/get-friendly-uri-end.js
- test/core/utils/get-friendly-uri-end.js
Closes #788
- Github issue: Closes #788
> fix: Right trim URLs before outputting them in getSelector

- axe.d.ts
- Github issue: #938
Fixes #938.
> fix: Lowercased Boolean in axe.d.ts

- lib/core/utils/aggregateChecks.js
- Github issue: https://github.com/dequelabs/axe-core/issues/960
> fix(lib/core/utils/aggregateChecks.js): don’t trust `indexOf(undefined)` to do the right thing.

- lib/core/utils/aggregateChecks.js
- Github issue: https://github.com/dequelabs/axe-core/issues/960
> Fix `type: none` outcome swapping

- axe.d.ts
- Github issue: closes #974
These types may either be a string or a function.
> fix(axe.d.ts): correct `Check.evaluate` and `Check.after` types

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
> chore: Update github templates

- lib/rules/aria-allowed-attr.json
- lib/rules/aria-required-attr.json
- lib/rules/aria-roles.json
- lib/rules/aria-valid-attr-value.json
- lib/rules/aria-valid-attr.json
Affects the following rules:
- aria-allowed-attr
- aria-required-attr
- aria-roles
- aria-valid-attr
- aria-valid-attr-value
Closes #986
[ ] Follows the commit message policy, appropriate for next version
[ ] Has documentation updated, a DU ticket, or requires no documentation change
[ ] Includes new tests, or was unnecessary
[ ] Code is reviewed for security by: << Name here >>
> feat: Tag aria rules as WCAG 2, SC4.1.2 issues

- .github/PULL_REQUEST_TEMPLATE.md
> chore: Fix PR template

- lib/checks/shared/aria-labelledby.json
Clear up error message for aria-labelledby check.
Closes issue: #1004 
> fix: Clearer fail message for aria-labelledby

- axe.d.ts
- package.json
- tsconfig.json
- tslint.json
- typings/axe-core/axe-core-tests.ts
- Added additional test case for typescript definitions/ interface changes.
- Run typescript definition tests as a part of npm test.
Closes issue: 
- https://github.com/dequelabs/axe-core/issues/979
> fix: validate typescript declarations using tests

- package.json
- test/checks/lists/dlitem.js
- test/checks/lists/listitem.js
- test/checks/lists/only-dlitems.js
- test/checks/lists/only-listitems.js
This patch upgrades Prettier to the latest version and runs it on some non-prettified files.
> chore: upgrade Prettier and run the formatter

- .npmrc
This patch adds an `.npmrc` file to the project which:
- ensures npm uses the correct registry
- ensures npm does not create a `package-lock.json` file (since we don't check it in anyway)
> chore: add `.npmrc`

- lib/commons/aria/index.js
- test/integration/rules/aria-valid-attr/aria-valid-attr.html
- test/integration/rules/aria-valid-attr/aria-valid-attr.json
Allow aria-errormessage if a fallback is provided.
Closes #1043 
> fix(aria-valid-attr): Allow aria-errormessage with fallback

- lib/commons/aria/index.js
- test/integration/rules/aria-required-attr/required-attr.html
- test/integration/rules/aria-required-attr/required-attr.json
Add new required properties:
- combobox required aria-expanded
- radio required aria-checked
Closes #969
> fix: Add combobox and radio required properties

- doc/projects.md
> docs: Add Terra to Project Community List

- lib/checks/keyboard/page-has-main.json
- lib/checks/keyboard/page-no-duplicate-banner.json
- lib/checks/keyboard/page-no-duplicate-contentinfo.json
- lib/checks/keyboard/page-no-duplicate-main.json
- lib/rules/landmark-no-duplicate-banner.json
- lib/rules/landmark-no-duplicate-contentinfo.json
- lib/rules/landmark-one-main.json
A minor fix that was missed in #983 
Closes issue: #983
> fix(messages): Change messages from "page" to "document" where appropriate

- package.json
> chore: add missing `eslint` dev dep

- .eslintrc
- lib/core/public/run.js
This updates our ESLint configuration, enabling usage of ES6-features (eg `Promise`).
See https://github.com/dequelabs/axe-core/pull/1256/files#r236574957.
> chore: add `es6: true` to ESLint config

- doc/API.md
> docs: Add wcag21aa tag to API docs

- package.json
For developer convenience, added `npm start` and `npm run develop` scripts.
> chore: add npm script for develop/ start

- .github/CODEOWNERS
> chore: Add Stephen as codeowner for core

- locales/ja.json
Minor adjustments to make the message easier to understand
> fix(i18n): Fix Japanese translation

- build/rule-generator/directories.js
- lib/commons/aria/attributes.js
- lib/commons/aria/is-unsupported-role.js
- package.json
CI failed for a bunch of dependency updates, attempted by greenkeeper bot. This PR fixes the lint errors and re-updates the relevant dependencies.
Closes issue:
- https://github.com/dequelabs/axe-core/issues/1277
- https://github.com/dequelabs/axe-core/issues/1373
- https://github.com/dequelabs/axe-core/issues/1371
> chore: update dependencies

- CHANGELOG.md
- bower.json
- package.json
- sri-history.json
> chore: Update from master

- lib/commons/text/label-text.js
- lib/commons/text/native-text-methods.js
- lib/commons/text/subtree-text.js
- lib/core/utils/preload-cssom.js
- test/commons/text/label-text.js
- test/commons/text/native-text-methods.js
- test/commons/text/subtree-text.js
> chore: run prettier

- build/tasks/langs.js
- build/tasks/test-webdriver.js
some of the grunt tasks are failing due to the promise package import that does not exist:
Removing this dependency as part of this PR.
> chore: remove unused promise dependency

- doc/projects.md
> adding https://accessibilityinsights.io/

- doc/examples/jest_react/package.json
> chore(docs): update enzyme and enzyme-adapter-react-16 dependencies

- README.md
Add a note in the Support Browsers section about being able to run when features are natively supported or polyfilled correctly.
Closes: #1136 
> docs: add note about supported environments

- test/integration/full/incomplete/th-has-data-cells.html
- test/integration/full/xml-lang-mismatch/xml-lang-mismatch.pass2.html
- test/integration/rules/label/label.html
- test/integration/rules/p-as-heading/p-as-heading.html
This patch fixes some HTML issues (extra closing tags, mismatched tags, etc). This enables us to run Prettier over our HTML files (PR incoming).
I assume these HTML issues were accidental 🤷‍♀️
> test: Fix invalid test html

- doc/examples/jasmine/package.json
Another false negative.
Closes issue: #1498
> chore: update karma to version 4.1.0

- doc/projects.md
* Updates the Accessibility Insights entry text to match its normal branding
* Adds new entries to the end of the Community Projects list for our new projects, [axe-sarif-converter](https://github.com/microsoft/axe-sarif-converter) and [Axe + Azure Pipelines samples](https://github.com/microsoft/axe-pipelines-samples)
Closes issue: n/a
> chore: update microsoft community project links in project.md

- doc/projects.md
> docs: Update project.md

- package.json
> chore(package): update husky to version 2.4.0

- package.json
> chore(package): update lint-staged to version 8.2.0

- locales/ja.json
Updated Japanese locale for axe-core 3.3.0 release.
> chore(i18n): Update Japanese locale

- locales/ja.json
Cherry pick locale pr for 3.3.0 release
> chore(i18n): Update Japanese locale (#1632)

- CHANGELOG.md
> docs: fix 3.3.0 changelog date

- doc/examples/chrome-debugging-protocol/package.json
- doc/examples/jasmine/package.json
- doc/examples/jest_react/package.json
- doc/examples/jsdom/package.json
- doc/examples/mocha/package.json
- doc/examples/phantomjs/package.json
- doc/examples/puppeteer/package.json
- doc/examples/qunit/package.json
> docs: update axe-core version to 3.3.0

- package.json
> Chore: update to babel 7.5.4

- lib/commons/dom/is-visible.js
- test/commons/dom/is-visible.js
> feat(is-visible): add support for clip-path techniques

- .github/PULL_REQUEST_TEMPLATE.md
Spoke with @WilcoFiers about this and we decided we want to simplify the review process.
> chore: Update PULL_REQUEST_TEMPLATE and remove unnecessary boxes

- lib/checks/tables/caption-faked.json
- Update string to be clearer
Closes issue: #1749 
> chore: update fail message for `caption-faked` to be more clear

- lib/checks/label/multiple-label.js
- lib/checks/label/multiple-label.json
- lib/rules/form-field-multiple-labels.json
- test/checks/label/multiple-label.js
- test/integration/rules/form-field-multiple-labels/form-field-multiple-labels.html
- test/integration/rules/form-field-multiple-labels/form-field-multiple-labels.json
> fix(form-field-multiple-label): incomplete rather than fail for multiple labels

- lib/core/public/configure.js
- test/core/public/configure.js
Address comments in https://github.com/dequelabs/axe-core/pull/1793#pullrequestreview-287690504
> feat(configure): accept ver property as axeVersion fallback

- locales/pt_BR.json
- Add pt_BR localization for Axe messages
> Feat: pt_BR localization

- doc/API.md
> docs: Update tags in API.md

- lib/commons/aria/index.js
- test/checks/aria/aria-allowed-role.js
- test/commons/aria/is-aria-role-allowed-on-element.js
> fix: allows all roles on img tag with no alt attribute

- test/integration/api/external/index.js
The test in question fails frequently in Windows and that behavior is not important to axe Pro.
> test: removes flaky test in axe Pro api check

- lib/commons/dom/is-hidden-with-css.js
Caches the computation result.
Closes issue:https://github.com/dequelabs/axe-core/issues/1717
> perf(is-hidden-with-css): Cache result

- locales/ko.json
Add Korean translation file locales/ko.json
> chore(i18n): Add Korean locale translation

- lib/commons/aria/index.js
see https://www.w3.org/WAI/PF/aria/roles#widget_roles
> fix: remove heading from list of widget roles

- lib/rules/button-name.json
- test/integration/rules/button-name/button-name.html
> fix(button-name): input[role=button] with value should pass

- appveyor.yml
Install a known working version of iedriver.
> test: install working version of iedriver to run windows tests

- lib/core/utils/collect-results-from-frames.js
- test/integration/full/frame-wait-time/frame-wait-time.js
Test is still flakey in appveyor.
> test: fix frameWaitTime flakey test

- doc/code-submission-guidelines.md
> docs: remove tabs from code-submission-guidelines

- build/configure.js
- lib/core/base/audit.js
- test/core/public/load.js
> fix(build): add lang query parameter to helpUrl when builing with a locale

- .circleci/config.yml
- lib/core/utils/preload-cssom.js
> docs: fix building api-docs

- locales/da.json
Adds Danish localization of Ace.
Thanks for your great work from Nota in Denmark.
> feat(i18n): add Danish (da-DK) translation

- doc/developer-guide.md
- lib/commons/dom/visually-contains.js
- test/commons/dom/is-visible.js
> docs(some documents and comments): fixed typo

- locales/ja.json
Noticed the changes, so I updated the Japanese localization.
> chore(i18n): update ja.json

- locales/fr.json
Translations provided by @dboudreau 
Closes issue: #1786, #1518 
> chore(i18n): Update French locale

- .circleci/config.yml
> ci: run test_win before release

- .circleci/config.yml
- .gitignore
- .npmrc
- CHANGELOG.md
- bower.json
- lib/checks/color/color-contrast.js
- locales/fr.json
- package-lock.json
- package.json
- sri-history.json
- test/checks/color/color-contrast.js
Develop merged a feat so we couldn't just take from develop. Had to branch from the 3.5.0 branch and cherry-pick all non-feat merges.
> Release 3.5.1

- test/checks/tables/td-headers-attr.js
Noticed that the markup was wrong in some of the test fixtures, when I was doing some validations on this rule.
Closes issue:
- NA
> test(td-headers-attr): update test fixtures

- doc/backwards-compatibility-doc.md
> docs: add change policy for tags in rules

- locales/pt_BR.json
- Localize new strings and changes in singular/plural mechanism
> chore(i18n): Update pt_BR.json

- README.md
- doc/API.md
> chore: run prettier formatting

- lib/commons/text/unicode.js
- test/commons/text/unicode.js
> fix(color-contrast): mark more punctuations for review

- .eslintrc
- Gruntfile.js
- lib/commons/forms/index.js
- lib/commons/forms/is-aria-combobox.js
- lib/commons/forms/is-aria-listbox.js
- lib/commons/forms/is-aria-range.js
- lib/commons/forms/is-aria-textbox.js
- lib/commons/forms/is-native-select.js
- lib/commons/forms/is-native-textbox.js
> chore: update commons.forms to ES Modules

- lib/checks/navigation/header-present.json
> fix(header-present): update verbiage to use heading instead of header

- lib/checks/mobile/meta-viewport-scale.js
- test/checks/mobile/meta-viewport-scale.js
Closes issue:
- https://github.com/dequelabs/axe-core/issues/2136
> fix(meta-viewport): parse negative and string values for `maximum-scale`

- lib/checks/keyboard/focusable-element.js
- test/checks/keyboard/focusable-element.js
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.html
- test/integration/rules/scrollable-region-focusable/scrollable-region-focusable.json
> fix(scrollable-region-focusable): pass for elements with contenteditable

- lib/checks/parsing/duplicate-id.json
> fix(duplicate-id): list the duplicate id in message

- .eslintrc
- Gruntfile.js
- lib/core/reporters/helpers/failure-summary.js
- lib/core/reporters/helpers/get-environment-data.js
- lib/core/reporters/helpers/incomplete-fallback-msg.js
- lib/core/reporters/helpers/index.js
- lib/core/reporters/helpers/process-aggregate.js
- lib/core/reporters/na.js
- lib/core/reporters/no-passes.js
- lib/core/reporters/not-index.js
- lib/core/reporters/raw-env.js
- lib/core/reporters/raw.js
- lib/core/reporters/reporters.js
- lib/core/reporters/v1.js
- lib/core/reporters/v2.js
- test/core/reporters/helpers/000_runfirst.js
- test/core/reporters/raw-env.js
- test/core/reporters/v1.js
> refactor(core/reporters): Convert to ES modules

- doc/API.md
> docs(API): improve descriptions in the tags table

- .eslintrc
- lib/checks/color/color-contrast-evaluate.js
- lib/checks/color/color-contrast.json
- lib/checks/color/link-in-text-block-evaluate.js
- lib/checks/color/link-in-text-block.json
- lib/checks/forms/autocomplete-appropriate-evaluate.js
- lib/checks/forms/autocomplete-appropriate.json
- lib/checks/forms/autocomplete-valid-evaluate.js
- lib/checks/forms/autocomplete-valid.json
- lib/core/base/metadata-function-map.js
forms/fieldset and forms/group-labelledby are deprecated and were not converted. They will be [removed for 4.0](https://github.com/dequelabs/axe-core/issues/2189).
> refactor(color,forms): convert color and forms checks to es modules

- .eslintrc
- lib/checks/visibility/hidden-content-evaluate.js
- lib/checks/visibility/hidden-content.json
- lib/core/base/metadata-function-map.js
> refactor(checks/visibility): Convert to ES Modules

- .eslintrc
- lib/checks/parsing/duplicate-id-active.json
- lib/checks/parsing/duplicate-id-after.js
- lib/checks/parsing/duplicate-id-aria.json
- lib/checks/parsing/duplicate-id-evaluate.js
- lib/checks/parsing/duplicate-id.json
- lib/core/base/metadata-function-map.js
This work was done by a robot and needs to be manually tested before it's ready for review
> refactor(checks/parsing): Convert to ES Modules

- .eslintrc
- lib/checks/tables/caption-faked-evaluate.js
- lib/checks/tables/caption-faked.json
- lib/checks/tables/has-caption-evaluate.js
- lib/checks/tables/has-caption.json
- lib/checks/tables/has-summary-evaluate.js
- lib/checks/tables/has-summary.json
- lib/checks/tables/has-th-evaluate.js
- lib/checks/tables/has-th.json
- lib/checks/tables/headers-visible-text.js
- lib/checks/tables/html5-scope-evaluate.js
- lib/checks/tables/html5-scope.json
- lib/checks/tables/same-caption-summary-evaluate.js
- lib/checks/tables/same-caption-summary.json
- lib/checks/tables/scope-value-evaluate.js
- lib/checks/tables/scope-value.json
- lib/checks/tables/td-has-header-evaluate.js
- lib/checks/tables/td-has-header.json
- lib/checks/tables/td-headers-attr-evaluate.js
- lib/checks/tables/td-headers-attr.json
- lib/checks/tables/th-has-data-cells-evaluate.js
- lib/checks/tables/th-has-data-cells.json
- lib/checks/tables/th-single-row-column.js
- lib/core/base/metadata-function-map.js
> refactor(checks/tables): Convert to ES Modules

- .eslintrc
- lib/checks/mobile/css-orientation-lock-evaluate.js
- lib/checks/mobile/css-orientation-lock.json
- lib/checks/mobile/meta-viewport-large.json
- lib/checks/mobile/meta-viewport-scale-evaluate.js
- lib/checks/mobile/meta-viewport.json
- lib/core/base/metadata-function-map.js
> refactor(checks/mobile): Convert to ES Modules

- .eslintrc
- lib/checks/keyboard/accesskeys-after.js
- lib/checks/keyboard/accesskeys-evaluate.js
- lib/checks/keyboard/accesskeys.json
- lib/checks/keyboard/focusable-content-evaluate.js
- lib/checks/keyboard/focusable-content.json
- lib/checks/keyboard/focusable-disabled-evaluate.js
- lib/checks/keyboard/focusable-disabled.json
- lib/checks/keyboard/focusable-element-evaluate.js
- lib/checks/keyboard/focusable-element.json
- lib/checks/keyboard/focusable-modal-open-evaluate.js
- lib/checks/keyboard/focusable-modal-open.json
- lib/checks/keyboard/focusable-no-name-evaluate.js
- lib/checks/keyboard/focusable-no-name.json
- lib/checks/keyboard/focusable-not-tabbable-evaluate.js
- lib/checks/keyboard/focusable-not-tabbable.json
- lib/checks/keyboard/landmark-is-top-level-evaluate.js
- lib/checks/keyboard/landmark-is-top-level.json
- lib/checks/keyboard/page-has-elm-after.js
- lib/checks/keyboard/page-has-elm-evaluate.js
- lib/checks/keyboard/page-has-heading-one.json
- lib/checks/keyboard/page-has-main.json
- lib/checks/keyboard/page-no-duplicate-after.js
- lib/checks/keyboard/page-no-duplicate-banner.json
- lib/checks/keyboard/page-no-duplicate-contentinfo.json
- lib/checks/keyboard/page-no-duplicate-evaluate.js
- lib/checks/keyboard/page-no-duplicate-main.json
- lib/checks/keyboard/tabindex-evaluate.js
- lib/checks/keyboard/tabindex.json
- lib/core/base/metadata-function-map.js
> refactor(checks/keyboard): convert to es modules

- .eslintrc
- lib/checks/label/alt-space-value-evaluate.js
- lib/checks/label/alt-space-value.json
- lib/checks/label/duplicate-img-label-evaluate.js
- lib/checks/label/duplicate-img-label.json
- lib/checks/label/explicit-evaluate.js
- lib/checks/label/explicit.json
- lib/checks/label/help-same-as-label-evaluate.js
- lib/checks/label/help-same-as-label.json
- lib/checks/label/hidden-explicit-label-evaluate.js
- lib/checks/label/hidden-explicit-label.json
- lib/checks/label/implicit-evaluate.js
- lib/checks/label/implicit.json
- lib/checks/label/label-content-name-mismatch-evaluate.js
- lib/checks/label/label-content-name-mismatch.json
- lib/checks/label/multiple-label-evaluate.js
- lib/checks/label/multiple-label.json
- lib/checks/label/title-only-evaluate.js
- lib/checks/label/title-only.json
- lib/core/base/metadata-function-map.js
> refactor(checks/label): convert to es modules

- axe.d.ts
Add the `element` property to `NodeResult` interface.
> types: add `element` to NodeResults

- build/configure.js
- doc/rule-descriptions.md
> docs(rule-descriptions): add note intead of empty table

- lib/checks/language/has-lang-evaluate.js
- lib/checks/language/has-lang.json
- test/checks/language/has-lang.js
Part of https://github.com/dequelabs/axe-core/issues/2195
> feat(has-lang): add option for which attributes to look at

- lib/checks/lists/listitem-evaluate.js
- test/checks/lists/listitem.js
- test/integration/rules/listitem/listitem.html
- test/integration/rules/listitem/listitem.json
> fix(listitem): do not fail for parent with role=presentation|none

- lib/checks/tables/scope-value-evaluate.js
- lib/checks/tables/scope-value.json
- test/checks/tables/scope-value.js
> feat(scope-value): add options for valid scope values

- CHANGELOG.md
- bower.json
- lib/commons/dom/get-element-stack.js
- package-lock.json
- package.json
- sri-history.json
- test/commons/dom/get-element-stack.js
> Release 3.5.4

- axe.d.ts
> fix(types): Add "wcag21aa" and "wcag21a" to our TS definition

- axe.d.ts
> fix(types): Add missing properties to `Spec`

- lib/commons/dom/get-element-stack.js
- lib/commons/dom/get-rect-stack.js
- lib/commons/dom/is-visible.js
- test/checks/color/color-contrast.js
- test/commons/dom/get-element-stack.js
- test/commons/dom/is-visible.js
Also cleaned up some imports while I was there.
Closes issue: #2261 and #2262 
> fix(is-visible): return false for opacity: 0 and 0 height scrollable regions

- CHANGELOG.md
- bower.json
- lib/checks/color/color-contrast.js
- lib/checks/lists/listitem.js
- lib/checks/mobile/meta-viewport-scale.js
- lib/commons/dom/is-visible.js
- lib/core/public/configure.js
- lib/rules/aria-input-field-name.json
- package-lock.json
- package.json
- sri-history.json
- test/checks/color/color-contrast.js
- test/checks/lists/listitem.js
- test/checks/mobile/meta-viewport-scale.js
- test/commons/dom/is-visible.js
- test/core/public/configure.js
- test/integration/rules/listitem/listitem.html
- test/integration/rules/listitem/listitem.json
Hand copied fixes for 3.5.5. Here are their originating prs:
- fix(meta-viewport): https://github.com/dequelabs/axe-core/pull/2238
- fix(listitem): https://github.com/dequelabs/axe-core/pull/2241
- fix(aria-input-filed-name): https://github.com/dequelabs/axe-core/pull/2266
- fix(color-contrast): https://github.com/dequelabs/axe-core/pull/2276
- fix(is-visible): https://github.com/dequelabs/axe-core/pull/2283
- fix(configure): https://github.com/dequelabs/axe-core/pull/2293
Closes issue: #2280
> chore: Release 3.5.5

- CHANGELOG.md
- bower.json
- package-lock.json
- package.json
- sri-history.json
Cherry-picked the release commit back into develop since we had to hand copy all the changes into master.
> chore: merge master

- lib/commons/aria/lookup-table.js
- test/integration/rules/aria-allowed-attr/passes.html
> fix(aria-allowed-attr): allow aria-activedescendant on role=application

- lib/checks/lists/dlitem-evaluate.js
- test/checks/lists/dlitem.js
> fix(dlitem): allow role=presentation on parent dl

- axe.d.ts
> fix(types): Allow `impact` to be `null`

- lib/commons/aria/arialabel-text.js
> chore: refactor arialabel-text

- lib/core/utils/closest.js
> chore(closest): correct return type

- lib/checks/keyboard/page-has-heading-one.json
- test/integration/full/page-has-heading-one/page-has-heading-one-pass1.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass2.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass2.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass3.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass4.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass4.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass5.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass5.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass6.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass6.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass7.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass7.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass8.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass8.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass9.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass9.js
Properly take aria-level into account for page-has-heading-one
Closes issue: #2348
> fix(page-has-h1): allow aria-level=1 on native headings

- lib/checks/shared/non-empty-if-present-evaluate.js
- test/checks/shared/non-empty-if-present.js
> fix(input-button-name): work with virtual nodes

- lib/checks/shared/button-has-visible-text.json
- test/checks/shared/button-has-visible-text.js
> fix(button-name): work with serial virtual node

- lib/commons/aria/is-accessible-ref.js
- test/commons/aria/is-accessible-ref.js
> chore(is-accessible-ref): work with standards object

- doc/API.md
> docs(configure): config must happen in each iframe

- test/integration/virtual-rules/area-alt.js
- test/integration/virtual-rules/aria-input-field-name.js
- test/integration/virtual-rules/aria-toggle-field-name.js
- test/integration/virtual-rules/button-name.js
- test/integration/virtual-rules/index.html
- test/integration/virtual-rules/input-button-name.js
> tests: add serial tests for button-name, input-button-name, aria-toggle-field-name, aria-input-field-name, and area-alt

- test/integration/virtual-rules/index.html
- test/integration/virtual-rules/role-img-alt.js
> tests: add test for role-img-alt for serial nodes

- lib/checks/shared/svg-non-empty-title-evaluate.js
- test/integration/virtual-rules/index.html
- test/integration/virtual-rules/svg-img-alt.js
> tests: add test for svg-img-alt for serial nodes

- .github/workflows/sync-master-develop.yml
> ci: Add "sync branches" workflow

- axe.d.ts
- typings/axe-core/axe-core-tests.ts
Closes issue: #2316, #2317, #2378
> fix(typings): update types file

- lib/core/base/rule.js
- test/core/base/rule.js
> fix(rule): allow impact to be configured

- doc/code-submission-guidelines.md
> docs: note how to author breaking change commits

- doc/developer-guide.md
Fixed links in [developer-guide.md](../blob/develop/doc/developer-guide.md/) to point to appropriate files after refactor/rename.
Closes issue: #2449
> docs: fix links

- .gitignore
Ignore Jetbrains IDEs (IntelliJ, WebStorm, ...)
> chore: gitignore .idea

- lib/checks/navigation/meta-refresh-evaluate.js
- test/checks/navigation/meta-refresh.js
Use vitrual node rather than node
Closes issue #2467
> refactor(meta-refresh): use virtual node

- lib/checks/keyboard/tabindex-evaluate.js
- test/checks/keyboard/tabindex.js
> refactor(tabindex): work with virtual nodes

- lib/checks/aria/aria-hidden-body-evaluate.js
- test/checks/aria/aria-hidden-body.js
> refactor(aria-hidden-body): work with virtual nodes

- lib/checks/label/title-only-evaluate.js
Update title-only-evaluate to work with virtualNode
Closes issue: fixes #2473 
> refactor(title-only-evaluate): work with virtual nodes

- lib/checks/media/caption-evaluate.js
Update caption-evaluate to work with virtualNodes
Closes issue: fixes #2469 
> refactor(caption-evaluate): work with virtual nodes

- lib/checks/navigation/unique-frame-title-evaluate.js
- test/checks/navigation/unique-frame-title.js
refactor(unique-frame-title): work with vNodes
Closes issue:
#2468 
> refactor(unique-frame-title): work with vNodes

- lib/checks/language/xml-lang-mismatch-evaluate.js
- test/checks/language/xml-lang-mismatch.js
refactor(xml-lang-mismatch): work with virtualNodes
Closes issue: #2471 
> refactor(xml-lang-mismatch): work with virtualNodes

- lib/checks/lists/structured-dlitems-evaluate.js
Update structured-dlitems-evaluate to work with virtualNodes
Closes issue: fixes #2470
> refactor(structured-dlitems-evaluate): work with virtual nodes

- lib/checks/language/valid-lang-evaluate.js
- test/checks/language/valid-lang.js
- test/integration/rules/valid-lang/valid-lang.html
- test/integration/rules/valid-lang/valid-lang.json
> fix(valid-lang): fail when lang attribute contains only whitespace

- lib/checks/label/duplicate-img-label-evaluate.js
refactor(duplicate-img-label-evaluate): work with virtualNodes
Closes issue: #2472
> refactor(duplicate-img-label-evaluate): work with virtualNodes

- lib/standards/aria-roles.js
> fix: add group to meniitemradio context

- doc/API.md
> docs(API): add reviewOnFail

- lib/commons/table/get-headers.js
- test/commons/table/get-headers.js
> fix(get-headers): fix for rowspan and colspan

- doc/projects.md
Addition of the `vue-axe` package
> docs: Update projects.md

- lib/core/utils/get-scroll-state.js
- lib/core/utils/set-scroll-state.js
> feat(utils): deprecate get/set-scroll-state

- lib/standards/dpub-roles.js
Same as #2600. Needed for #1677
> feat(standards): add superclassRole to dpubRoles

- README.md
> docs(readme): replace Gitter with Slack badge

- lib/checks/navigation/region.json
- test/checks/navigation/region.js
> fix(region): allow role=alertdialog as region

- .circleci/config.yml
- test/integration/full/test-webdriver.js
The new test-runner file that allows multiple browsers in a single command kept failing so moving it back to a single browser runner.
> tests: fix flakey integration test

- .github/PULL_REQUEST_TEMPLATE.md
- .github/review.yml
> chore: add PR review app yml file

- doc/projects.md
> docs(projects): update to current Deque project names

- locales/pl.json
> feat(locale): Polish translation

- Gruntfile.js
Now when you save a test file the tests will be rerun.
> chore: watch tests and rerun in develop

- package-lock.json
- package.json
Security upgrade according to dependabot.
> chore: upgrade node-notifier to 8.0.1

- lib/checks/aria/aria-errormessage-evaluate.js
- test/checks/aria/errormessage.js
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
- test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.json
> fix(aria-valid-attr-value): pass for aria-errormessage when aria-invalid is not set or false

- lib/rules/layout-table-matches.js
- test/rule-matches/frame-title-has-text-matches.js
- test/rule-matches/inserted-into-focus-order-matches.js
- test/rule-matches/layout-table-matches.js
- test/rule-matches/link-in-text-block-matches.js
- test/rule-matches/no-role-matches.js
- test/rule-matches/not-html-matches.js
Added tests for all missing rule-matches.
Closes issue: #2403
> tests: add missing tests for rule-matches

- lib/rules/frame-title.json
> fix(frame-title): update rule description to be more descriptive

- lib/checks/keyboard/landmark-is-top-level-evaluate.js
- test/checks/keyboard/landmark-is-top-level.js
- test/integration/full/landmark-complementary-is-top-level/frames/level1-fail.html
- test/integration/full/landmark-complementary-is-top-level/landmark-complementary-is-top-level-pass.html
- test/integration/full/landmark-complementary-is-top-level/landmark-complementary-is-top-level-pass.js
> fix(landmark-complementary-is-top-level): allow aside inside main

- test/playground.html
This was snuck into #2745 on accident.
> tests: revert playground

- test/rule-matches/aria-required-parent-matches.js
- test/rule-matches/frame-title-has-text-matches.js
- test/rule-matches/inserted-into-focus-order-matches.js
- test/rule-matches/layout-table-matches.js
- test/rule-matches/link-in-text-block-matches.js
- test/rule-matches/no-role-matches.js
- test/rule-matches/not-html-matches.js
Replace with the new `axe.utils.getRule`
> tests: remove all use of axe._audit.rules.find

- lib/checks/aria/aria-allowed-attr-evaluate.js
- lib/checks/aria/aria-unsupported-attr-evaluate.js
- lib/rules/aria-allowed-attr-matches.js
- test/checks/aria/allowed-attr.js
- test/integration/virtual-rules/aria-allowed-attr.js
- test/rule-matches/aria-allowed-attr-matches.js
> chore: allow aria-allowed-attr to run virtually

- lib/rules/area-alt.json
- lib/rules/aria-command-name.json
- lib/rules/aria-toggle-field-name.json
- lib/rules/aria-tooltip-name.json
- lib/rules/aria-treeitem-name.json
- lib/rules/button-name.json
- lib/rules/frame-title.json
- lib/rules/input-button-name.json
- lib/rules/label.json
- lib/rules/select-name.json
> chore: put checks in order of preferred solution

- lib/checks/mobile/meta-viewport-scale-evaluate.js
- test/checks/mobile/meta-viewport-scale.js
- test/integration/virtual-rules/meta-viewport.js
> chore: allow meta-viewport to run virtually

- test/integration/virtual-rules/meta-refresh.js
> tests: add virtual test for meta-refresh

- lib/checks/aria/aria-required-attr-evaluate.js
- test/checks/aria/aria-required-attr.js
- test/integration/virtual-rules/aria-required-attr.js
> chore: allow aria-required-attr to run virtually

- lib/checks/aria/unsupportedrole-evaluate.js
- test/checks/aria/unsupportedrole.js
- test/integration/virtual-rules/aria-roles.js
> chore: allow aria-roles to run virtually

- lib/rules/bypass.json
- test/integration/full/bypass/fail.js
- test/integration/full/bypass/header-iframe-fail.js
- test/integration/full/bypass/header-iframe-pass.js
- test/integration/full/bypass/pass-tests.js
> fix(bypass): mark as needs review rather than failure

- .circleci/config.yml
- doc/API.md
> docs: add docs for new features

- lib/rules/label-hidden-field.json
This is the smallest PR I've done, but here goes:
> add the css selector

- lib/checks/language/has-lang-evaluate.js
- lib/core/public/run-virtual-rule.js
- test/integration/virtual-rules/html-has-lang.js
> chore: allow html-has-lang to run virtually

- doc/rule-descriptions.md
Another rule file update where the changes weren't rebuilt, probably due to accepting suggestions in the github interface but not rebuilding the code.
> chore: rerun rule-description

- .github/ISSUE_TEMPLATE.md
Add instructions and field for product
> chore:update to add product field for easier triage

- lib/checks/navigation/heading-order-after.js
- test/checks/navigation/heading-order.js
> fix(heading-order): handle iframe as first result

- locales/de.json
Fixed some simple typos in the german language file, added two missing translations and corrected some other simple stuff.
> refactor(german-translation): corrected some simple aspects

- locales/ja.json
Add missing Japanese translations, based on the develop branch as of 2021-06-03.
> chore(i18n): update locales/ja.json

- lib/checks/visibility/hidden-content-evaluate.js
rename to allowlist
Closes issue:
> chore: rename to allowlist

- lib/checks/aria/aria-valid-attr-evaluate.js
- lib/rules/aria-has-attr-matches.js
- test/checks/aria/valid-attr.js
- test/integration/virtual-rules/aria-valid-attr.js
- test/rule-matches/aria-has-attr-matches.js
> chore: allow aria-valid-attr to run virtually

- test/core/utils/respondable.js
Attempt to stop this test from failing half the time.
Related #2849
> test(respondable): add retries

- lib/checks/generic/page-no-duplicate-evaluate.js
- test/checks/keyboard/page-no-duplicate.js
> fix(page-no-duplicate): don't count elements hidden from screenreaders as potential duplicates

- lib/core/base/virtual-node/virtual-node.js
- lib/core/utils/matches.js
- lib/core/utils/query-selector-all-filter.js
- test/commons/matches/node-name.js
- test/core/utils/matches.js
- test/core/utils/qsa.js
Taken from https://github.com/dequelabs/axe-core/pull/3018. Seeing if this will allow CircleCI to pick this up and run tests.
> perf(core): reduce memory allocations

- axe.d.ts
Add types for:
- axe.utils.getFrameContexts
- axe.runPartial
- axe.finishRun
Related to #3059
> chore(d.ts): type runPartial + finishRun

- README.md
> docs: note supported locales

- package.json
> fix: add sri-history.json to npm bundle

- axe.d.ts
Last thing we need to fix finishRun. Should have been done in #3096 but we forgot
> fix(axe.d.ts): fix finishRun types

- locales/fr.json
Updated translation based on the develop branch.
> chore(i18n): updated french translation

- locales/ko.json
- Update translation based on currently develop branch
- Change some of existing translation to make it easier to understand
> chore(i18n) Update Korean locale translate

- axe.d.ts
Found myself needing this type in a few places, so I'm adding it.
> fix(d.ts): Add PartialResults type

- doc/projects.md
> docs: add a11y-sitechecker to community projects

- README.md
Checked the links, skipping the redirect HTTP => HTTPS this way 0:-)
> chore: update package quality to use HTTPS

- lib/commons/aria/get-element-unallowed-roles.js
- lib/commons/aria/is-aria-role-allowed-on-element.js
- test/checks/aria/aria-allowed-role.js
- test/commons/aria/is-aria-role-allowed-on-element.js
Proposed update to #3142
Didn't want to push the changes directly to that PR, and putting it all into comments seemed a bit too confusing too.
> chore(getElementUnallowedRoles): Clean-up work

- doc/API.md
I have fixed a wrongly styled headline.
Closes issue: na
> docs: Fixed wrong styling

- package-lock.json
- package.json
> chore: update to use `@axe-core/webdriverjs@4.3.2`

- lib/checks/label/label-content-name-mismatch-evaluate.js
- lib/commons/text/accessible-text-virtual.js
- lib/commons/text/visible-text-nodes.js
- test/checks/label/label-content-name-mismatch.js
- test/commons/text/accessible-text.js
> fix(label-content-name-mismatch): account for formatting elements

- axe.d.ts
> fix(d.ts): correct getFrameContexts return type

- locales/ko.json
- Update translation for items added after Aug 2021
- changed '인터랙티브' to '대화형'
Closes issue:
> chore(i18n): Update Korean locale translate

- package.json
Should help prevent #3374 in the future.
> chore: add rule-descriptions to release script

- .circleci/config.yml
> ci: fix go release script

- doc/issue_impact.md
> docs: add link from issue_impact to rule-descriptions

- lib/checks/generic/has-descendant-evaluate.js
- lib/checks/keyboard/page-has-heading-one.json
- lib/checks/keyboard/page-has-main.json
- test/integration/full/landmark-one-main/landmark-one-main-pass4.html
- test/integration/full/landmark-one-main/landmark-one-main-pass4.js
- test/integration/full/page-has-heading-one/page-has-heading-one-pass10.html
- test/integration/full/page-has-heading-one/page-has-heading-one-pass10.js
> fix(page-has-heading-one,landmark-one-main): do not fail if modal is open

- doc/projects.md
docs: change /docs/projects.md to include mitm-play
mitm-play now integrated axe-core as command line parameter: -A / --a11y
Closes issue: n/a
> docs: change /docs/projects.md to include mitm-play

- .circleci/config.yml
See: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
> ci: update to use `cimg` for circleci

- package.json
> fix: Continue supporting Node >=4

- lib/rules/video-caption.json
- test/integration/rules/video-caption/video-caption.html
> fix(video-caption): remove excludeHidden: false

- test/act-mapping/aria-allowed-attr.json
> test(aria-allowed-attr): put back act test aria-props-permitted

- doc/projects.md
As requested by Deque's Mike Farrell.
> docs(projects): add Sitebulb

- lib/checks/aria/aria-busy-evaluate.js
- lib/checks/aria/aria-busy.json
- lib/rules/aria-required-children.json
- test/checks/aria/aria-busy.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
> feat(aria-required-children): add aria-busy check

- .github/workflows/auto-assign-issues.yml
> ci: update github project board link

- locales/_template.json
> chore: sync locales/_template

- lib/checks/shared/presentational-role-evaluate.js
- test/checks/aria/has-global-aria-attribute.js
- test/checks/aria/is-element-focusable.js
- test/integration/virtual-rules/presentation-role-conflict.js
- use virtual node
references: https://github.com/dequelabs/axe-core/issues/3473
> refactor(presentation-role-conflict): use virtual node

- build/configure.js
- doc/rule-descriptions.md
- lib/rules/identical-links-same-purpose.json
Ensure all AAA rules are disabled by default
Closes issue: #3611
> feat(identical-links-same-purpose): Disable AAA rules by default

- SECURITY.md
> docs: add security channel

- lib/commons/aria/get-element-unallowed-roles.js
- lib/commons/dom/has-lang-text.js
- lib/commons/dom/is-hidden-with-css.js
- locales/_template.json
- test/act-mapping/valid-lang.json
- test/commons/dom/has-lang-text.js
- test/commons/dom/is-hidden-with-css.js
- test/integration/rules/valid-lang/valid-lang.html
- test/integration/rules/valid-lang/valid-lang.json
> fix(valid-lang): run on aria-hidden text

- lib/core/_exposed-for-testing.js
- lib/core/core.js
- lib/core/reporters/helpers/index.js
- lib/core/utils/index.js
> refactor: put all internal function exports into same file

- test/playground.html
I find myself repeatedly making changes to the playground to:
1. Add runOnly to run a single rule
2. Add a landmark and heading to ensure no violations from best practices
I also included testUtils, so I can use awaitNestedLoad, which is helpful from time to time.
> chore: update playground

- sri-history.json
Release 4.5.0 with proper sri-history numbers.
> chore(release): 4.5.0 (sir-history corrected)

- lib/checks/aria/aria-required-children.json
- test/checks/aria/required-children.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
> fix(aria-required-children): allow menu and menubar to be empty

- lib/checks/color/link-in-text-block-evaluate.js
- lib/rules/link-in-text-block-matches.js
- test/checks/color/link-in-text-block.js
- test/integration/rules/link-in-text-block/link-in-text-block.html
- test/rule-matches/link-in-text-block-matches.js
> fix(link-in-text-block): don't match style or script text

- lib/core/reporters/helpers/process-aggregate.js
- test/core/reporters/helpers/process-aggregate.js
> chore: Ensure relatedNodes fallback uses arrays

- .circleci/config.yml
bump circleci/browser-tools to 1.4.0
> ci: bump circleci/browser-tools to 1.4.0

- .circleci/config.yml
> ci: run on node 16.18

- .circleci/config.yml
circleci: bump cimg/go to latest
> ci: bump cimg/go image

- lib/standards/aria-roles.js
- test/integration/rules/aria-required-children/aria-required-children.html
- test/integration/rules/aria-required-children/aria-required-children.json
> fix(aria-required-children): allow menu as child of menu

- .circleci/config.yml
> ci: Fix release CircleCI job

- README.md
> docs(readme): mistyped a name

- lib/rules/color-contrast-matches.js
- test/rule-matches/color-contrast-matches.js
> fix(color-contrast): skip ligature icons

- lib/commons/text/is-icon-ligature.js
Based on a conversation on #3867, just so we have a reference of the potential issue.
> chore(iconLigature): comment on possible false positive

- .circleci/config.yml
Second attempt at releasing 4.6.3 (PR #3872). Fix a CI issue, caused by us having optimised CI recently.
> chore(release): 4.6.3 (corrected)

- lib/commons/dom/create-grid.js
As part of my review of #3930 I ended up refactoring that method. I couldn't wrap my brain around how it worked.
> chore: Refactor createStackingOrder

- doc/examples/puppeteer/package.json
See: https://github.com/puppeteer/puppeteer/issues/9940
> ci(examples): remove puppeteer pin

- doc/projects.md
The link for Terra Toolkit was broken.
> docs(projects): fix link for terra loolkit

- README.md
Added 2.2 and added AAA, also moved the link to the full set of rules to a more appropriate position
> docs: add WCAG 2.2 and level AAA

- lib/standards/aria-roles.js
- test/integration/rules/aria-allowed-attr/passes.html
> fix(aria-allowed-attr): Add 'aria-required' to switch role

- locales/ja.json
Reflect the changes in PR #4144 (quote usage)
Update checks/target-offset to be in line with the current messages.
Update rules/aria-allowed-attr to be in-line with the current messages.
> chore(i18n): update Japanese translation

- .circleci/config.yml
> ci: unpin chromedriver version

- package-lock.json
- package.json
Saw we didn't use `proxyquire` anywhere so removing it.
> chore(deps): remove proxyquire

- .circleci/config.yml
> ci: update to node v18

- locales/it.json
create it.json following template
This pull request contains the Italian translation of a JSON template related to accessibility auditing. The translation includes all the keys and values of the original JSON, ensuring that the meaning and context of each message are accurately conveyed in Italian. The translation was carefully reviewed to ensure that it meets quality standards
> feat(i18n): Add Italian translation

- lib/checks/lists/listitem.json
- locales/_template.json
Editorial fix based on feedback from the Italian localization.
> fix(listitem): clarify roleNotValid message

- locales/it.json
Thanks to @giacomo-petri for reviewing the Italian translation for accuracy.
No QA needed.
> fix(i18n): update Italian translations

- locales/de.json
> chore: Update local de.json

- package-lock.json
- package.json
update to use the latest version of `@axe-core/webdriverjs`
> test: update `@axe-core/webdriverjs` package

- lib/commons/color/element-is-distinct.js
- lib/commons/color/flatten-shadow-colors.js
- lib/commons/color/get-background-stack.js
- lib/commons/color/get-contrast.js
- lib/commons/color/has-valid-contrast-ratio.js
- lib/commons/dom/get-composed-parent.js
- lib/commons/dom/get-element-coordinates.js
- lib/commons/dom/get-scroll-offset.js
- lib/commons/dom/has-content-virtual.js
- lib/commons/dom/is-focusable.js
- lib/commons/dom/is-in-text-block.js
- lib/commons/dom/visually-overlaps.js
- lib/commons/index.js
- lib/commons/table/get-all-cells.js
- lib/commons/table/get-cell-position.js
- lib/commons/table/is-data-table.js
- lib/commons/table/to-grid.js
- lib/commons/text/label-virtual.js
Just like https://github.com/dequelabs/axe-core/pull/4451 but for `lib/commons`
Smaller part of the full vision: https://github.com/dequelabs/axe-core/pull/4444
> style(lib/commons): var -> let and const codemod

- locales/ja.json
Update Japanese translation to reflect the changes made after 2023-09-12.
> chore(i18n): update Japanese translation to reflect changes occurred after 2023-09-12

- locales/de.json
> chore: Update locale de.json

- doc/projects.md
A11y Audit Elixir is my project which allows running axe-core in browser-based tests in Elixir, failing the tests if accessibility violations are found.
> docs(projects): add a11y-audit-elixir

- README.md
Allows people to more easily see the total NPM downloads of axe-core.
> docs(readme): link download badge to npm-stats.com

- doc/accessibility-supported.md
Updates the link to WebAims Screen Reader User Survey to point to the current survey.
> docs: update link for WebAims Screen Reader User Survey

- CHANGELOG.md
- bower.json
- lib/core/utils/get-ancestry.js
- package-lock.json
- package.json
- sri-history.json
- test/core/utils/get-ancestry.js
- **get-ancestry:** don't error when there is no parent ([#4617](https://github.com/dequelabs/axe-core/issues/4617)) ([6c07102](https://github.com/dequelabs/axe-core/commit/6c07102b1d29145b8dc5f1d96229f3d0b8b38068))
> chore(release): 4.10.2

- lib/checks/media/caption.json
- locales/_template.json
Thanks @somaalapati for reporting the issue
> fix(captions): fix grammar in captions check incomplete message

- locales/ko.json
> chore: fix missing period in ko locales

- .github/dependabot.yml
@see https://github.com/dequelabs/axe-core/pull/4691/files
> chore: prevent @types/node > 4

- locales/pt_PT.json
> feat(i18n): Add Portugal Portuguese translation

- doc/projects.md
Added trademark information to the projects page
> docs: add trademarks information to the projects page

- axe.d.ts
Ran into a couple mistakes in the raw types.
> fix(types): correct raw types
